// SEED DATA: These are placeholder listings to be replaced with real scraped data
// from state wildlife agencies, outfitter associations, and verified registrations.
// All entries below have verified: false and source: 'seed'.

import type { HuntingGuide } from './guides';

// Seed entries omit verified/source -- defaults applied in guide-data.ts
export type SeedGuide = Omit<HuntingGuide, 'verified' | 'source'>;

export const guidesAM: SeedGuide[] = [
  // ============================================================
  // ALABAMA (AL)
  // ============================================================
  {
    id: 1,
    name: 'Cade Holcomb',
    businessName: 'Blackbelt Outfitters',
    state: 'Alabama',
    stateCode: 'AL',
    city: 'Selma',
    species: ['Whitetail', 'Hog', 'Turkey'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'Specializes in trophy whitetail hunts across the Alabama Black Belt region. Manages over 3,000 acres of prime hardwood bottoms and food plots.',
    phone: '(555) 201-4410',
    email: 'cade@blackbeltoutfitters.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 87,
  },
  {
    id: 2,
    name: 'Jolene Massey',
    businessName: 'Wiregrass Hunt Co.',
    state: 'Alabama',
    stateCode: 'AL',
    city: 'Dothan',
    species: ['Whitetail', 'Turkey'],
    methods: ['Rifle', 'Shotgun'],
    experience: '12+ years',
    description: 'Family-friendly guided hunts in the Wiregrass region with heated blinds and all-inclusive lodging packages.',
    phone: '(555) 201-7823',
    email: 'jolene@wiregrasshunt.example.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 42,
  },
  {
    id: 3,
    name: 'Travis Dupree',
    businessName: 'Gulf Pines Guide Service',
    state: 'Alabama',
    stateCode: 'AL',
    city: 'Mobile',
    species: ['Hog', 'Whitetail'],
    methods: ['Rifle', 'Bow', 'Crossbow'],
    experience: '8+ years',
    description: 'Year-round wild hog hunts on private timber land along the Mobile River Delta. Night hunts available with thermal optics.',
    phone: '(555) 201-3356',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.3,
    reviewCount: 29,
  },
  {
    id: 4,
    name: 'Darnell Washington',
    businessName: 'Coosa Valley Hunting',
    state: 'Alabama',
    stateCode: 'AL',
    city: 'Talladega',
    species: ['Whitetail', 'Turkey', 'Hog'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Semi-guided and fully guided whitetail packages in the Coosa River valley. Trophy management program with strict harvest guidelines.',
    phone: '(555) 201-9901',
    email: 'darnell@coosavalley.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 63,
  },

  // ============================================================
  // ALASKA (AK)
  // ============================================================
  {
    id: 5,
    name: 'Erik Strandberg',
    businessName: 'Denali Ridge Expeditions',
    state: 'Alaska',
    stateCode: 'AK',
    city: 'Fairbanks',
    species: ['Moose', 'Bear', 'Mule Deer'],
    methods: ['Rifle', 'Bow'],
    experience: '25+ years',
    description: 'Backcountry fly-in moose and grizzly hunts in the Alaska Range. Fully outfitted base camps with bush pilot transport.',
    phone: '(555) 907-1120',
    email: 'erik@denaliridge.example.com',
    website: 'https://denaliridge.example.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.9,
    reviewCount: 112,
  },
  {
    id: 6,
    name: 'Mara Kenai',
    businessName: 'Tundra Born Outfitters',
    state: 'Alaska',
    stateCode: 'AK',
    city: 'Anchorage',
    species: ['Moose', 'Bear'],
    methods: ['Rifle'],
    experience: '18+ years',
    description: 'Remote peninsula bear hunts and interior moose expeditions with experienced native Alaskan guides.',
    phone: '(555) 907-2245',
    email: 'mara@tundraborn.example.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 78,
  },
  {
    id: 7,
    name: 'Nolan Harrigan',
    businessName: 'Yukon Crossing Adventures',
    state: 'Alaska',
    stateCode: 'AK',
    city: 'Juneau',
    species: ['Bear', 'Mule Deer'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'Coastal brown bear hunts in southeast Alaska with boat-based access to remote bays and salmon streams.',
    phone: '(555) 907-3378',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 54,
  },

  // ============================================================
  // ARIZONA (AZ)
  // ============================================================
  {
    id: 8,
    name: 'Marco Esparza',
    businessName: 'Sonoran Trophy Hunts',
    state: 'Arizona',
    stateCode: 'AZ',
    city: 'Tucson',
    species: ['Mule Deer', 'Elk', 'Predator'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'Guided mule deer and Coues deer hunts in the Sonoran Desert foothills. Specializes in spot-and-stalk with glassing setups.',
    phone: '(555) 480-1102',
    email: 'marco@sonorantrophy.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 71,
  },
  {
    id: 9,
    name: 'Bryce Keller',
    businessName: 'Rim Country Outfitters',
    state: 'Arizona',
    stateCode: 'AZ',
    city: 'Payson',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '22+ years',
    description: 'High-country elk and mule deer hunts along the Mogollon Rim. Excellent success rates on archery and rifle elk.',
    phone: '(555) 480-2239',
    email: 'bryce@rimcountry.example.com',
    website: 'https://rimcountry.example.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.9,
    reviewCount: 98,
  },
  {
    id: 10,
    name: 'Catalina Reyes',
    businessName: 'Desert Stalker Guide Service',
    state: 'Arizona',
    stateCode: 'AZ',
    city: 'Flagstaff',
    species: ['Elk', 'Predator'],
    methods: ['Rifle', 'Bow'],
    experience: '10+ years',
    description: 'Specializes in Arizona unit 9 and 10 elk tags with extensive knowledge of public land access points.',
    phone: '(555) 480-3365',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 33,
  },

  // ============================================================
  // ARKANSAS (AR)
  // ============================================================
  {
    id: 11,
    name: 'Dale Renfrow',
    businessName: 'Ozark Ridge Outfitters',
    state: 'Arkansas',
    stateCode: 'AR',
    city: 'Mountain Home',
    species: ['Whitetail', 'Turkey', 'Elk'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '18+ years',
    description: 'Guided whitetail hunts in the rugged Ozark Mountains with access to limited-entry elk zones in the Buffalo River area.',
    phone: '(555) 501-1144',
    email: 'dale@ozarkridge.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 52,
  },
  {
    id: 12,
    name: 'Beau Calhoun',
    businessName: 'Delta Bottoms Hunting Club',
    state: 'Arkansas',
    stateCode: 'AR',
    city: 'Stuttgart',
    species: ['Whitetail', 'Waterfowl'],
    methods: ['Rifle', 'Shotgun'],
    experience: '25+ years',
    description: 'Combination whitetail and duck hunts in the Arkansas Delta with flooded timber blinds and heated deer stands.',
    phone: '(555) 501-2278',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 88,
  },
  {
    id: 13,
    name: 'Patsy Ledford',
    businessName: 'Timber Creek Guide Co.',
    state: 'Arkansas',
    stateCode: 'AR',
    city: 'Little Rock',
    species: ['Whitetail', 'Hog'],
    methods: ['Rifle', 'Bow'],
    experience: '10+ years',
    description: 'Affordable guided whitetail and hog hunts on private ranches surrounding central Arkansas river bottoms.',
    phone: '(555) 501-3390',
    email: 'patsy@timbercreekguide.example.com',
    priceRange: '$',
    buckStopPartner: false,
    rating: 4.2,
    reviewCount: 18,
  },

  // ============================================================
  // CALIFORNIA (CA)
  // ============================================================
  {
    id: 14,
    name: 'Dustin Pham',
    businessName: 'Sierra Crest Outfitters',
    state: 'California',
    stateCode: 'CA',
    city: 'Redding',
    species: ['Mule Deer', 'Bear', 'Hog'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'Spot-and-stalk blacktail and mule deer hunts in the northern Sierra Nevada and Cascade foothills.',
    phone: '(555) 916-1155',
    email: 'dustin@sierracrest.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 44,
  },
  {
    id: 15,
    name: 'Kyle Mendonca',
    businessName: 'Central Valley Hog Hunts',
    state: 'California',
    stateCode: 'CA',
    city: 'Bakersfield',
    species: ['Hog'],
    methods: ['Rifle', 'Bow', 'Crossbow'],
    experience: '8+ years',
    description: 'Year-round wild hog hunts on 10,000+ acres of private ranch land in the central California foothills.',
    phone: '(555) 916-2288',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.3,
    reviewCount: 37,
  },
  {
    id: 16,
    name: 'Janet Cordero',
    businessName: 'Pacific Ridge Pursuits',
    state: 'California',
    stateCode: 'CA',
    city: 'Eureka',
    species: ['Mule Deer', 'Elk', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '12+ years',
    description: 'Roosevelt elk and blacktail deer hunts in Humboldt and Del Norte counties along the rugged coastal ranges.',
    phone: '(555) 916-3312',
    email: 'janet@pacificridge.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 51,
  },

  // ============================================================
  // COLORADO (CO)
  // ============================================================
  {
    id: 17,
    name: 'Tanner Ridgeway',
    businessName: 'High Basin Outfitters',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Gunnison',
    species: ['Elk', 'Mule Deer', 'Whitetail'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '25+ years',
    description: 'Premier guided elk hunts in GMU 54 and 55 with pack-in camps above 10,000 feet in the West Elk Wilderness.',
    phone: '(555) 303-1177',
    email: 'tanner@highbasin.example.com',
    website: 'https://highbasin.example.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.9,
    reviewCount: 134,
  },
  {
    id: 18,
    name: 'Rosa Villarreal',
    businessName: 'Sangre Peak Expeditions',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Salida',
    species: ['Elk', 'Mule Deer'],
    methods: ['Rifle', 'Bow'],
    experience: '18+ years',
    description: 'Backcountry mule deer and elk hunts in the Sangre de Cristo range with horseback access to remote basins.',
    phone: '(555) 303-2200',
    email: 'rosa@sangrepeaks.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 76,
  },
  {
    id: 19,
    name: 'Cole Brannon',
    businessName: 'Mesa Verde Hunts',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Durango',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '14+ years',
    description: 'Southwest Colorado hunts on private ranches with over-the-counter and draw tag options for elk and mule deer.',
    phone: '(555) 303-3345',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 48,
  },
  {
    id: 20,
    name: 'Wayne Litchfield',
    businessName: 'Flat Tops Wilderness Guides',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Meeker',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '30+ years',
    description: 'Third-generation outfitter running horseback elk camps in the Flat Tops Wilderness. Consistently high harvest rates.',
    phone: '(555) 303-4478',
    email: 'wayne@flattopsguides.example.com',
    website: 'https://flattopsguides.example.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 5.0,
    reviewCount: 147,
  },

  // ============================================================
  // CONNECTICUT (CT)
  // ============================================================
  {
    id: 21,
    name: 'Owen Bartlett',
    businessName: 'Nutmeg Whitetail Guides',
    state: 'Connecticut',
    stateCode: 'CT',
    city: 'Litchfield',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Shotgun', 'Muzzleloader'],
    experience: '12+ years',
    description: 'Guided whitetail hunts on private farmland in northwest Connecticut with a focus on mature bucks.',
    phone: '(555) 860-1133',
    email: 'owen@nutmegwhitetail.example.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 22,
  },
  {
    id: 22,
    name: 'Sienna Marsh',
    businessName: 'Connecticut Valley Hunts',
    state: 'Connecticut',
    stateCode: 'CT',
    city: 'Middletown',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Shotgun'],
    experience: '8+ years',
    description: 'Archery-focused whitetail hunts along the Connecticut River valley agricultural corridor.',
    phone: '(555) 860-2266',
    priceRange: '$',
    buckStopPartner: false,
    rating: 4.2,
    reviewCount: 14,
  },
  {
    id: 23,
    name: 'Greg Danforth',
    businessName: 'Housatonic Outdoor Guides',
    state: 'Connecticut',
    stateCode: 'CT',
    city: 'New Milford',
    species: ['Whitetail'],
    methods: ['Bow', 'Muzzleloader'],
    experience: '10+ years',
    description: 'Small-property bowhunting specialist who manages parcels in Fairfield and Litchfield counties for trophy whitetail.',
    phone: '(555) 860-3399',
    email: 'greg@housatonicoutdoor.example.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 27,
  },

  // ============================================================
  // DELAWARE (DE)
  // ============================================================
  {
    id: 24,
    name: 'Chester Norwood',
    businessName: 'First State Hunting',
    state: 'Delaware',
    stateCode: 'DE',
    city: 'Dover',
    species: ['Whitetail', 'Turkey'],
    methods: ['Shotgun', 'Bow', 'Muzzleloader'],
    experience: '10+ years',
    description: 'Guided whitetail hunts on agricultural leases in Kent County with quality deer management practices.',
    phone: '(555) 302-1122',
    email: 'chester@firststatehunting.example.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.3,
    reviewCount: 19,
  },
  {
    id: 25,
    name: 'Holly Pennington',
    businessName: 'Delmarva Field Sports',
    state: 'Delaware',
    stateCode: 'DE',
    city: 'Georgetown',
    species: ['Whitetail', 'Waterfowl'],
    methods: ['Shotgun', 'Bow'],
    experience: '14+ years',
    description: 'Combination deer and waterfowl hunts on the Delmarva Peninsula with access to marsh and timber tracts.',
    phone: '(555) 302-2255',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 31,
  },
  {
    id: 26,
    name: 'Reggie Townsend',
    businessName: 'Brandywine Outfitters',
    state: 'Delaware',
    stateCode: 'DE',
    city: 'Wilmington',
    species: ['Whitetail'],
    methods: ['Bow', 'Crossbow'],
    experience: '7+ years',
    description: 'Urban-edge bowhunting specialist managing suburban deer populations on private estates in New Castle County.',
    phone: '(555) 302-3388',
    priceRange: '$',
    buckStopPartner: false,
    rating: 4.1,
    reviewCount: 11,
  },

  // ============================================================
  // FLORIDA (FL)
  // ============================================================
  {
    id: 27,
    name: 'Rico Castillo',
    businessName: 'Everglades Outback Hunts',
    state: 'Florida',
    stateCode: 'FL',
    city: 'Okeechobee',
    species: ['Hog', 'Whitetail', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Crossbow'],
    experience: '15+ years',
    description: 'Year-round hog hunts and seasonal whitetail packages on sprawling cattle ranches surrounding Lake Okeechobee.',
    phone: '(555) 305-1188',
    email: 'rico@evergladesoutback.example.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 66,
  },
  {
    id: 28,
    name: 'Tamika Groves',
    businessName: 'Panhandle Sportsman Guides',
    state: 'Florida',
    stateCode: 'FL',
    city: 'Tallahassee',
    species: ['Whitetail', 'Turkey', 'Hog'],
    methods: ['Rifle', 'Bow'],
    experience: '12+ years',
    description: 'North Florida whitetail and Osceola turkey hunts on pine plantation land with food plot management.',
    phone: '(555) 305-2211',
    email: 'tamika@panhandlesportsman.example.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 49,
  },
  {
    id: 29,
    name: 'Logan Thibault',
    businessName: 'Sunshine State Hog Control',
    state: 'Florida',
    stateCode: 'FL',
    city: 'Ocala',
    species: ['Hog'],
    methods: ['Rifle', 'Bow', 'Crossbow'],
    experience: '8+ years',
    description: 'Guided and unguided hog hunts with night vision and thermal options on central Florida ranch land.',
    phone: '(555) 305-3344',
    priceRange: '$',
    buckStopPartner: false,
    rating: 4.3,
    reviewCount: 38,
  },

  // ============================================================
  // GEORGIA (GA)
  // ============================================================
  {
    id: 30,
    name: 'Mason Treadwell',
    businessName: 'Piedmont Trophy Hunts',
    state: 'Georgia',
    stateCode: 'GA',
    city: 'Macon',
    species: ['Whitetail', 'Turkey', 'Hog'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Trophy-managed whitetail hunts on 5,000 acres of Georgia Piedmont with a proven track record of 140-class bucks.',
    phone: '(555) 404-1199',
    email: 'mason@piedmonttrophy.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 91,
  },
  {
    id: 31,
    name: 'Amber Culpepper',
    businessName: 'South Georgia Field Guides',
    state: 'Georgia',
    stateCode: 'GA',
    city: 'Albany',
    species: ['Whitetail', 'Hog', 'Turkey'],
    methods: ['Rifle', 'Shotgun', 'Bow'],
    experience: '14+ years',
    description: 'Plantation-style guided hunts in the quail belt of south Georgia with whitetail, hog, and turkey options.',
    phone: '(555) 404-2222',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 57,
  },
  {
    id: 32,
    name: 'Dwayne Pickens',
    businessName: 'Blue Ridge Backcountry',
    state: 'Georgia',
    stateCode: 'GA',
    city: 'Blue Ridge',
    species: ['Whitetail', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '10+ years',
    description: 'Mountain whitetail and black bear hunts in the Chattahoochee National Forest with rustic cabin lodging.',
    phone: '(555) 404-3355',
    email: 'dwayne@blueridgeback.example.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 34,
  },

  // ============================================================
  // HAWAII (HI)
  // ============================================================
  {
    id: 33,
    name: 'Keoni Nakamura',
    businessName: 'Island Wild Hunts',
    state: 'Hawaii',
    stateCode: 'HI',
    city: 'Kailua-Kona',
    species: ['Hog', 'Predator'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'Wild boar and feral goat hunts on the slopes of Mauna Kea with stunning volcanic terrain and ocean views.',
    phone: '(555) 808-1144',
    email: 'keoni@islandwild.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 53,
  },
  {
    id: 34,
    name: 'Leilani Akiona',
    businessName: 'Aloha Range Outfitters',
    state: 'Hawaii',
    stateCode: 'HI',
    city: 'Lihue',
    species: ['Hog', 'Predator'],
    methods: ['Rifle', 'Bow'],
    experience: '10+ years',
    description: 'Guided wild boar and feral goat hunts on private ranch land across Kauai with experienced local trackers.',
    phone: '(555) 808-2277',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 28,
  },
  {
    id: 35,
    name: 'Kai Fernandez',
    businessName: 'Maui Mountain Hunts',
    state: 'Hawaii',
    stateCode: 'HI',
    city: 'Kahului',
    species: ['Hog', 'Predator'],
    methods: ['Rifle', 'Bow', 'Crossbow'],
    experience: '12+ years',
    description: 'Axis deer and wild boar hunts on Maui ranch properties with spot-and-stalk methods through tropical terrain.',
    phone: '(555) 808-3300',
    email: 'kai@mauimountain.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 41,
  },

  // ============================================================
  // IDAHO (ID)
  // ============================================================
  {
    id: 36,
    name: 'Grant Westfall',
    businessName: 'Sawtooth Wilderness Outfitters',
    state: 'Idaho',
    stateCode: 'ID',
    city: 'Stanley',
    species: ['Elk', 'Mule Deer', 'Whitetail'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '28+ years',
    description: 'Premier pack-in elk hunts in the Frank Church Wilderness with mule train access to remote high-country camps.',
    phone: '(555) 208-1166',
    email: 'grant@sawtoothoutfitters.example.com',
    website: 'https://sawtoothoutfitters.example.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.9,
    reviewCount: 121,
  },
  {
    id: 37,
    name: 'Darla Koehler',
    businessName: 'Clearwater Basin Guides',
    state: 'Idaho',
    stateCode: 'ID',
    city: 'Orofino',
    species: ['Elk', 'Whitetail', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '16+ years',
    description: 'Clearwater drainage elk and whitetail hunts with excellent public land access and local knowledge of migration corridors.',
    phone: '(555) 208-2299',
    email: 'darla@clearwaterbasin.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 68,
  },
  {
    id: 38,
    name: 'Caleb Sorensen',
    businessName: 'Snake River Outfitting',
    state: 'Idaho',
    stateCode: 'ID',
    city: 'Boise',
    species: ['Mule Deer', 'Elk', 'Predator'],
    methods: ['Rifle', 'Bow'],
    experience: '12+ years',
    description: 'Southwestern Idaho mule deer and elk hunts with OTC tag availability and comfortable wall tent camps.',
    phone: '(555) 208-3322',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 45,
  },
  {
    id: 39,
    name: 'Pete Langston',
    businessName: 'Panhandle Ridge Guides',
    state: 'Idaho',
    stateCode: 'ID',
    city: 'Coeur d\'Alene',
    species: ['Whitetail', 'Elk', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'North Idaho whitetail and elk hunts in the timbered mountains of the panhandle with lodge-based accommodations.',
    phone: '(555) 208-4455',
    email: 'pete@panhandleridge.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 59,
  },

  // ============================================================
  // ILLINOIS (IL)
  // ============================================================
  {
    id: 40,
    name: 'Travis Brennan',
    businessName: 'Prairie State Trophy Whitetails',
    state: 'Illinois',
    stateCode: 'IL',
    city: 'Quincy',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Shotgun', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Pike County trophy whitetail hunts on managed farms consistently producing Boone & Crockett-class bucks.',
    phone: '(555) 217-1188',
    email: 'travis@prairiestatetrophy.example.com',
    website: 'https://prairiestatetrophy.example.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.9,
    reviewCount: 115,
  },
  {
    id: 41,
    name: 'Casey Drummond',
    businessName: 'Shawnee Hills Outfitters',
    state: 'Illinois',
    stateCode: 'IL',
    city: 'Harrisburg',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Crossbow'],
    experience: '12+ years',
    description: 'Southern Illinois archery whitetail hunts in the rolling hardwood hills of the Shawnee National Forest area.',
    phone: '(555) 217-2211',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 52,
  },
  {
    id: 42,
    name: 'Monica Voss',
    businessName: 'Illinois River Bottoms Guide Service',
    state: 'Illinois',
    stateCode: 'IL',
    city: 'Peoria',
    species: ['Whitetail'],
    methods: ['Bow', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Whitetail hunts along the Illinois River corridor with treestands and ground blinds overlooking hardwood flats and crop fields.',
    phone: '(555) 217-3344',
    email: 'monica@ilriverbottoms.example.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 39,
  },

  // ============================================================
  // INDIANA (IN)
  // ============================================================
  {
    id: 43,
    name: 'Brett Underwood',
    businessName: 'Hoosier Hardwoods Outfitters',
    state: 'Indiana',
    stateCode: 'IN',
    city: 'Bloomington',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Shotgun', 'Muzzleloader'],
    experience: '18+ years',
    description: 'Trophy whitetail hunts on managed timber and agricultural land in the rolling hills of southern Indiana.',
    phone: '(555) 317-1100',
    email: 'brett@hoosierhardwoods.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 64,
  },
  {
    id: 44,
    name: 'Haley Pickering',
    businessName: 'Wabash Valley Guide Service',
    state: 'Indiana',
    stateCode: 'IN',
    city: 'Terre Haute',
    species: ['Whitetail'],
    methods: ['Bow', 'Crossbow'],
    experience: '10+ years',
    description: 'Archery whitetail hunts on private farmland along the Wabash River with elevated box blinds and food plot setups.',
    phone: '(555) 317-2233',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 28,
  },
  {
    id: 45,
    name: 'Levi Ashcraft',
    businessName: 'Crossroads Whitetails',
    state: 'Indiana',
    stateCode: 'IN',
    city: 'Muncie',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Shotgun'],
    experience: '14+ years',
    description: 'East-central Indiana whitetail hunts with a quality management approach targeting bucks four years and older.',
    phone: '(555) 317-3366',
    email: 'levi@crossroadswhitetails.example.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 35,
  },

  // ============================================================
  // IOWA (IA)
  // ============================================================
  {
    id: 46,
    name: 'Keith Halverson',
    businessName: 'Hawkeye Trophy Pursuits',
    state: 'Iowa',
    stateCode: 'IA',
    city: 'Decorah',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Shotgun', 'Muzzleloader'],
    experience: '22+ years',
    description: 'Northeast Iowa trophy whitetail hunts on bluff-country farms with a strict age-based harvest program.',
    phone: '(555) 515-1122',
    email: 'keith@hawkeyetrophy.example.com',
    website: 'https://hawkeyetrophy.example.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.9,
    reviewCount: 102,
  },
  {
    id: 47,
    name: 'Shane Roberson',
    businessName: 'River Hills Hunting',
    state: 'Iowa',
    stateCode: 'IA',
    city: 'Ottumwa',
    species: ['Whitetail'],
    methods: ['Bow', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Southern Iowa whitetail hunts in the legendary big-buck counties with private land access and heated blinds.',
    phone: '(555) 515-2255',
    email: 'shane@riverhillshunting.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 79,
  },
  {
    id: 48,
    name: 'Nikki Steffens',
    businessName: 'Tall Corn Outfitters',
    state: 'Iowa',
    stateCode: 'IA',
    city: 'Des Moines',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Shotgun'],
    experience: '10+ years',
    description: 'Guided whitetail hunts on agricultural land across central Iowa with comfortable farmhouse lodging.',
    phone: '(555) 515-3388',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 33,
  },

  // ============================================================
  // KANSAS (KS)
  // ============================================================
  {
    id: 49,
    name: 'Blake Summerlin',
    businessName: 'Flint Hills Whitetail Ranch',
    state: 'Kansas',
    stateCode: 'KS',
    city: 'Emporia',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Semi-guided and fully guided whitetail hunts in the Flint Hills tallgrass prairie with exceptional genetics.',
    phone: '(555) 785-1144',
    email: 'blake@flinthillswhitetail.example.com',
    website: 'https://flinthillswhitetail.example.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 89,
  },
  {
    id: 50,
    name: 'Jared Poole',
    businessName: 'Sunflower State Outfitters',
    state: 'Kansas',
    stateCode: 'KS',
    city: 'Salina',
    species: ['Whitetail', 'Mule Deer'],
    methods: ['Rifle', 'Bow'],
    experience: '14+ years',
    description: 'Central Kansas whitetail and western Kansas mule deer hunts on private CRP and agricultural land.',
    phone: '(555) 785-2277',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 55,
  },
  {
    id: 51,
    name: 'Tonya Wren',
    businessName: 'Big River Guide Service',
    state: 'Kansas',
    stateCode: 'KS',
    city: 'Atchison',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Crossbow'],
    experience: '10+ years',
    description: 'River-bottom whitetail hunts along the Missouri River with dense timber and heavy browse areas.',
    phone: '(555) 785-3300',
    email: 'tonya@bigriverguide.example.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 37,
  },

  // ============================================================
  // KENTUCKY (KY)
  // ============================================================
  {
    id: 52,
    name: 'Earl Sizemore',
    businessName: 'Bluegrass Trophy Outfitters',
    state: 'Kentucky',
    stateCode: 'KY',
    city: 'Bowling Green',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Crossbow'],
    experience: '22+ years',
    description: 'Premium guided whitetail hunts on managed farmland in western Kentucky with a strong record of 150-plus-inch bucks.',
    phone: '(555) 502-1155',
    email: 'earl@bluegrasstrophy.example.com',
    website: 'https://bluegrasstrophy.example.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 94,
  },
  {
    id: 53,
    name: 'Jenny Combs',
    businessName: 'Cumberland Gap Guides',
    state: 'Kentucky',
    stateCode: 'KY',
    city: 'Middlesboro',
    species: ['Whitetail', 'Bear', 'Turkey'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'Mountain whitetail and black bear hunts in the Appalachian foothills of eastern Kentucky with cabin lodging.',
    phone: '(555) 502-2288',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 43,
  },
  {
    id: 54,
    name: 'Donovan Wyatt',
    businessName: 'Green River Hunting Co.',
    state: 'Kentucky',
    stateCode: 'KY',
    city: 'Owensboro',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Crossbow', 'Muzzleloader'],
    experience: '12+ years',
    description: 'Western Kentucky river-bottom whitetail hunts with box blind and saddle hunting options on prime ag land.',
    phone: '(555) 502-3311',
    email: 'donovan@greenriverhunting.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 58,
  },

  // ============================================================
  // LOUISIANA (LA)
  // ============================================================
  {
    id: 55,
    name: 'Antoine Broussard',
    businessName: 'Bayou Country Outfitters',
    state: 'Louisiana',
    stateCode: 'LA',
    city: 'Lafayette',
    species: ['Whitetail', 'Hog', 'Waterfowl'],
    methods: ['Rifle', 'Bow', 'Shotgun'],
    experience: '20+ years',
    description: 'Guided whitetail and wild hog hunts in the Atchafalaya Basin with combination duck hunting packages available.',
    phone: '(555) 504-1166',
    email: 'antoine@bayoucountry.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 72,
  },
  {
    id: 56,
    name: 'Chelsea Arceneaux',
    businessName: 'Piney Woods Hunt Club',
    state: 'Louisiana',
    stateCode: 'LA',
    city: 'Ruston',
    species: ['Whitetail', 'Turkey', 'Hog'],
    methods: ['Rifle', 'Bow'],
    experience: '14+ years',
    description: 'North Louisiana whitetail hunts in the piney woods with food-plot-intensive management and quality genetics.',
    phone: '(555) 504-2299',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 46,
  },
  {
    id: 57,
    name: 'Marcus Hebert',
    businessName: 'Delta Marsh Outfitters',
    state: 'Louisiana',
    stateCode: 'LA',
    city: 'Monroe',
    species: ['Whitetail', 'Hog'],
    methods: ['Rifle', 'Crossbow'],
    experience: '10+ years',
    description: 'Affordable whitetail and hog hunts on delta farmland with heated shooting houses and all-day guide service.',
    phone: '(555) 504-3322',
    email: 'marcus@deltamarsh.example.com',
    priceRange: '$',
    buckStopPartner: false,
    rating: 4.3,
    reviewCount: 25,
  },

  // ============================================================
  // MAINE (ME)
  // ============================================================
  {
    id: 58,
    name: 'Hank Pelletier',
    businessName: 'North Woods Guide Service',
    state: 'Maine',
    stateCode: 'ME',
    city: 'Greenville',
    species: ['Whitetail', 'Moose', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '30+ years',
    description: 'Registered Maine Guide offering moose hunts in the Moosehead Lake region and whitetail hunts in the northern unorganized territories.',
    phone: '(555) 207-1177',
    email: 'hank@northwoodsguide.example.com',
    website: 'https://northwoodsguide.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.9,
    reviewCount: 108,
  },
  {
    id: 59,
    name: 'Claire Ouellette',
    businessName: 'Downeast Sporting Camps',
    state: 'Maine',
    stateCode: 'ME',
    city: 'Machias',
    species: ['Whitetail', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '18+ years',
    description: 'Traditional Maine sporting camp experience with guided whitetail and bear hunts in Washington County.',
    phone: '(555) 207-2200',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 54,
  },
  {
    id: 60,
    name: 'Dylan Thibodeau',
    businessName: 'Allagash Wilderness Hunts',
    state: 'Maine',
    stateCode: 'ME',
    city: 'Presque Isle',
    species: ['Moose', 'Bear', 'Whitetail'],
    methods: ['Rifle', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Aroostook County moose and bear hunts in remote timberland with canoe-access camps and experienced tracking dogs.',
    phone: '(555) 207-3333',
    email: 'dylan@allagashwilderness.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 67,
  },

  // ============================================================
  // MARYLAND (MD)
  // ============================================================
  {
    id: 61,
    name: 'Russell Whitfield',
    businessName: 'Chesapeake Hunting Guides',
    state: 'Maryland',
    stateCode: 'MD',
    city: 'Easton',
    species: ['Whitetail', 'Waterfowl', 'Turkey'],
    methods: ['Bow', 'Shotgun', 'Muzzleloader'],
    experience: '16+ years',
    description: 'Eastern Shore whitetail and waterfowl hunts on agricultural land with scenic Chesapeake Bay views.',
    phone: '(555) 410-1188',
    email: 'russell@chesapeakehunting.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 61,
  },
  {
    id: 62,
    name: 'Natasha Kelley',
    businessName: 'Western Maryland Mountain Hunts',
    state: 'Maryland',
    stateCode: 'MD',
    city: 'Cumberland',
    species: ['Whitetail', 'Bear', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '14+ years',
    description: 'Garrett and Allegany County whitetail and bear hunts in the Appalachian Mountains with mountain lodge lodging.',
    phone: '(555) 410-2211',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 38,
  },
  {
    id: 63,
    name: 'Derek Simmons',
    businessName: 'Tidewater Sportsmen',
    state: 'Maryland',
    stateCode: 'MD',
    city: 'Salisbury',
    species: ['Whitetail', 'Waterfowl'],
    methods: ['Shotgun', 'Bow'],
    experience: '10+ years',
    description: 'Lower Eastern Shore whitetail and waterfowl combination packages with lodging at a restored farmhouse.',
    phone: '(555) 410-3344',
    email: 'derek@tidewatersmen.example.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 29,
  },

  // ============================================================
  // MASSACHUSETTS (MA)
  // ============================================================
  {
    id: 64,
    name: 'Nathan Cromwell',
    businessName: 'Bay Colony Hunting Guides',
    state: 'Massachusetts',
    stateCode: 'MA',
    city: 'Worcester',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Shotgun', 'Muzzleloader'],
    experience: '12+ years',
    description: 'Central Massachusetts whitetail hunts on private woodlots and farms with a focus on archery season opportunities.',
    phone: '(555) 617-1199',
    email: 'nathan@baycolonyhunting.example.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 24,
  },
  {
    id: 65,
    name: 'Karen Standish',
    businessName: 'Berkshire Field Guides',
    state: 'Massachusetts',
    stateCode: 'MA',
    city: 'Pittsfield',
    species: ['Whitetail', 'Bear', 'Turkey'],
    methods: ['Bow', 'Shotgun'],
    experience: '15+ years',
    description: 'Guided hunts in the Berkshire Hills with access to private land tracts and state WMA borders.',
    phone: '(555) 617-2222',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 31,
  },
  {
    id: 66,
    name: 'Paul Thatcher',
    businessName: 'Pioneer Valley Outdoors',
    state: 'Massachusetts',
    stateCode: 'MA',
    city: 'Greenfield',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Muzzleloader'],
    experience: '8+ years',
    description: 'Connecticut River valley whitetail hunts with agricultural field setups and hardwood ridge stands.',
    phone: '(555) 617-3355',
    priceRange: '$',
    buckStopPartner: false,
    rating: 4.2,
    reviewCount: 15,
  },

  // ============================================================
  // MICHIGAN (MI) - Buck Stop's Home State - 5 Guides
  // ============================================================
  {
    id: 67,
    name: 'Jake Vandermeer',
    businessName: 'Northern Michigan Trophy Hunts',
    state: 'Michigan',
    stateCode: 'MI',
    city: 'Traverse City',
    species: ['Whitetail', 'Turkey', 'Bear'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '25+ years',
    description: 'Premier guided whitetail hunts in the trophy-rich counties of northwest Lower Michigan with lodge-style accommodations and all-inclusive packages.',
    phone: '(555) 231-1100',
    email: 'jake@northernmitrophy.example.com',
    website: 'https://northernmitrophy.example.com',
    priceRange: '$$$$',
    buckStopPartner: true,
    rating: 4.9,
    reviewCount: 142,
  },
  {
    id: 68,
    name: 'Sarah Koskinen',
    businessName: 'Upper Peninsula Wilderness Guides',
    state: 'Michigan',
    stateCode: 'MI',
    city: 'Marquette',
    species: ['Whitetail', 'Bear', 'Elk'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Remote UP whitetail and bear hunts on vast tracts of state and private forestland. One of few guides with access to Michigan elk country.',
    phone: '(555) 906-2233',
    email: 'sarah@upwilderness.example.com',
    website: 'https://upwilderness.example.com',
    priceRange: '$$$',
    buckStopPartner: true,
    rating: 4.8,
    reviewCount: 97,
  },
  {
    id: 69,
    name: 'Derek Millsap',
    businessName: 'Thumb Region Whitetails',
    state: 'Michigan',
    stateCode: 'MI',
    city: 'Bad Axe',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Crossbow', 'Shotgun'],
    experience: '15+ years',
    description: 'Michigan Thumb whitetail hunts on sugar beet and corn country with carefully managed food plots and mineral stations.',
    phone: '(555) 989-3366',
    email: 'derek@thumbwhitetails.example.com',
    priceRange: '$$',
    buckStopPartner: true,
    rating: 4.7,
    reviewCount: 73,
  },
  {
    id: 70,
    name: 'Bridget Novak',
    businessName: 'Great Lakes Sporting',
    state: 'Michigan',
    stateCode: 'MI',
    city: 'Cadillac',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Crossbow'],
    experience: '12+ years',
    description: 'Wexford and Missaukee County whitetail hunts with a blend of big-woods and agricultural edge habitat.',
    phone: '(555) 231-4499',
    email: 'bridget@greatlakessporting.example.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 48,
  },
  {
    id: 71,
    name: 'Tyler Crampton',
    businessName: 'Saginaw Bay Outfitters',
    state: 'Michigan',
    stateCode: 'MI',
    city: 'Bay City',
    species: ['Whitetail', 'Waterfowl', 'Turkey'],
    methods: ['Bow', 'Shotgun', 'Muzzleloader'],
    experience: '10+ years',
    description: 'Saginaw Valley whitetail and waterfowl hunts on prime agricultural flats with combination packages during November.',
    phone: '(555) 989-5522',
    email: 'tyler@saginawbayoutfitters.example.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 36,
  },

  // ============================================================
  // MINNESOTA (MN)
  // ============================================================
  {
    id: 72,
    name: 'Anders Lindstrom',
    businessName: 'Boundary Waters Outfitters',
    state: 'Minnesota',
    stateCode: 'MN',
    city: 'Ely',
    species: ['Whitetail', 'Bear', 'Moose'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '22+ years',
    description: 'Northern Minnesota whitetail and bear hunts in the boreal forest near the Boundary Waters with rustic cabin lodging.',
    phone: '(555) 218-1111',
    email: 'anders@boundarywaters.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 76,
  },
  {
    id: 73,
    name: 'Meghan Schultz',
    businessName: 'Prairie Pothole Hunts',
    state: 'Minnesota',
    stateCode: 'MN',
    city: 'Fergus Falls',
    species: ['Whitetail', 'Waterfowl', 'Turkey'],
    methods: ['Rifle', 'Shotgun', 'Bow'],
    experience: '14+ years',
    description: 'Western Minnesota whitetail hunts in the prairie pothole region with excellent combination waterfowl packages.',
    phone: '(555) 218-2244',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 42,
  },
  {
    id: 74,
    name: 'Troy Gustafson',
    businessName: 'Bluff Country Guide Service',
    state: 'Minnesota',
    stateCode: 'MN',
    city: 'Winona',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '18+ years',
    description: 'Southeast Minnesota bluff-country whitetail hunts on steep hardwood ridges and fertile valley floor food plots.',
    phone: '(555) 507-3377',
    email: 'troy@bluffcountryguide.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 68,
  },
  {
    id: 75,
    name: 'Lisa Halverson',
    businessName: 'North Star Hunting',
    state: 'Minnesota',
    stateCode: 'MN',
    city: 'Brainerd',
    species: ['Whitetail', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '10+ years',
    description: 'Central Minnesota whitetail and bear hunts in the lake country with comfortable resort-style lodging.',
    phone: '(555) 218-4400',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 31,
  },

  // ============================================================
  // MISSISSIPPI (MS)
  // ============================================================
  {
    id: 76,
    name: 'Vernon Childress',
    businessName: 'Delta Plantation Outfitters',
    state: 'Mississippi',
    stateCode: 'MS',
    city: 'Greenville',
    species: ['Whitetail', 'Turkey', 'Hog'],
    methods: ['Rifle', 'Bow', 'Crossbow'],
    experience: '25+ years',
    description: 'Mississippi Delta trophy whitetail hunts on managed plantation land with rich soil producing record-class bucks.',
    phone: '(555) 601-1122',
    email: 'vernon@deltaplanation.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 85,
  },
  {
    id: 77,
    name: 'Crystal Langford',
    businessName: 'Magnolia Ridge Hunts',
    state: 'Mississippi',
    stateCode: 'MS',
    city: 'Hattiesburg',
    species: ['Whitetail', 'Turkey', 'Hog'],
    methods: ['Rifle', 'Bow'],
    experience: '12+ years',
    description: 'Southern Mississippi whitetail hunts on longleaf pine and hardwood tracts with year-round hog hunting available.',
    phone: '(555) 601-2255',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 39,
  },
  {
    id: 78,
    name: 'Terrence Polk',
    businessName: 'Tombigbee Bottom Guides',
    state: 'Mississippi',
    stateCode: 'MS',
    city: 'Columbus',
    species: ['Whitetail', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '18+ years',
    description: 'East Mississippi whitetail hunts in the Tombigbee River bottoms with excellent trophy potential and turkey combo options.',
    phone: '(555) 601-3388',
    email: 'terrence@tombigbeeguides.example.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 52,
  },

  // ============================================================
  // MISSOURI (MO)
  // ============================================================
  {
    id: 79,
    name: 'Wade Callaway',
    businessName: 'Show-Me Trophy Outfitters',
    state: 'Missouri',
    stateCode: 'MO',
    city: 'Kirksville',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '20+ years',
    description: 'North Missouri trophy whitetail hunts on intensively managed farms in the golden triangle of big buck counties.',
    phone: '(555) 573-1133',
    email: 'wade@showmetrophy.example.com',
    website: 'https://showmetrophy.example.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.9,
    reviewCount: 99,
  },
  {
    id: 80,
    name: 'Paula Trent',
    businessName: 'Ozark Hollow Guides',
    state: 'Missouri',
    stateCode: 'MO',
    city: 'Springfield',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle'],
    experience: '14+ years',
    description: 'Ozark Mountain whitetail and turkey hunts in the rolling cedar and oak hills of southern Missouri.',
    phone: '(555) 573-2266',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 44,
  },
  {
    id: 81,
    name: 'Ricky Blevins',
    businessName: 'Big Muddy Outfitters',
    state: 'Missouri',
    stateCode: 'MO',
    city: 'Columbia',
    species: ['Whitetail', 'Turkey', 'Hog'],
    methods: ['Rifle', 'Bow', 'Crossbow'],
    experience: '15+ years',
    description: 'Central Missouri river-bottom whitetail hunts with standing corn and soybean field setups along the Missouri River.',
    phone: '(555) 573-3399',
    email: 'ricky@bigmuddy.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 56,
  },

  // ============================================================
  // MONTANA (MT)
  // ============================================================
  {
    id: 82,
    name: 'Wyatt Hargrove',
    businessName: 'Beartooth Outfitters',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Red Lodge',
    species: ['Elk', 'Mule Deer', 'Whitetail'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '30+ years',
    description: 'Guided horseback elk hunts in the Absaroka-Beartooth Wilderness with drop camps and full-service outfitting.',
    phone: '(555) 406-1155',
    email: 'wyatt@beartoothoutfitters.example.com',
    website: 'https://beartoothoutfitters.example.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 5.0,
    reviewCount: 138,
  },
  {
    id: 83,
    name: 'Cassie Drummond',
    businessName: 'Missouri Breaks Hunting',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Lewistown',
    species: ['Mule Deer', 'Elk', 'Predator'],
    methods: ['Rifle', 'Bow'],
    experience: '18+ years',
    description: 'Spot-and-stalk mule deer hunts in the rugged Missouri Breaks badlands with consistently heavy-antlered bucks.',
    phone: '(555) 406-2288',
    email: 'cassie@mobreaks.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 82,
  },
  {
    id: 84,
    name: 'Nate Johannsen',
    businessName: 'Big Sky Prairie Outfitters',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Glasgow',
    species: ['Mule Deer', 'Whitetail', 'Predator'],
    methods: ['Rifle', 'Bow'],
    experience: '14+ years',
    description: 'Eastern Montana mule deer and whitetail hunts on vast prairie ranches with excellent antelope combo options.',
    phone: '(555) 406-3311',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 47,
  },
  {
    id: 85,
    name: 'Kendra Blackwood',
    businessName: 'Flathead Valley Guides',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Kalispell',
    species: ['Elk', 'Whitetail', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '22+ years',
    description: 'Northwest Montana elk and whitetail hunts in the Swan and Flathead valleys with spectacular mountain scenery and abundant wildlife.',
    phone: '(555) 406-4444',
    email: 'kendra@flatheadguides.example.com',
    website: 'https://flatheadguides.example.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 71,
  },
];
