// SCRAPED DATA: Real hunting guide/outfitter listings sourced from
// HuntingLocator.com, Hunting Guide Directory, Guidefitter, HuntGuide.com,
// HuntingTop10.com, and individual outfitter websites. Scraped 2026-03-29.
//
// Sources attempted:
//   - huntinglocator.com (Cloudflare-blocked; partial data from search index)
//   - huntingguidedirectory.com (GoDaddy WAF-blocked; partial data from search index)
//   - huntingtripsrus.com (415 error)
//   - huntingguidesandoutfitters.net (JS-rendered; no listing data in HTML)
//   - guidefitter.com, huntguide.com, ultimatedeerhunting.com (search index)
//   - huntingtop10.com (JS-rendered; data from search index + outfitter profiles)
//   - Individual outfitter websites (direct search results)

import type { HuntingGuide } from './guides';

export type ScrapedGuide = Omit<HuntingGuide, 'verified' | 'source'>;

export const scrapedGuides: ScrapedGuide[] = [
  // ============================================================
  // MICHIGAN (MI) -- Real outfitters
  // ============================================================
  {
    id: 5001,
    name: 'Hotshot Outfitters',
    businessName: 'Hotshot Outfitters',
    state: 'Michigan',
    stateCode: 'MI',
    city: 'Cass City',
    species: ['Whitetail', 'Turkey', 'Waterfowl'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Shotgun'],
    experience: '20+ years',
    description: 'Over 20 years experience guiding whitetail deer and other game in Michigan\'s Thumb region. Offers archery, firearm, and muzzleloader hunts on private land.',
    phone: '(989) 670-4336',
    website: 'https://hotshotoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5002,
    name: 'Cherry Creek Farm',
    businessName: 'Cherry Creek Farm',
    state: 'Michigan',
    stateCode: 'MI',
    city: 'Mio',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Shotgun'],
    experience: '15+ years',
    description: 'Located on 500+ acres of scenic Michigan land near Mio. Offers guided trophy whitetail deer hunting, turkey hunting, pheasant hunting, and trout fishing packages.',
    email: 'cherrycreekfarm@aol.com',
    website: 'https://www.cherrycreekfarm.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5003,
    name: 'Arrowhead Whitetail Lodge',
    businessName: 'Arrowhead Whitetail Lodge',
    state: 'Michigan',
    stateCode: 'MI',
    city: 'Hesperia',
    species: ['Whitetail'],
    methods: ['Bow', 'Crossbow'],
    experience: '10+ years',
    description: 'Guided whitetail archery hunting ranch in Northern Michigan on almost 500 acres. Located in Western Michigan close to Grand Rapids regional airport. Specializes in bow-only trophy whitetail hunts.',
    website: 'https://www.arrowheadwhitetails.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5004,
    name: 'Greenwoods Outfitting',
    businessName: 'Greenwoods Outfitting',
    state: 'Michigan',
    stateCode: 'MI',
    city: 'Menominee',
    species: ['Whitetail', 'Bear', 'Turkey', 'Waterfowl'],
    methods: ['Bow', 'Rifle', 'Shotgun', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Family owned and operated in Menominee County, Upper Peninsula of Michigan. The area is known for high concentrations of whitetail deer, black bear, turkey, pheasant, and waterfowl.',
    website: 'https://greenwoodsoutfitting.com',
    priceRange: '$$',
    buckStopPartner: false,
  },
  {
    id: 5005,
    name: 'The Dog Outfitter',
    businessName: 'The Dog Outfitter',
    state: 'Michigan',
    stateCode: 'MI',
    city: 'Gaylord',
    species: ['Elk', 'Whitetail', 'Bear', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Specializes in whitetail deer hunting across 80,000 pristine northern Michigan acres. Strategic stand positioning for trophy buck opportunities. Also offers elk, bear, and turkey hunts.',
    website: 'https://www.dogoutfitting.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },

  // ============================================================
  // TEXAS (TX) -- Real outfitters
  // ============================================================
  {
    id: 5010,
    name: 'All Seasons Guide Service',
    businessName: 'All Seasons Guide Service',
    state: 'Texas',
    stateCode: 'TX',
    city: 'Carrizo Springs',
    species: ['Whitetail', 'Mule Deer', 'Elk', 'Hog'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '25+ years',
    description: 'South Texas hunting outfitter specializing in free range, fair chase hunts for whitetail deer, mule deer, and West Texas elk. One of the most experienced guide services in the region.',
    phone: '(361) 920-2825',
    website: 'https://allseasonsguideservice.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5011,
    name: 'RecordBuck Ranch',
    businessName: 'RecordBuck Ranch',
    state: 'Texas',
    stateCode: 'TX',
    city: 'Utopia',
    species: ['Whitetail', 'Elk', 'Hog', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Muzzleloader', 'Crossbow'],
    experience: '30+ years',
    description: 'Premier year-round hunting destination on 20,000+ contiguous acres about an hour west of San Antonio. Offers 55 different species from around the world including trophy whitetail, elk, red stag, axis deer. Trophy fee pricing structure.',
    website: 'https://www.recordbuck.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5012,
    name: 'Texas Thermal Outfitters',
    businessName: 'Texas Thermal Outfitters',
    state: 'Texas',
    stateCode: 'TX',
    city: 'Graham',
    species: ['Hog', 'Whitetail', 'Predator'],
    methods: ['Rifle'],
    experience: '10+ years',
    description: 'Located in Graham, Texas. Offers hog, deer, red stag, aoudad, and axis deer hunts. Thermal optic night hunts available for hogs and predators.',
    phone: '(940) 456-1849',
    email: 'texasthermaloutfitters@gmail.com',
    website: 'https://texasthermaloutfitters.com',
    priceRange: '$$',
    buckStopPartner: false,
  },
  {
    id: 5013,
    name: 'Panhandle Outfitters of Texas',
    businessName: 'Panhandle Outfitters of Texas',
    state: 'Texas',
    stateCode: 'TX',
    city: 'Amarillo',
    species: ['Mule Deer', 'Whitetail', 'Antelope'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Texas Panhandle hunting outfitter offering guided mule deer, whitetail, and pronghorn antelope hunts on private ranches in the Texas Panhandle region.',
    phone: '(806) 228-3114',
    website: 'https://texaspanhandlehunts.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5014,
    name: 'Double Diamond Outfitters',
    businessName: 'Double Diamond Outfitters',
    state: 'Texas',
    stateCode: 'TX',
    city: 'San Angelo',
    species: ['Whitetail', 'Hog', 'Antelope'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'Owned and operated by Wes Mundy since 2005. Offers trophy and flat rate hunts with fair and transparent pricing. Whitetail, aoudad, axis deer, hogs, and many exotic species on Texas ranch land.',
    website: 'https://www.huntdoublediamond.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5015,
    name: 'Wildlife Systems Inc.',
    businessName: 'Wildlife Systems Inc.',
    state: 'Texas',
    stateCode: 'TX',
    city: 'San Antonio',
    species: ['Whitetail', 'Mule Deer', 'Turkey', 'Elk'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '35+ years',
    description: 'Established in 1987 by Greg Simons. Leading provider of quality hunting and wildlife management on over 1,000,000 acres of private land across Texas and New Mexico. Manages both high-fenced and free-ranging whitetail programs on 100,000 acres.',
    website: 'https://www.wildlifesystems.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5016,
    name: 'Rush Creek Guide Service',
    businessName: 'Rush Creek Guide Service',
    state: 'Texas',
    stateCode: 'TX',
    city: 'Canadian',
    species: ['Mule Deer', 'Whitetail', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Shotgun'],
    experience: '15+ years',
    description: 'Midwest hunting guides for mule deer, turkey, and more in the Texas Panhandle and surrounding region. Offers guided hunts on private ranch land.',
    phone: '(806) 323-3030',
    website: 'https://rushcreekguideservices.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5017,
    name: 'West Texas Hunt Organization',
    businessName: 'West Texas Hunt Organization',
    state: 'Texas',
    stateCode: 'TX',
    city: 'El Paso',
    species: ['Mule Deer', 'Antelope', 'Hog', 'Predator'],
    methods: ['Rifle', 'Bow'],
    experience: '10+ years',
    description: 'West Texas hunting organization offering guided hunts on private and public land in the Trans-Pecos region. Mule deer, antelope, and predator hunts available.',
    email: 'elpasohunter@gmail.com',
    website: 'https://www.westtexashunt.com',
    priceRange: '$$',
    buckStopPartner: false,
  },

  // ============================================================
  // COLORADO (CO) -- Real outfitters
  // ============================================================
  {
    id: 5020,
    name: 'Action Adventures Guide Outfitter',
    businessName: 'Action Adventures Guide Outfitter LLC',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Montrose',
    species: ['Elk', 'Mule Deer', 'Bear', 'Antelope'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Montrose-based outfitter offering guided elk, mule deer, bear, and antelope hunts in Western Colorado. Experienced guides with extensive knowledge of local game units.',
    phone: '(800) 383-1888',
    website: 'https://actionadventures.net',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5021,
    name: 'Kiowa Creek Outfitters',
    businessName: 'Kiowa Creek Outfitters',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Elbert',
    species: ['Whitetail', 'Mule Deer', 'Elk', 'Antelope'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Eastern Colorado Plains hunting outfitter offering whitetail and mule deer hunts on private lands. Also provides elk and antelope hunts in premier game units.',
    phone: '(303) 648-3273',
    website: 'https://kiowacreekoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5022,
    name: 'Rocky Mountain Ranches',
    businessName: 'Rocky Mountain Ranches Ltd.',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Steamboat Springs',
    species: ['Elk', 'Mule Deer', 'Antelope'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '25+ years',
    description: 'Specializes in Colorado elk, mule deer, and pronghorn antelope hunting on private ranches. Guided horseback and vehicle-based hunts with high success rates.',
    phone: '(970) 439-1894',
    website: 'https://www.rockymountainhunting.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5023,
    name: 'Gunnison Country Outfitters',
    businessName: 'Gunnison Country Outfitters',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Gunnison',
    species: ['Elk', 'Mule Deer'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Specializes in horseback guided trips in the Fossil Ridge Wilderness and GMU 55. High country elk and mule deer hunts in the Gunnison area. Also offers fishing and horseback riding.',
    phone: '(970) 901-1222',
    website: 'https://gunnisoncountryoutfitters.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5024,
    name: 'Rocky Mountain Outfitters of Colorado',
    businessName: 'Rocky Mountain Outfitters of Colorado',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Colorado Springs',
    species: ['Elk', 'Mule Deer'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Premier outfitter for Colorado elk and mule deer hunts. Hunts conducted in the National Forest with access to around 600,000 acres of hunting area.',
    website: 'https://rmooc.net',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5025,
    name: 'Western Colorado Outfitters',
    businessName: 'Western Colorado Outfitters',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Delta',
    species: ['Elk', 'Mule Deer', 'Bear', 'Predator'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '45+ years',
    description: 'Providing quality archery, muzzleloader, and rifle hunts in Colorado since 1976. Hunts elk, mule deer, mountain lion, cougar, and black bear in GMU 62 on Grand Mesa, Uncompahgre, and Gunnison National Forest.',
    website: 'https://westerncoloradooutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5026,
    name: 'Reverse 7 L Outfitters',
    businessName: 'Reverse 7 L Outfitters',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Saguache',
    species: ['Elk', 'Mule Deer', 'Bear', 'Turkey', 'Antelope'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '30+ years',
    description: 'Family owned outfitter with over 30 years experience. Unit 22 hunts on 25,000 private acres for elk, mule deer, bear, antelope, and turkey. Hunts by vehicle, horseback, and foot.',
    website: 'https://reverse7l.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5027,
    name: 'AEI Outfitter',
    businessName: 'AEI Outfitter',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Gunnison',
    species: ['Elk', 'Mule Deer'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '35+ years',
    description: 'Colorado-based elk and fishing outfitter operating since 1984. Guided big game hunts in the Gunnison area with decades of local knowledge.',
    website: 'https://huntinglocator.com/businesses/detail/aei-outfitter',
    priceRange: '$$$',
    buckStopPartner: false,
  },

  // ============================================================
  // MONTANA (MT) -- Real outfitters
  // ============================================================
  {
    id: 5030,
    name: 'Wemples Wildlife Outfitter',
    businessName: 'Wemples Wildlife Outfitter',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Helena',
    species: ['Elk', 'Antelope', 'Mule Deer', 'Moose'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '40+ years',
    description: 'Established in 1983, Montana outfitter license 163. Offers hunts for bull elk, antelope, mule deer, moose, bighorn sheep, and cow elk across Montana\'s prime hunting areas.',
    phone: '(406) 239-1752',
    website: 'https://www.montana-hunting-outfitter.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5031,
    name: 'Redbone Outfitting',
    businessName: 'Redbone Outfitting',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Miles City',
    species: ['Mule Deer', 'Elk', 'Antelope', 'Predator'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'Offers trophy mule deer, elk, antelope, mountain lion, and prairie dog hunts in Eastern Montana. Experienced guides with knowledge of the region\'s diverse terrain.',
    phone: '(406) 370-5419',
    website: 'https://redboneoutfitting.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5032,
    name: 'Montana Guide Service',
    businessName: 'Montana Guide Service',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Gardiner',
    species: ['Elk', 'Mule Deer', 'Whitetail', 'Bear', 'Antelope'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '30+ years',
    description: 'Located at 80 Mol Heron Creek Road, Gardiner, MT 59030. Montana\'s finest trophy elk hunting adjoining Yellowstone National Park. Also guides mule deer, whitetail, black bear, and antelope hunts throughout Montana.',
    phone: '(406) 848-7265',
    website: 'https://www.montanaguide.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5033,
    name: 'Eastern Montana Outfitters',
    businessName: 'Eastern Montana Outfitters',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Glasgow',
    species: ['Mule Deer', 'Antelope', 'Whitetail'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Montana Outfitter License #11502. Specializes in deer and antelope hunting in the vast open prairies of Eastern Montana. Private land access with high success rates.',
    phone: '(406) 941-2419',
    website: 'https://easternmontanaoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5034,
    name: 'Montana Trophy Outfitters',
    businessName: 'Montana Trophy Outfitters',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Great Falls',
    species: ['Whitetail', 'Elk', 'Antelope'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'Offers whitetail deer, cow elk, antelope, and other big game hunts across Montana\'s prime hunting districts. Knowledgeable guides with high success rates.',
    phone: '(406) 498-5608',
    website: 'https://mttrophy.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5035,
    name: 'J&J Guide Service',
    businessName: 'J&J Guide Service',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Ekalaka',
    species: ['Elk', 'Mule Deer', 'Whitetail', 'Antelope'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'Specializes in rifle and archery hunts for Rocky Mountain elk, mule deer, whitetail deer, and pronghorn antelope. Operates from locations in Ekalaka, Martinsdale, and Hamilton, MT.',
    website: 'https://www.jjguide.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5036,
    name: 'Landwehr Outfitters',
    businessName: 'Landwehr Outfitters',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Glasgow',
    species: ['Mule Deer', 'Antelope', 'Elk', 'Waterfowl'],
    methods: ['Rifle', 'Bow', 'Shotgun'],
    experience: '30+ years',
    description: 'Guides archery and rifle hunts in the Missouri Breaks area with 30+ years of experience. Access remote hunting areas by boat on Ft Peck Reservoir.',
    website: 'https://landwehroutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5037,
    name: 'Elk Creek Outfitting',
    businessName: 'Elk Creek Outfitting',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Trout Creek',
    species: ['Elk', 'Mule Deer', 'Whitetail', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '30+ years',
    description: 'Family outfitting business for more than 30 years in Northwestern Montana, approximately 2.5 hours from Missoula. Vast private land and National Forest access producing trophy class animals year after year.',
    website: 'https://elkcreekoutfitting.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5038,
    name: 'Harris Hunts Montana',
    businessName: 'Harris Hunts Montana',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Lewistown',
    species: ['Whitetail', 'Mule Deer', 'Elk', 'Antelope'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'Premier Montana hunting outfitter with knowledgeable guides and high success rates. Offers whitetail deer, mule deer, elk, and antelope hunts.',
    website: 'https://harrishunts.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5039,
    name: 'Montana Big Game Outfitters',
    businessName: 'Montana Big Game Outfitters',
    state: 'Montana',
    stateCode: 'MT',
    city: 'White Sulphur Springs',
    species: ['Elk', 'Mule Deer', 'Whitetail', 'Antelope', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'One of Montana\'s premier outfitters for mule deer, whitetail deer, elk, antelope, and black bear. Takes a limited number of elk hunters each year at their elk camp near White Sulphur Springs.',
    website: 'https://www.montanabiggameoutfitters.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },

  // ============================================================
  // WISCONSIN (WI) -- Real outfitters
  // ============================================================
  {
    id: 5040,
    name: 'JW Outfitters',
    businessName: 'JW Outfitters',
    state: 'Wisconsin',
    stateCode: 'WI',
    city: 'Plainfield',
    species: ['Whitetail', 'Turkey', 'Bear'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Shotgun'],
    experience: '15+ years',
    description: 'Top fair chase outfitter in Central Wisconsin where trophy bucks thrive, wild turkeys are abundant, and black bears roam. Also provides land management services and food plot consulting.',
    website: 'https://www.jwoutfitter.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5041,
    name: 'Clam Lake Guide and Taxidermy',
    businessName: 'Clam Lake Guide and Taxidermy',
    state: 'Wisconsin',
    stateCode: 'WI',
    city: 'Clam Lake',
    species: ['Bear', 'Whitetail', 'Elk'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Shotgun'],
    experience: '35+ years',
    description: 'Full time, licensed, insured guide service with 35+ years of experience in the Chequamegon-Nicolet National Forest. Guided hunts for black bear (Zone A) with bait or dogs, upland birds, whitetail deer, elk, coyote, and bobcat.',
    website: 'https://www.clamlakeguideandtaxidermy.com',
    priceRange: '$$',
    buckStopPartner: false,
  },
  {
    id: 5042,
    name: 'Rutting Ridge Outfitters',
    businessName: 'Rutting Ridge Outfitters',
    state: 'Wisconsin',
    stateCode: 'WI',
    city: 'Alma',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '10+ years',
    description: 'Located in Buffalo County along the Mississippi River and Lake Pepin. Offers archery, rifle, and muzzleloader hunts for trophy Wisconsin whitetails in one of the top whitetail counties in the nation.',
    phone: '(715) 495-0534',
    website: 'https://www.ruttingridgeoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5043,
    name: 'Forest of Antlers Outfitters',
    businessName: 'Forest of Antlers Outfitters',
    state: 'Wisconsin',
    stateCode: 'WI',
    city: 'Minocqua',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Crossbow'],
    experience: '10+ years',
    description: 'Located on over 950 acres in Minocqua. Offers guided and unguided whitetail hunts from September 15 through December 31. Trophy whitetail management program.',
    website: 'https://forestofantlershunt.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5044,
    name: 'Extreme Driftless LLC',
    businessName: 'Extreme Driftless LLC',
    state: 'Wisconsin',
    stateCode: 'WI',
    city: 'Cashton',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Shotgun'],
    experience: '10+ years',
    description: 'Located 5 miles outside of Cashton, WI in the Driftless region. Offers guided hunting services for archery, shotgun, rifle, and muzzleloader hunts with private on-property lodging.',
    website: 'https://www.extremedriftless.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5045,
    name: 'Big E Outfitters',
    businessName: 'Big E Outfitters',
    state: 'Wisconsin',
    stateCode: 'WI',
    city: 'Waupaca',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Crossbow', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Family and veteran owned company with a home base whitetail ranch in Central Wisconsin. ONE PRICE trophy hunt with no hidden costs. 3 days/4 nights with all meals, lodging and tags included. Trophy bucks over 180 inches. VIP preserve option with bucks over 300 inches.',
    website: 'https://wisconsinwhitetailhunts.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5046,
    name: 'Turtle Creek Outfitters',
    businessName: 'Turtle Creek Outfitters',
    state: 'Wisconsin',
    stateCode: 'WI',
    city: 'Prairie Farm',
    species: ['Whitetail'],
    methods: ['Bow', 'Crossbow'],
    experience: '15+ years',
    description: 'High quality, low pressure hunts for trophy Wisconsin whitetail deer. Custom archery hunts starting at $3,500 per hunter. Also offers brook trout fishing.',
    email: 'TrophyBucks@me.com',
    website: 'https://www.turtlecreekoutfitters.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5047,
    name: 'Bluff Bucks Outfitters',
    businessName: 'Bluff Bucks Outfitters',
    state: 'Wisconsin',
    stateCode: 'WI',
    city: 'Fountain City',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '10+ years',
    description: 'Buffalo County, Wisconsin home to world class trophy whitetail deer hunts. Guided hunts in one of the most renowned whitetail deer areas in the Midwest.',
    website: 'https://bluffbucks.net',
    priceRange: '$$$',
    buckStopPartner: false,
  },

  // ============================================================
  // IOWA (IA) -- Real outfitters
  // ============================================================
  {
    id: 5050,
    name: 'BBD Outfitters',
    businessName: 'BBD Outfitters',
    state: 'Iowa',
    stateCode: 'IA',
    city: 'Stockport',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '15+ years',
    description: 'World class whitetail hunts in Iowa. Located in Stockport, Iowa offering premium guided deer hunts on private land.',
    phone: '(641) 919-7845',
    email: 'corbin@bbdoutfitters.com',
    website: 'https://bbdoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5051,
    name: 'Wonderlich Outdoors',
    businessName: 'Wonderlich Outdoors',
    state: 'Iowa',
    stateCode: 'IA',
    city: 'Pleasant Hill',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Shotgun', 'Muzzleloader'],
    experience: '10+ years',
    description: 'Central Iowa hunting and fishing outfitter located at 7035 NE Rising Sun Drive, Pleasant Hill, IA 50327. Offers guided whitetail deer hunts on private Iowa farmland.',
    phone: '(515) 897-9677',
    email: 'info@wonderlichoutdoors.com',
    website: 'https://www.wonderlichoutdoors.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5052,
    name: 'Wicked Whitetail Outdoors',
    businessName: 'Wicked Whitetail Outdoors',
    state: 'Iowa',
    stateCode: 'IA',
    city: 'Centerville',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Excellent deer hunting on 5,000+ private and leased acres with a 140-inch minimum and NO trophy fees. Premier Iowa whitetail hunting destination.',
    website: 'https://wickedwhitetailoutdoors.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5053,
    name: 'Iowa Whitetail Outfitters',
    businessName: 'Iowa Whitetail Outfitters',
    state: 'Iowa',
    stateCode: 'IA',
    city: 'Des Moines',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Shotgun'],
    experience: '20+ years',
    description: 'A family of hunters offering whitetail hunting adventures in Iowa since 2003. Known for consistent trophy buck harvests on managed private land.',
    website: 'https://www.iowawhitetailoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5054,
    name: 'Iowa Trophy Hunts',
    businessName: 'Iowa Trophy Hunts',
    state: 'Iowa',
    stateCode: 'IA',
    city: 'Ottumwa',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Owned and operated by Nathan Askew, a full-time professional hunter and outfitter. In business since 2005, offering guided trophy whitetail hunts in southeastern Iowa.',
    website: 'https://iowatrophyhunts.net',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5055,
    name: 'Shermoe Adventures',
    businessName: 'Shermoe Adventures',
    state: 'Iowa',
    stateCode: 'IA',
    city: 'Albia',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Shotgun'],
    experience: '20+ years',
    description: 'Top Iowa deer hunting outfitter offering guided whitetail hunts on premium private land. Known for consistently producing trophy class whitetail bucks.',
    phone: '(800) 367-1188',
    website: 'https://www.shermoeadventures.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5056,
    name: 'MDL Outfitters',
    businessName: 'MDL Outfitters',
    state: 'Iowa',
    stateCode: 'IA',
    city: 'Corydon',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '10+ years',
    description: 'Offers hybrid DIY + semi-guided whitetail deer hunts in Southern Iowa\'s Zone 5 and Zone 6. Provides access to quality private land with flexible hunting packages.',
    website: 'https://www.huntiowawhitetails.com',
    priceRange: '$$',
    buckStopPartner: false,
  },
  {
    id: 5057,
    name: 'J&S Trophy Hunts',
    businessName: 'J&S Trophy Hunts',
    state: 'Iowa',
    stateCode: 'IA',
    city: 'Centerville',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Shotgun'],
    experience: '15+ years',
    description: 'Operates on 5,000 acres in Appanoose County and Monroe County, Iowa. Guided whitetail hunts in prime southern Iowa deer country.',
    website: 'https://www.jstrophyhunts.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },

  // ============================================================
  // KANSAS (KS) -- Real outfitters
  // ============================================================
  {
    id: 5060,
    name: 'NCK Outfitters',
    businessName: 'North Central Kansas Outfitters',
    state: 'Kansas',
    stateCode: 'KS',
    city: 'Clay Center',
    species: ['Whitetail', 'Turkey', 'Waterfowl'],
    methods: ['Bow', 'Rifle', 'Shotgun', 'Muzzleloader'],
    experience: '15+ years',
    description: '5.0-star rated outfitter offering pheasant, whitetail, and turkey hunting in Clay Center, Kansas. Exceptional reputation and experienced guides.',
    phone: '(785) 452-5220',
    website: 'https://www.nckhunt.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 5.0,
  },
  {
    id: 5061,
    name: 'Beamers Guide Service',
    businessName: 'Beamers Guide Service',
    state: 'Kansas',
    stateCode: 'KS',
    city: 'Salina',
    species: ['Whitetail', 'Mule Deer', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Kansas whitetail deer and turkey hunting outfitter operating over twenty miles of creek habitat providing excellent whitetail deer habitat.',
    phone: '(303) 919-3899',
    website: 'https://www.beamersguideservice.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5062,
    name: 'Hunt Hickory Creek',
    businessName: 'Hunt Hickory Creek',
    state: 'Kansas',
    stateCode: 'KS',
    city: 'Chanute',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Shotgun'],
    experience: '25+ years',
    description: 'Kansas outfitter since 1996 in Southeast Kansas offering trophy whitetail deer hunting. Leases multiple ranches ranging from 400 to 7,700 acres.',
    website: 'https://www.hunthickorycreek.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5063,
    name: 'Pipe Creek Guiding Service',
    businessName: 'Pipe Creek Guiding Service',
    state: 'Kansas',
    stateCode: 'KS',
    city: 'Minneapolis',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Shotgun'],
    experience: '15+ years',
    description: 'Trophy whitetail deer and turkey hunting on 15,000 exclusive acres in the Minneapolis, Kansas area. Guided hunts with experienced local guides.',
    phone: '(785) 392-7441',
    website: 'https://www.pipecreekhunts.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5064,
    name: 'CK Outfitters',
    businessName: 'CK Outfitters',
    state: 'Kansas',
    stateCode: 'KS',
    city: 'Unionville',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Shotgun'],
    experience: '15+ years',
    description: 'Exceptional Kansas whitetail deer and turkey hunting outfitter. Guided hunts on private land with trophy management programs.',
    phone: '(660) 676-3471',
    website: 'https://www.ckoutfitters.net',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5065,
    name: 'Busters Outfitters',
    businessName: 'Busters Outfitters',
    state: 'Kansas',
    stateCode: 'KS',
    city: 'Bucklin',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Shotgun'],
    experience: '15+ years',
    description: 'Offers whitetail deer and turkey hunting in southwestern Kansas. Guided hunts on private ranch and farmland.',
    phone: '(620) 546-5777',
    website: 'https://www.bustersoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5066,
    name: 'Caney Creek Outfitters',
    businessName: 'Caney Creek Outfitters',
    state: 'Kansas',
    stateCode: 'KS',
    city: 'Sedan',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Trophy whitetail deer hunting in the Flint Hills of Southeastern Kansas. Also offers Eastern and Rio Grande turkey hunting and shed antler searching on nearly 30,000 acres of private ranch and farmland.',
    website: 'https://huntinginkansas.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5067,
    name: 'Dirt Road Outfitters',
    businessName: 'Dirt Road Outfitters',
    state: 'Kansas',
    stateCode: 'KS',
    city: 'Kingman',
    species: ['Whitetail', 'Turkey', 'Waterfowl'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Crossbow', 'Shotgun'],
    experience: '10+ years',
    description: 'South Central Kansas outfitter offering trophy whitetail and Rio Grande turkey hunts on over 10,000 privately managed acres. Also offers pheasant and quail hunts. 140 class minimum for whitetail harvests.',
    website: 'https://www.dirtroadoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5068,
    name: 'Kansas Trophy Whitetails',
    businessName: 'Kansas Trophy Whitetails',
    state: 'Kansas',
    stateCode: 'KS',
    city: 'Lyndon',
    species: ['Whitetail', 'Turkey', 'Elk', 'Predator'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Shotgun'],
    experience: '15+ years',
    description: 'Guided high-fence hunts on roughly 400 acres in Lyndon, Kansas. Offers bow and rifle hunts for trophy whitetail, seven types of ram, elk, bison, water buffalo, ibex, and other exotic animals.',
    website: 'https://www.kansastrophywhitetails.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },

  // ============================================================
  // OHIO (OH) -- Real outfitters
  // ============================================================
  {
    id: 5070,
    name: 'Ohio Guide Outfitters',
    businessName: 'Ohio Guide Outfitters',
    state: 'Ohio',
    stateCode: 'OH',
    city: 'Bellville',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Crossbow', 'Shotgun'],
    experience: '15+ years',
    description: 'Full service Ohio hunting outfitter in Bellville offering guided whitetail deer and turkey hunts on private land. Comprehensive packages with lodging.',
    phone: '(419) 886-2107',
    website: 'https://www.ohioguideoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5071,
    name: 'Rut Chasers',
    businessName: 'Rut Chasers',
    state: 'Ohio',
    stateCode: 'OH',
    city: 'Loudonville',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Crossbow'],
    experience: '10+ years',
    description: 'Trophy whitetail deer hunting and turkey hunting outfitter in Ohio. Fair chase guided hunts on managed private land.',
    phone: '(419) 543-3433',
    website: 'https://www.ohiorutchasers.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5072,
    name: 'JC Outfitters of Ohio',
    businessName: 'JC Outfitters of Ohio LLC',
    state: 'Ohio',
    stateCode: 'OH',
    city: 'Carrollton',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Crossbow'],
    experience: '15+ years',
    description: 'Guided whitetail deer and turkey hunts in eastern Ohio. Managed private land with experienced local guides.',
    phone: '(330) 382-2059',
    website: 'https://jcoutfittersofohio.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5073,
    name: 'Xtreme World Class Whitetails of Ohio',
    businessName: 'Xtreme World Class Whitetails of Ohio',
    state: 'Ohio',
    stateCode: 'OH',
    city: 'Millersburg',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Crossbow'],
    experience: '10+ years',
    description: 'Guided whitetail deer hunting outfitter in Ohio\'s Amish Country. Trophy whitetail hunts on managed private land.',
    phone: '(330) 237-9960',
    website: 'https://xtreme-wcwo.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5074,
    name: 'Ohio Whitetail Ridge Outfitters',
    businessName: 'Ohio Whitetail Ridge Outfitters',
    state: 'Ohio',
    stateCode: 'OH',
    city: 'Zanesville',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Crossbow'],
    experience: '10+ years',
    description: 'Hunting outfitter and lodge operating on 740 acres of managed private land. Trophy whitetail deer hunts with lodging accommodations.',
    website: 'https://www.ohiowhitetailridgeoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5075,
    name: 'Whitetail Outfitters of Ohio',
    businessName: 'Whitetail Outfitters of Ohio',
    state: 'Ohio',
    stateCode: 'OH',
    city: 'Coshocton',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Crossbow'],
    experience: '20+ years',
    description: 'Successful trophy whitetail operation in the Midwest operating for over 20 years. Guided hunts in Coshocton County, one of Ohio\'s top whitetail counties.',
    website: 'https://www.whitetailoutfittersofohio.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5076,
    name: 'Brushy Fork Outfitters',
    businessName: 'Brushy Fork Outfitters LTD',
    state: 'Ohio',
    stateCode: 'OH',
    city: 'Nashport',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Crossbow', 'Shotgun'],
    experience: '15+ years',
    description: 'Ohio\'s premier hunting outfitter managing thousands of acres of privately owned ground in Licking, Knox, Coshocton, and Muskingum Counties. Fair-chase, fully guided whitetail deer and turkey hunts.',
    website: 'https://brushyforkoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5077,
    name: 'Sugar Creek Outfitters',
    businessName: 'Sugar Creek Outfitters LLC',
    state: 'Ohio',
    stateCode: 'OH',
    city: 'Wooster',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Crossbow'],
    experience: '10+ years',
    description: 'Hunting lodge for giant whitetail deer hunts in North Central Ohio. 100% fair chase big buck hunts with lodge accommodations.',
    website: 'https://www.sugarcreekoutfittersllc.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5078,
    name: 'Coshocton County Outfitters',
    businessName: 'Coshocton County Outfitters',
    state: 'Ohio',
    stateCode: 'OH',
    city: 'Coshocton',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Crossbow'],
    experience: '10+ years',
    description: 'Whitetail deer hunting outfitter based in Coshocton County, Ohio. Guided hunts in one of Ohio\'s most productive whitetail areas.',
    website: 'https://www.coshoctoncountyoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },

  // ============================================================
  // PENNSYLVANIA (PA) -- Real outfitters
  // ============================================================
  {
    id: 5080,
    name: 'Sherks Guide Service',
    businessName: 'Sherks Guide Service',
    state: 'Pennsylvania',
    stateCode: 'PA',
    city: 'Lewis Run',
    species: ['Whitetail', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Located in Lewis Run, PA near the Allegheny National Forest. Books PA guided whitetail deer and bear hunting trips in the dense hardwood forests of northern Pennsylvania.',
    phone: '(814) 558-0696',
    email: 'clintsherk@hotmail.com',
    website: 'https://www.sherksguideservice.com',
    priceRange: '$$',
    buckStopPartner: false,
  },
  {
    id: 5081,
    name: 'Full Fan Lodge',
    businessName: 'Full Fan Lodge',
    state: 'Pennsylvania',
    stateCode: 'PA',
    city: 'Honesdale',
    species: ['Turkey', 'Whitetail', 'Bear'],
    methods: ['Rifle', 'Shotgun', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Northeast Pennsylvania\'s premier hunting lodge for wild turkey, whitetail deer, and black bear. Offers hunting on private land with full guide service and all-inclusive lodge accommodations.',
    website: 'https://www.fullfanlodge.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5082,
    name: 'The Moonshine Ranch',
    businessName: 'The Moonshine Ranch',
    state: 'Pennsylvania',
    stateCode: 'PA',
    city: 'Millville',
    species: ['Whitetail', 'Bear'],
    methods: ['Bow', 'Crossbow', 'Shotgun', 'Rifle'],
    experience: '10+ years',
    description: 'Offers whitetail deer hunting on private property and leased farmland with archery, crossbow, shotgun, and rifle options. Bear hunting available as add-on for $495 trophy fee with appropriate tags.',
    website: 'https://themoonshineranch.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5083,
    name: 'Burdicks Lodge',
    businessName: 'Burdicks Lodge',
    state: 'Pennsylvania',
    stateCode: 'PA',
    city: 'Smethport',
    species: ['Whitetail', 'Bear', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Muzzleloader', 'Shotgun'],
    experience: '15+ years',
    description: 'Located in McKean County, Allegheny Mountains. Provides 100% fair chase deer, bear, and turkey hunts in the dense forests of northern Pennsylvania.',
    website: 'https://www.padeerhunting.net',
    priceRange: '$$',
    buckStopPartner: false,
  },
  {
    id: 5084,
    name: 'Gsells Whitetails',
    businessName: 'Gsells Whitetails',
    state: 'Pennsylvania',
    stateCode: 'PA',
    city: 'Fayetteville',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Crossbow'],
    experience: '10+ years',
    description: 'Premier guided trophy whitetail hunts on private land in south-central Pennsylvania near Fayetteville.',
    website: 'https://www.gsellswhitetails.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5085,
    name: 'Evolved Whitetail Outfitters',
    businessName: 'Evolved Whitetail Outfitters',
    state: 'Pennsylvania',
    stateCode: 'PA',
    city: 'Bloomsburg',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Crossbow'],
    experience: '10+ years',
    description: 'Fully guided whitetail deer hunts in Central Pennsylvania near Bloomsburg. Trophy management program on private land.',
    website: 'https://www.evolvedwhitetailoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5086,
    name: 'Edmonds Outdoors',
    businessName: 'Edmonds Outdoors',
    state: 'Pennsylvania',
    stateCode: 'PA',
    city: 'Montrose',
    species: ['Whitetail', 'Bear'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '10+ years',
    description: 'Guided whitetail deer and bear hunting in northeastern Pennsylvania. Offers archery, rifle, and muzzleloader hunts on managed private land.',
    phone: '(570) 657-8361',
    website: 'https://edmondsoutdoors.co',
    priceRange: '$$',
    buckStopPartner: false,
  },
  {
    id: 5087,
    name: 'Powder Ridge Outfitters',
    businessName: 'Powder Ridge Outfitters',
    state: 'Pennsylvania',
    stateCode: 'PA',
    city: 'Mill Hall',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Crossbow'],
    experience: '10+ years',
    description: 'Pennsylvania whitetail deer hunting outfitter and preserve. Guided trophy whitetail hunts on managed private land in central Pennsylvania.',
    website: 'https://www.powderridgeoutfitters.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },

  // ============================================================
  // ADDITIONAL LISTINGS from HuntingLocator.com search index
  // ============================================================
  {
    id: 5090,
    name: 'Arizona High Country Outfitters',
    businessName: 'Arizona High Country Outfitters and Hunt Club',
    state: 'Arizona',
    stateCode: 'AZ',
    city: 'Show Low',
    species: ['Elk', 'Antelope', 'Bear', 'Turkey', 'Predator'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '60+ years combined',
    description: 'Regarded as one of the top big bull elk hunting destinations in Arizona. Over 60 years of combined experience. Also hunts antelope, black bear, turkey, mountain lion, javelina, bobcats, and coyotes across top-rated Arizona hunting units.',
    website: 'https://huntinglocator.com/businesses/detail/arizona-high-country-outfitters',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5091,
    name: 'Cowboy Country Outfitters',
    businessName: 'Cowboy Country Outfitters & Hunt Club',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Cody',
    species: ['Elk', 'Mule Deer', 'Antelope', 'Bear', 'Moose'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '18+ years',
    description: 'Wyoming\'s premier big game hunting outfitter since 2005. Offers guided hunts for elk, mule deer, antelope, bear, and moose in the Greater Yellowstone region.',
    website: 'https://huntinglocator.com/businesses/detail/cowboy-country-outfitters-hunt-club',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 5092,
    name: 'Gander Outfitter',
    businessName: 'Gander Outfitter',
    state: 'Missouri',
    stateCode: 'MO',
    city: 'Macon',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Shotgun'],
    experience: '15+ years',
    description: 'Missouri hunting outfitter with approximately 11,000 acres of prime hunting land. Guided whitetail deer and turkey hunts.',
    website: 'https://huntinglocator.com/businesses/detail/gander-outfitter',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5093,
    name: 'Indian Creek Lodge & Outfitter',
    businessName: 'Indian Creek Lodge & Outfitter',
    state: 'Alabama',
    stateCode: 'AL',
    city: 'Greenville',
    species: ['Whitetail', 'Turkey', 'Hog'],
    methods: ['Rifle', 'Bow', 'Shotgun'],
    experience: '15+ years',
    description: 'Hunting lodge and outfitter in Greenville, Alabama offering guided whitetail deer, turkey, and wild hog hunts on private Black Belt land.',
    website: 'https://huntinglocator.com/businesses/detail/indian-creek-lodge-outfitter',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5094,
    name: 'Maine Blackwater Outfitters',
    businessName: 'Maine Blackwater Outfitters',
    state: 'Maine',
    stateCode: 'ME',
    city: 'Ashland',
    species: ['Moose', 'Bear', 'Whitetail'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Maine-based hunting lodge and outfitter offering guided moose, bear, and whitetail deer hunts in the northern Maine wilderness.',
    website: 'https://huntinglocator.com/businesses/detail/maine-blackwater-outfitters',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 5095,
    name: 'Merryville Outfitters',
    businessName: 'Merryville Outfitters',
    state: 'Texas',
    stateCode: 'TX',
    city: 'Merryville',
    species: ['Whitetail'],
    methods: ['Rifle', 'Bow'],
    experience: '10+ years',
    description: 'Whitetail deer hunting outfitter offering guided hunts on managed private land in Texas.',
    website: 'https://huntinglocator.com/businesses/detail/merryville-outfitters',
    priceRange: '$$',
    buckStopPartner: false,
  },
  {
    id: 5096,
    name: 'Piney Woods Hunting Outfitter',
    businessName: 'Piney Woods Hunting Outfitter',
    state: 'Alabama',
    stateCode: 'AL',
    city: 'Troy',
    species: ['Whitetail', 'Turkey', 'Hog'],
    methods: ['Rifle', 'Bow', 'Shotgun'],
    experience: '10+ years',
    description: 'Located in Troy, Alabama. Guided whitetail deer, turkey, and wild hog hunts in the piney woods of southern Alabama.',
    website: 'https://huntinglocator.com/businesses/detail/piney-woods-hunting-outfitter',
    priceRange: '$$',
    buckStopPartner: false,
  },
  {
    id: 5097,
    name: 'Montana Hunting Club & Company',
    businessName: 'Montana Hunting Club & Company',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Billings',
    species: ['Elk', 'Mule Deer', 'Whitetail', 'Antelope'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Montana-based hunting club offering guided elk, mule deer, whitetail, and antelope hunts across multiple Montana hunting districts.',
    website: 'https://huntinglocator.com/businesses/detail/montana-hunting-club-company',
    priceRange: '$$$',
    buckStopPartner: false,
  },

  // ============================================================
  // HuntingTop10.com Scraped Data (2026-03-29)
  // Source: https://www.huntingtop10.com/united-states-of-america
  // Real outfitter profiles with verified contact information.
  // ============================================================

  // -- MONTANA (MT) --
  {
    id: 5100,
    name: 'Stockton Outfitters',
    businessName: 'Stockton Outfitters',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Anaconda',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '25+ years',
    description:
      'Montana\'s premier free-chase outfitter providing fully guided elk, mule deer, and spring black bear hunts in southwestern Montana (Region 3 - HD 319, HD 331, HD 332). Access to 187+ square miles of Deer Lodge/Beaverhead National Forest encompassing the Big Hole Valley, Anaconda Pintler Wilderness, and Pioneer Mountain Ranges. Featured on Outdoor Channel, Versus Network, and Sportsman\'s Channel. No trophy fees. Spring bear: $3,995 (2:1) / $4,750 (1:1). Black bear: $3,750 (2:1) / $4,250 (1:1).',
    phone: '(406) 782-9532',
    website: 'https://stocktonoutfitters.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.9,
    reviewCount: 124,
  },
  {
    id: 5101,
    name: 'Wayne Hill',
    businessName: 'Wayne Hill Outfitting',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Noxon',
    species: ['Elk', 'Mule Deer', 'Whitetail', 'Bear'],
    methods: ['Bow', 'Rifle'],
    experience: '40+ years',
    description:
      'Montana\'s premier elk hunting guides since 1981, operating on over 480,000 acres of the Kootenai National Forest in the Cabinet Mountains. Elk bow hunting $6,500 (8 days), rifle elk/deer $6,000 (7 days), spring black bear $4,000 (7 days). Success rates: 75% elk opportunity, 85% rifle deer, 90% spring bear. Food, lodging, and airport pickup included. Various bear color phases available.',
    phone: '(406) 847-5563',
    email: 'hiloutfit@blackfoot.net',
    website: 'https://waynehilloutfitting.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 96,
  },

  // -- COLORADO (CO) --
  {
    id: 5102,
    name: "Del's Triangle 3 Ranch",
    businessName: "Del's Triangle 3 Ranch, LLC",
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Clark',
    species: ['Elk', 'Mule Deer'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '60+ years',
    description:
      'One of Colorado\'s oldest licensed outfitters (License #22), operating since 1962. Offers private and public land fully guided elk and mule deer hunts in units 5, 14, and 214 of the Mt. Zirkel Wilderness, Routt National Forest. All public land hunts are horse-based. Five-day hunts with one guide per two hunters include cooking, wrangling, and game transport. Drop camps also available. Six generations in the valley.',
    phone: '(970) 879-3495',
    website: 'https://steamboathorses.com/camps/hunting/',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 82,
  },

  // -- PENNSYLVANIA (PA) --
  {
    id: 5103,
    name: 'Lou Lampitelli',
    businessName: 'The Moonshine Ranch',
    state: 'Pennsylvania',
    stateCode: 'PA',
    city: 'Equinunk',
    species: ['Bear', 'Turkey', 'Whitetail', 'Hog'],
    methods: ['Bow', 'Crossbow', 'Shotgun', 'Rifle'],
    experience: '30+ years',
    description:
      'Located in Wayne County, North Eastern Pennsylvania. Species include Black Bear, Eastern Turkey, Fallow Deer, Red Stag, Whitetail Deer, and Wild Boar. Free range and preserve hunts available. Host Lou Lampitelli has harvested over 30 plains game species. Archery, crossbow, shotgun, and rifle hunting. Cost-efficient bear hunting packages.',
    phone: '(631) 745-3235',
    website: 'https://themoonshineranch.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 58,
  },

  // -- WEST VIRGINIA (WV) --
  {
    id: 5104,
    name: 'Hans Creek Outfitters',
    businessName: 'Hans Creek Outfitters',
    state: 'West Virginia',
    stateCode: 'WV',
    city: 'Greenville',
    species: ['Whitetail', 'Turkey', 'Predator'],
    methods: ['Rifle', 'Bow', 'Shotgun'],
    experience: '20+ years',
    description:
      'Privately owned in Monroe County, southeastern West Virginia. Free range hunts for whitetail deer, Red Stag, fall/spring turkey, predator hunts, and upland birds. Species include Eastern Turkey, Bobcat, Coyote, Rabbit, Chukar, Pheasant, Quail. Luxury Grandview Cottages sleep up to 10 (4 bedrooms, 3.5 baths) with fishing and hiking.',
    phone: '(304) 832-6552',
    website: 'https://www.hanscreekoutfitterswv.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 73,
  },

  // -- NORTH CAROLINA (NC) --
  {
    id: 5105,
    name: 'Choanoke Outfitters',
    businessName: 'Choanoke Outfitters',
    state: 'North Carolina',
    stateCode: 'NC',
    city: 'Ahoskie',
    species: ['Whitetail', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Shotgun', 'Muzzleloader'],
    experience: '20+ years',
    description:
      'Some of the best whitetail hunting in North Carolina across 10,000+ acres in Hertford, Northhampton, and Bertie counties in the Roanoke River agricultural region. 150+ strategically located stands including shooting towers and ladder stands. Specializes in Whitetail Deer and Eastern Turkey.',
    phone: '(252) 395-0008',
    website: 'https://choanokeoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 64,
  },
  {
    id: 5106,
    name: 'Buffalo Creek Outfitters',
    businessName: 'Buffalo Creek Outfitters',
    state: 'North Carolina',
    stateCode: 'NC',
    city: 'Lewiston Woodville',
    species: ['Whitetail', 'Bear', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Shotgun', 'Muzzleloader'],
    experience: '15+ years',
    description:
      'All-inclusive whitetail deer, black bear, and spring turkey hunts in Bertie County (NC\'s highest deer density). 5-day deer hunt (3 does, 1 buck) $1,800; Deer & Bear Combo (5 days) $2,500; Spring Turkey (2 days) $1,000. Main lodge plus three cabins sleeping 4 each. 45 minutes east of I-95.',
    phone: '(252) 305-2787',
    email: 'Ugohunt@gmail.com',
    website: 'https://www.buffalocreekoutfitters.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 91,
  },

  // -- NEBRASKA (NE) --
  {
    id: 5107,
    name: 'Prairie Rock Outfitters',
    businessName: 'Prairie Rock Outfitters',
    state: 'Nebraska',
    stateCode: 'NE',
    city: 'Broadwater',
    species: ['Whitetail', 'Mule Deer', 'Elk', 'Turkey', 'Antelope', 'Waterfowl'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Shotgun'],
    experience: '20+ years',
    description:
      'Guided hunts in the Nebraska panhandle across 300,000+ acres stretching 40+ miles along the North Platte River. Mule deer, whitetail, antelope, elk, turkey, and waterfowl. Tree stands, ground blinds, and tower blinds. Archery: 5 days / 6 nights. Rifle: 4 days / 5 nights.',
    website: 'https://prairierockoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 78,
  },
  {
    id: 5108,
    name: 'Double D Trophy Outfitters',
    businessName: 'Double D Trophy Outfitters',
    state: 'Nebraska',
    stateCode: 'NE',
    city: 'Chadron',
    species: ['Mule Deer', 'Whitetail', 'Turkey', 'Antelope'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description:
      'Near Wyoming/South Dakota border on 50,000 acres of private land adjacent to public land. 4-night/5-day semi-guided mule deer and whitetail packages plus Merriam turkey and antelope. $500 deposit for deer/antelope/elk; $250 for turkey.',
    phone: '(605) 877-2550',
    website: 'https://www.doubledtrophyoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 52,
  },

  // -- IDAHO (ID) --
  {
    id: 5109,
    name: 'Ridgerunner Outfitters',
    businessName: 'Ridgerunner Outfitters',
    state: 'Idaho',
    stateCode: 'ID',
    city: 'Orofino',
    species: ['Elk', 'Bear', 'Moose', 'Mule Deer', 'Whitetail'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '30+ years',
    description:
      'Nez Perce/Clearwater National Forest. Guided elk, bear, deer, mountain lion, moose, mountain goat. Fully guided, semi-guided, drop camp, or spike camp. Shiras Moose (7 day) $8,000 + trophy fee. Semi-guided big game (7 day) $6,000. Drop camp (7 day) $4,500. Horses available for guided hunts.',
    phone: '(801) 633-3264',
    website: 'https://ridgerunneroutfitters.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 67,
  },

  // -- ARIZONA (AZ) --
  {
    id: 5110,
    name: 'Shadow Valley Outfitters',
    businessName: 'Shadow Valley Outfitters',
    state: 'Arizona',
    stateCode: 'AZ',
    city: 'Tucson',
    species: ['Elk', 'Mule Deer', 'Antelope', 'Bear', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '15+ years',
    description:
      'Premier Arizona big game outfitter: elk, mule deer, Coues deer, antelope, bighorn sheep, black bear, javelina, Merriam turkey. Fully outfitted/guided, guide-only, and scouting packages. 15 bucks over 200 inches since 2016, two over 245 inches. Guides in multiple AZ units.',
    phone: '(928) 533-1903',
    website: 'https://shadowvalleyoutfitters.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 88,
  },

  // -- ALABAMA (AL) --
  {
    id: 5111,
    name: 'Alabama Water Valley Lodge',
    businessName: 'Alabama Water Valley Lodge',
    state: 'Alabama',
    stateCode: 'AL',
    city: 'Gilbertown',
    species: ['Whitetail', 'Turkey', 'Hog'],
    methods: ['Rifle', 'Bow', 'Shotgun'],
    experience: '25+ years',
    description:
      'First-class hunting in rural Choctaw County on 30,000+ acres of diverse terrain. Turkey success sometimes 100% with multiple kills common. 17,000 sq ft lodge with guest rooms, private baths, dining hall, recreation room, billiards, big screen TV, and rocking-chair porches. Whitetail season Oct 15 - Jan 31.',
    website: 'https://www.watervalleylodge.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.9,
    reviewCount: 112,
  },

  // -- TENNESSEE (TN) --
  {
    id: 5112,
    name: 'Goodman Ranch',
    businessName: 'Goodman Ranch',
    state: 'Tennessee',
    stateCode: 'TN',
    city: 'Bethel Springs',
    species: ['Whitetail', 'Elk', 'Turkey', 'Hog'],
    methods: ['Rifle', 'Bow', 'Muzzleloader', 'Shotgun'],
    experience: '25+ years',
    description:
      'Tennessee\'s largest and most premier hunting outfitter since 1997. 1 hour from Memphis, 2.5 hours from Nashville. Whitetail 3-day/2-night at $3,995 including meals, lodging, trophy fees. Also Fallow Deer, Oryx, Texas Dall, Aoudad Sheep, Axis Deer, Bison, Blackbuck, Elk, Exotic Rams, Sika Deer, Pere David Deer, Turkey, and rare exotic game.',
    website: 'https://goodmanranch.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 95,
  },

  // -- OREGON (OR) --
  {
    id: 5113,
    name: 'Opal Butte Outfitters',
    businessName: 'Opal Butte Outfitters',
    state: 'Oregon',
    stateCode: 'OR',
    city: 'Heppner',
    species: ['Elk', 'Mule Deer'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '20+ years',
    description:
      'Oregon\'s premiere elk outfitter on 28,500 acres south of Heppner. Kirkpatrick family operation with 5-star accommodations. Excellent habitat with high elk and deer numbers year-round. Trophy-quality elk during Oregon archery season. Exceptional return client rate.',
    website: 'https://www.opalbutteoutfitters.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 76,
  },

  // -- FLORIDA (FL) --
  {
    id: 5114,
    name: "God's Country Outfitters",
    businessName: "God's Country Outfitters",
    state: 'Florida',
    stateCode: 'FL',
    city: 'San Mateo',
    species: ['Hog', 'Turkey', 'Whitetail'],
    methods: ['Rifle', 'Bow', 'Shotgun'],
    experience: '30+ years',
    description:
      'Florida\'s finest outfitting service since 2008 with 30+ years of hunting experience. 40,000+ acres along the St. Johns River. Osceola turkey, wild hog, and alligator hunts. Hog options: spot-and-stalk, night thermal, preserve (100% success), dog hunts (90%). Ranch-style lodge. 4.9 from 233+ reviews.',
    phone: '(386) 972-9473',
    website: 'https://godscountryoutfitters.net',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.9,
    reviewCount: 233,
  },

  // -- KANSAS (KS) --
  {
    id: 5115,
    name: 'Dirt Road Outfitters',
    businessName: 'Dirt Road Outfitters',
    state: 'Kansas',
    stateCode: 'KS',
    city: 'Stafford',
    species: ['Whitetail', 'Turkey', 'Waterfowl'],
    methods: ['Bow', 'Rifle', 'Shotgun'],
    experience: '25+ years',
    description:
      'South Central Kansas outfitter with land in top-five state counties for P&Y and B&C whitetail. Small camp sizes, limited hunter slots. 90+ combined years of Kansas whitetail experience. Thousands of acres privately managed with trail cameras and year-round scouting. Waterfowl: $2,000 for 3-day/4-night package.',
    phone: '(620) 388-2218',
    email: 'contact@dirtroadoutfitters.com',
    website: 'https://www.dirtroadoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 59,
  },

  // -- OHIO (OH) --
  {
    id: 5116,
    name: 'Flint Ridge Outfitters',
    businessName: 'Flint Ridge Outfitters',
    state: 'Ohio',
    stateCode: 'OH',
    city: 'Zanesville',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Muzzleloader', 'Shotgun'],
    experience: '15+ years',
    description:
      'Premier Ohio whitetail since 2008. 5-day archery hunts and 4-day muzzleloader hunts in January. Properties in Licking, Muskingum, and Perry counties (top Ohio trophy buck counties). Packages include lodging, meals, transport, stands/blinds. Lodge with deck, fire pit, 60-yard archery range. Turkey hunts April-May.',
    phone: '(740) 586-3075',
    website: 'https://flintridgeoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 54,
  },

  // -- ILLINOIS (IL) --
  {
    id: 5117,
    name: 'Genesis Whitetails',
    businessName: 'Genesis Whitetails',
    state: 'Illinois',
    stateCode: 'IL',
    city: 'Huntsville',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Crossbow', 'Muzzleloader'],
    experience: '15+ years',
    description:
      'Family-owned whitetail breeding facility and high-fence hunting preserve in west-central Illinois. Hardwood timber, winding creeks, ridges, thick bedding areas, and food plots. Fully guided hunts with box blinds, ground blinds, and ladder stands. Management practices produce exceptional bucks.',
    phone: '(217) 392-2115',
    website: 'https://genesiswhitetails.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 41,
  },

  // ============================================================
  // STATE AGENCY & ASSOCIATION SCRAPED DATA (2026-03-29)
  // Sources: WYOGA (wyoga.org), MOGA (montanaoutfitters.org),
  //   IOGA (ioga.org), COA (coloradooutfitters.org),
  //   NMCOG (nmoutfitters.com), MPGA (maineguides.org),
  //   APHA (alaskaprohunter.org), Guidefitter, Utah DWR
  // Data includes license numbers where available from HTML scrape.
  // ============================================================

  // -- WYOMING (WY) -- WYOGA member directory (live HTML scrape) --
  {
    id: 6000,
    name: 'Chad Christensen',
    businessName: '6x6 Outfitters',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Bancroft',
    species: ['Bear', 'Mule Deer', 'Elk', 'Moose'],
    methods: ['Rifle'],
    experience: '10+ years',
    description: 'Licensed WY outfitter (BG066). WYOGA member, Jackson region. Guided hunts for bear, deer, elk, mountain goat, and moose.',
    phone: '(208) 339-8872',
    email: '6x6outfitters@gmail.com',
    website: 'https://6x6outfitters.com/',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6001,
    name: 'Jim Schell',
    businessName: '88 Ranch Outfitters',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Glenrock',
    species: ['Antelope', 'Mule Deer'],
    methods: ['Bow', 'Rifle'],
    experience: '20+ years',
    description: 'Licensed WY outfitter (BG207), co-outfitter Dusty Schell (BG360). WYOGA Casper region. Antelope and mule deer on private ranch.',
    phone: '(307) 436-2304',
    email: 'jimsrco@aol.com',
    website: 'http://www.88ranchoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6002,
    name: 'Robert "Budd" Betts Jr.',
    businessName: 'Absaroka Ranch',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Dubois',
    species: ['Mule Deer', 'Elk'],
    methods: ['Rifle'],
    experience: '25+ years',
    description: 'Licensed WY outfitter (BG174). WYOGA Jackson/Lander-Dubois regions. Also fishing, horseback, pack trips, guest ranch.',
    phone: '(307) 455-2275',
    email: 'absaroka@wyoming.com',
    website: 'http://www.absarokaranch.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6003,
    name: 'Jessie Allen Gottwald',
    businessName: "Allen's Diamond 4 Wilderness Ranch",
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Lander',
    species: ['Antelope', 'Mule Deer', 'Elk', 'Moose'],
    methods: ['Rifle'],
    experience: '30+ years',
    description: 'Licensed WY outfitter (BG006). WYOGA Lander-Dubois. Bighorn sheep, antelope, deer, elk, moose. Fishing, horseback, pack trips.',
    phone: '(307) 332-2995',
    email: 'diamond4@wyoming.com',
    website: 'https://www.diamond4ranch.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6004,
    name: 'Patrick Ginder',
    businessName: 'At Ease Hunting',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Casper',
    species: ['Antelope', 'Mule Deer', 'Elk'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'Licensed WY outfitter (BG201). WYOGA Casper region. Guided antelope, mule deer, and elk hunts.',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6005,
    name: 'SNS Outfitter Team',
    businessName: 'SNS Outfitter and Guides',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Casper',
    species: ['Antelope', 'Bear', 'Mule Deer', 'Elk', 'Moose', 'Turkey'],
    methods: ['Rifle', 'Bow'],
    experience: '25+ years',
    description: 'WYOGA member. Antelope, bear, deer, elk, moose, turkey, and varmints across central Wyoming.',
    phone: '(307) 266-4229',
    email: 'sns@huntwyo.com',
    website: 'https://www.huntwyo.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6006,
    name: 'Timberline Team',
    businessName: 'Timberline Outfitters',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Cheyenne',
    species: ['Elk', 'Mule Deer', 'Antelope', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'WYOGA member. Big game hunting for elk, deer, antelope, mountain lion, bear, and turkey.',
    phone: '(307) 635-7288',
    email: 'Timber4In@aol.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6007,
    name: 'Barlow Team',
    businessName: 'Barlow Outfitting',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Story',
    species: ['Elk', 'Bear', 'Moose', 'Mule Deer', 'Whitetail', 'Antelope'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'WYOGA member. Jedediah Smith Wilderness, Gros Ventre Wilderness, Hoback Snake River ranges. Elk, goat, bear, moose, deer, antelope, sheep.',
    phone: '(307) 413-0726',
    email: 'barlowoutfitting@gmail.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6008,
    name: 'Wyoming Wildlife Team',
    businessName: 'Wyoming Wildlife Outfitters',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Sheridan',
    species: ['Elk', 'Mule Deer', 'Whitetail', 'Antelope', 'Turkey'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'WYOGA member. Quality private land hunts for elk, mule deer, whitetail, antelope, and turkey.',
    phone: '(307) 683-7938',
    email: 'rmarosok@wyoming.com',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6009,
    name: 'Elk Mountain Team',
    businessName: 'Elk Mountain Outfitters / Wapiti Ridge Ranch',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Elk Mountain',
    species: ['Elk', 'Mule Deer', 'Whitetail', 'Antelope', 'Moose', 'Turkey'],
    methods: ['Rifle', 'Bow'],
    experience: '50+ years',
    description: 'WYOGA member since 1970. 4x4 and horseback hunting for elk, mule deer, whitetail, antelope, bighorn sheep, moose, and turkey.',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6010,
    name: 'Bear Track Team',
    businessName: 'Bear Track Outfitters',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Cody',
    species: ['Antelope', 'Elk', 'Mule Deer'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'WYOGA member. Fully guided hunts in north central Wyoming for antelope, elk, and mule deer.',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6011,
    name: 'High Pine Team',
    businessName: 'High Pine Outfitters',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Thermopolis',
    species: ['Elk', 'Mule Deer', 'Antelope'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'WYOGA member. Trophy elk in areas 7, 122, 123; deer areas 21, 65; antelope areas 24, 30.',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6012,
    name: 'Elk Fork Team',
    businessName: 'Elk Fork Outfitters',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Meeteetse',
    species: ['Elk', 'Mule Deer', 'Antelope'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'WYOGA member. Horseback hunts for elk and bighorn sheep; mule deer migration hunts with lodge; spot-and-stalk antelope.',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6013,
    name: 'Jenkins Family',
    businessName: 'Jenkins Hunting Camp',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Jackson',
    species: ['Mule Deer', 'Elk', 'Antelope', 'Moose', 'Bear'],
    methods: ['Rifle'],
    experience: '50+ years',
    description: 'Second-generation WYOGA member. Horseback hunts since 1970 for trophy mule deer, elk, antelope, moose, and bear.',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6014,
    name: 'Backcountry Hunting Team',
    businessName: 'Backcountry Hunting Logistics',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Casper',
    species: ['Elk', 'Mule Deer', 'Antelope'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'WYOGA member. Quality elk, deer, antelope, and bighorn sheep hunts in central Wyoming.',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6015,
    name: 'Butte Creek Team',
    businessName: 'Butte Creek Outfitters',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Cody',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle'],
    experience: '20+ years',
    description: 'WYOGA member. Pack-in wilderness hunts for elk, deer, sheep, and black bear; antelope/deer from lodge.',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6016,
    name: 'Wagonhound Team',
    businessName: 'Wagonhound Outfitters',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Douglas',
    species: ['Elk', 'Mule Deer', 'Antelope'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'WYOGA member on extensive private ranch land in central Wyoming.',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6017,
    name: 'Robert Model',
    businessName: 'Robert Model Outfitter, LLC',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Lander',
    species: ['Elk', 'Mule Deer'],
    methods: ['Rifle'],
    experience: '15+ years',
    description: 'WYOGA member. Only permitted camp in Trout Creek Drainage elk area 54. Also Deer Area 111 and Sheep Area 2.',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6018,
    name: 'WPH Team',
    businessName: 'Wyoming Professional Hunters, LTD',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Sheridan',
    species: ['Elk', 'Mule Deer', 'Antelope'],
    methods: ['Rifle', 'Bow'],
    experience: '25+ years',
    description: 'WYOGA member. Quality hunting on privately controlled lands; internationally recognized archery antelope hunts.',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6019,
    name: 'Livingston Team',
    businessName: 'Livingston Outfitting, Inc.',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Cody',
    species: ['Elk', 'Mule Deer'],
    methods: ['Rifle', 'Bow'],
    experience: '35+ years',
    description: 'WYOGA member. Lee guiding since 1985. Alex licensed 2024. Trophy bull elk specialty.',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6020,
    name: 'Big Horn Outfitters Team',
    businessName: 'Big Horn Outfitters',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Sheridan',
    species: ['Antelope', 'Elk', 'Mule Deer', 'Whitetail', 'Moose', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Shotgun'],
    experience: '20+ years',
    description: 'WYOGA member in the Big Horn Mountains. Antelope, elk, mule deer, whitetail, moose, turkey, and prairie dog.',
    priceRange: '$$$',
    buckStopPartner: false,
  },

  // -- COLORADO (CO) -- COA directory, Guidefitter (assoc. data) --
  {
    id: 6030,
    name: 'Bearcat Outfitters Team',
    businessName: 'Bearcat Outfitters',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Craig',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '70+ years',
    description: 'COA member est. 1953. Quality hunts for elk, mule deer, black bear, bobcat, mountain lion. $2,700-$4,950.',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6031,
    name: 'Circle K Ranch Team',
    businessName: 'Circle K Ranch, Inc.',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Dolores',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '60+ years',
    description: 'COA member since 1961. Southwest CO guide and outfitter. Trophy elk and mule deer. $1,675-$4,600.',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6032,
    name: 'Sable Mountain Team',
    businessName: 'Sable Mountain Outfitters, LLC',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Meeker',
    species: ['Bear', 'Mule Deer', 'Elk', 'Moose'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '15+ years',
    description: 'COA member. Public land big game for bear, deer, elk, moose near White River National Forest.',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6033,
    name: 'Base Camp Team',
    businessName: 'Base Camp Outfitters, LLC',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Montrose',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'Family-owned. CO unit 62. Semi-guided, fully-guided, and drop camp DIY hunts for elk, mule deer, black bear.',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6034,
    name: 'Prather Outfitters Team',
    businessName: 'Prather Outfitters, Inc.',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Hotchkiss',
    species: ['Mule Deer', 'Elk', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '25+ years',
    description: 'Western CO big game on ~10,000 acres private land with full accommodations.',
    website: 'https://www.guidefitter.com/pratheroutfitters',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6035,
    name: 'Adam Gall',
    businessName: 'Dark Timber Outfitters',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Gunnison',
    species: ['Elk', 'Mule Deer'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'Guidefitter-listed. Units 61 and 62, considered best elk hunting in CO.',
    phone: '(208) 691-3014',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6036,
    name: 'Gunnison Country Team',
    businessName: 'Gunnison Country Outfitters',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Gunnison',
    species: ['Elk', 'Mule Deer'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'COA member. Experienced elk and mule deer guides in the Gunnison area.',
    website: 'https://gunnisoncountryoutfitters.com/',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6037,
    name: 'H and H Team',
    businessName: 'H and H Outfitting',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Meeker',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '25+ years',
    description: 'COA member. Guided hunts in the Flat Tops Wilderness out of Meeker.',
    website: 'https://handhoutfitting.com/',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6038,
    name: 'Colorado Elk Outfitter Team',
    businessName: 'Colorado Elk Outfitter, LLC',
    state: 'Colorado',
    stateCode: 'CO',
    city: 'Eagle',
    species: ['Elk'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Registered, bonded, insured CO outfitter. World-class elk hunts.',
    website: 'https://coloradoelkoutfitter.com/',
    priceRange: '$$$$',
    buckStopPartner: false,
  },

  // -- NEW MEXICO (NM) -- NMCOG, Guidefitter, NMDGF --
  {
    id: 6050,
    name: 'Heritage Team',
    businessName: 'Heritage Outfitters, LLC',
    state: 'New Mexico',
    stateCode: 'NM',
    city: 'Albuquerque',
    species: ['Elk', 'Mule Deer', 'Antelope'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '25+ years',
    description: 'NM registered. Family-run, 25+ years for elk, mule deer, barbary sheep, oryx, and pronghorn.',
    phone: '(505) 239-2128',
    website: 'https://www.heritageoutfittersnm.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6051,
    name: 'Ridgeline Team',
    businessName: 'Ridgeline Outfitters',
    state: 'New Mexico',
    stateCode: 'NM',
    city: 'Ruidoso',
    species: ['Elk', 'Mule Deer', 'Antelope'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'NM premier elk, antelope, mule deer, oryx outfitter. Barbary sheep and Coues whitetail. NMCOG member.',
    website: 'https://ridgelineoutfitters.com/',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6052,
    name: '505 Outfitters Team',
    businessName: '505 Outfitters',
    state: 'New Mexico',
    stateCode: 'NM',
    city: 'Las Cruces',
    species: ['Elk', 'Mule Deer', 'Antelope'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'NM registered outfitter. Guided hunts across southern NM for elk, mule deer, oryx, and pronghorn.',
    website: 'http://www.505hunting.com/',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6053,
    name: 'G3 Outfitters Team',
    businessName: 'G3 Outfitters',
    state: 'New Mexico',
    stateCode: 'NM',
    city: 'Santa Fe',
    species: ['Elk', 'Mule Deer', 'Antelope', 'Bear', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'NM registered. Elk, mule deer, antelope, Coues deer, oryx, aoudad, bear, bighorn sheep, ibex, turkey.',
    website: 'https://www.g3outfitters.com',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6054,
    name: 'Radiant R Team',
    businessName: 'Radiant R Outfitters',
    state: 'New Mexico',
    stateCode: 'NM',
    city: 'Tularosa',
    species: ['Elk', 'Mule Deer', 'Antelope'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'NM registered. Guided hunting across southern New Mexico.',
    phone: '(575) 518-8323',
    website: 'https://radiantroutfitters.com/',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6055,
    name: 'NMHA Team',
    businessName: 'New Mexico Hunting Adventures',
    state: 'New Mexico',
    stateCode: 'NM',
    city: 'Albuquerque',
    species: ['Elk', 'Mule Deer', 'Antelope', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'NM registered, NMCOG member. Elk, mule deer, antelope, oryx, and bear.',
    website: 'https://nmhuntingadventures.com/',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6056,
    name: 'Frontier Outfitting Team',
    businessName: 'Frontier Outfitting',
    state: 'New Mexico',
    stateCode: 'NM',
    city: 'Chama',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'NM premier outfitter, NMCOG member. Elk, deer, and bear in northern NM.',
    website: 'https://frontieroutfitting.com/',
    priceRange: '$$$$',
    buckStopPartner: false,
  },

  // -- IDAHO (ID) -- IOGA (ioga.org), Guidefitter --
  {
    id: 6070,
    name: 'Travis Bullock',
    businessName: 'Mile High Outfitters',
    state: 'Idaho',
    stateCode: 'ID',
    city: 'Challis',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '25+ years',
    description: 'IOGA member. Horseback wilderness hunting/fishing in Frank Church Wilderness. Insured and bonded.',
    website: 'https://www.milehighoutfitters.com/',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6071,
    name: 'Amon Molsee',
    businessName: 'Shattuck Creek Outfitters',
    state: 'Idaho',
    stateCode: 'ID',
    city: 'Elk River',
    species: ['Elk', 'Whitetail', 'Mule Deer', 'Moose', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'Second-generation IOGA member. Elk, whitetail, mule deer, moose, bear, mountain lion, wolf.',
    website: 'https://shattuckcreek.com/',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6072,
    name: 'Bitterroot Team',
    businessName: 'Bitterroot Outfitters',
    state: 'Idaho',
    stateCode: 'ID',
    city: 'Salmon',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'IOGA member. Guided elk, deer, bear, and lion in the Idaho backcountry.',
    website: 'https://www.idahohunts.net/',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6073,
    name: 'Bear Creek Team',
    businessName: 'Bear Creek Outfitters',
    state: 'Idaho',
    stateCode: 'ID',
    city: 'Grangeville',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '25+ years',
    description: 'IOGA member. Week-long elk/deer in Selway-Bitterroot Wilderness. Mountain lion and spring bear.',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6074,
    name: 'Cameron Team',
    businessName: 'Cameron Outfitters',
    state: 'Idaho',
    stateCode: 'ID',
    city: 'McCall',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'IOGA member. Idaho elk, deer, bear, and lion in the Frank Church Wilderness.',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6075,
    name: 'McGowan Team',
    businessName: 'McGowan Outfitting',
    state: 'Idaho',
    stateCode: 'ID',
    city: 'Boise',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'IOGA member directory listing.',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6076,
    name: 'Wild Idaho Team',
    businessName: 'Wild Idaho Outfitters',
    state: 'Idaho',
    stateCode: 'ID',
    city: 'Cascade',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'Licensed Idaho outfitter. Elk, deer, bear, wolf, and combo hunts.',
    website: 'https://www.wildidahooutfitters.com/',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6077,
    name: 'Bearpaw Team',
    businessName: 'Bearpaw Outfitters',
    state: 'Idaho',
    stateCode: 'ID',
    city: 'Moscow',
    species: ['Elk', 'Mule Deer', 'Bear', 'Moose'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'Licensed outfitter. Guided and unguided elk, deer, bear, cougar, moose in ID, MT, UT, WA.',
    website: 'https://www.bearpawoutfitters.com/',
    priceRange: '$$$',
    buckStopPartner: false,
  },

  // -- MONTANA (MT) -- MOGA (montanaoutfitters.org), Guidefitter --
  {
    id: 6090,
    name: 'Absaroka-Beartooth Team',
    businessName: 'Absaroka-Beartooth Outfitters',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Livingston',
    species: ['Elk', 'Mule Deer', 'Bear', 'Moose'],
    methods: ['Rifle', 'Bow'],
    experience: '25+ years',
    description: 'Licensed MT outfitter. Absaroka-Beartooth Wilderness near Yellowstone.',
    website: 'https://absarokabeartooth.com/',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6091,
    name: 'Cody Carr',
    businessName: 'Hunt with Cody',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Helena',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'Licensed MT outfitter, MOGA member. Elk, deer, bear, mountain lion.',
    website: 'https://huntwithcody.com/',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6092,
    name: "Wemple's Team",
    businessName: "Wemple's Wildlife Outfitter",
    state: 'Montana',
    stateCode: 'MT',
    city: 'Great Falls',
    species: ['Elk', 'Mule Deer', 'Whitetail', 'Bear', 'Antelope'],
    methods: ['Rifle', 'Bow'],
    experience: '25+ years',
    description: 'Montana big game outfitter. Guided hunts across central MT.',
    website: 'https://www.montana-hunting-outfitter.com/',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6093,
    name: 'Elk Creek Team',
    businessName: 'Elk Creek Outfitting',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Kalispell',
    species: ['Elk', 'Mule Deer', 'Whitetail', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'Elk, mule deer, whitetail, bear in NW Montana near Glacier National Park.',
    website: 'https://elkcreekoutfitting.com/',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6094,
    name: 'Yaak River Team',
    businessName: 'Yaak River Outfitters',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Troy',
    species: ['Bear', 'Elk', 'Mule Deer', 'Moose'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'Guidefitter-listed. Bear, elk, deer, moose in remote Yaak River valley, NW Montana.',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6095,
    name: 'Linehan Outfitting Team',
    businessName: 'Linehan Outfitting',
    state: 'Montana',
    stateCode: 'MT',
    city: 'Troy',
    species: ['Elk', 'Mule Deer', 'Whitetail', 'Bear', 'Moose'],
    methods: ['Rifle', 'Bow'],
    experience: '30+ years',
    description: 'Licensed MT outfitter. Kootenai National Forest, NW Montana.',
    website: 'https://www.fishmontana.com/',
    priceRange: '$$$$',
    buckStopPartner: false,
  },

  // -- MAINE (ME) -- MPGA (maineguides.org), State registry --
  {
    id: 6110,
    name: 'Paul Beauregard',
    businessName: 'PB Guide Service',
    state: 'Maine',
    stateCode: 'ME',
    city: 'Brownville',
    species: ['Bear', 'Moose', 'Whitetail'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '30+ years',
    description: 'Registered Maine Guide, MPGA member. 30+ years guiding bear, moose, and deer.',
    phone: '(207) 399-7000',
    email: 'info@pbguideservice.com',
    website: 'https://www.pbguideservice.com/',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6111,
    name: 'Jeff Fay',
    businessName: 'Spaulding Lake Outfitters',
    state: 'Maine',
    stateCode: 'ME',
    city: 'Patten',
    species: ['Moose', 'Whitetail', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '20+ years',
    description: 'Registered Maine Guide, MPGA member. One-on-one moose, deer, bird hunting in northern Maine.',
    website: 'https://www.spauldinglakeoutfitters.com/',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6112,
    name: 'Stony Brook Team',
    businessName: 'Stony Brook Outfitters',
    state: 'Maine',
    stateCode: 'ME',
    city: 'Millinocket',
    species: ['Moose', 'Whitetail', 'Bear', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Shotgun'],
    experience: '25+ years',
    description: 'MPGA member, Registered Maine Guide. Moose, deer, bear, turkey in the Katahdin region.',
    priceRange: '$$$',
    buckStopPartner: false,
  },
  {
    id: 6113,
    name: 'Bulldog Camps Team',
    businessName: 'Bulldog Camps',
    state: 'Maine',
    stateCode: 'ME',
    city: 'Greenville',
    species: ['Moose', 'Whitetail', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '30+ years',
    description: 'Registered Maine Guides, MPGA member. Wilderness camps. Moose, deer, bear in Moosehead Lake region.',
    priceRange: '$$$',
    buckStopPartner: false,
  },

  // -- ALASKA (AK) -- APHA (alaskaprohunter.org), ADF&G --
  {
    id: 6130,
    name: 'Henry Tiffany',
    businessName: 'Alaskan Perimeter Expeditions',
    state: 'Alaska',
    stateCode: 'AK',
    city: 'Ester',
    species: ['Moose', 'Bear'],
    methods: ['Rifle'],
    experience: '30+ years',
    description: 'APHA member. Licensed Master Guide, 30+ years. Trophy Dall sheep, moose, grizzly, brown bear.',
    phone: '(907) 223-3226',
    website: 'https://www.alaskanperimeter.com/',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6131,
    name: 'Coke Wallace',
    businessName: 'Midnight Sun Safaris',
    state: 'Alaska',
    stateCode: 'AK',
    city: 'Healy',
    species: ['Bear', 'Moose'],
    methods: ['Rifle'],
    experience: '30+ years',
    description: 'APHA member, Master Guide. Horseback outfitting for grizzly, caribou, moose, Dall sheep, wolf.',
    website: 'https://midnightsunsafaris.com/',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6132,
    name: 'Dave Leonard',
    businessName: 'Mountain Monarchs of Alaska',
    state: 'Alaska',
    stateCode: 'AK',
    city: 'Fairbanks',
    species: ['Moose', 'Bear'],
    methods: ['Rifle'],
    experience: '40+ years',
    description: 'APHA member. State Land concession, Central Brooks Range. Dall sheep, moose, grizzly.',
    website: 'https://www.mountainmonarchs.com/',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6133,
    name: 'Joey Klutsch',
    businessName: 'Katmai Guide Service',
    state: 'Alaska',
    stateCode: 'AK',
    city: 'King Salmon',
    species: ['Bear', 'Moose'],
    methods: ['Rifle'],
    experience: '20+ years',
    description: 'APHA member, Master Guide. Sheep, bear, caribou, goat, moose, wolf in Arctic NWR and AK Peninsula NWR.',
    website: 'https://katmaiguideservice.com/',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6134,
    name: 'Buck Bowden',
    businessName: 'Hidden Alaska Guides and Outfitters',
    state: 'Alaska',
    stateCode: 'AK',
    city: 'Anchorage',
    species: ['Moose', 'Bear'],
    methods: ['Rifle'],
    experience: '25+ years',
    description: 'APHA member. Licensed Alaska guide. Dall sheep, moose, bear, caribou.',
    website: 'https://hiddenak.com/',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
  {
    id: 6135,
    name: 'Ultimate Alaskan Team',
    businessName: 'Ultimate Alaskan Adventures',
    state: 'Alaska',
    stateCode: 'AK',
    city: 'Palmer',
    species: ['Bear', 'Moose'],
    methods: ['Rifle'],
    experience: '20+ years',
    description: 'Licensed Master Alaska Guide. Bear, Dall sheep, mountain goat, predator hunts.',
    website: 'https://ultimatealaskanadventure.com/',
    priceRange: '$$$$',
    buckStopPartner: false,
  },
];
