// SEED DATA: These are placeholder listings to be replaced with real scraped data
// from state wildlife agencies, outfitter associations, and verified registrations.
// All entries below have verified: false and source: 'seed'.

import type { HuntingGuide } from './guides';

// Seed entries omit verified/source -- defaults applied in guide-data.ts
export type SeedGuide = Omit<HuntingGuide, 'verified' | 'source'>;

export const guidesNW: SeedGuide[] = [
  // ============================================================
  // Nebraska (NE)
  // ============================================================
  {
    id: 200,
    name: 'Dan Kreiger',
    businessName: 'Platte River Outfitters',
    state: 'Nebraska',
    stateCode: 'NE',
    city: 'Grand Island',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Shotgun'],
    experience: '20+ years',
    description: 'Specializes in trophy whitetail hunts along the Platte River corridor with access to over 10,000 acres of private farmland.',
    phone: '(555) 301-4821',
    email: 'dan@platteriver.com',
    website: 'https://platterriveroutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 68,
  },
  {
    id: 201,
    name: 'Travis Becker',
    businessName: 'Sandhills Guide Service',
    state: 'Nebraska',
    stateCode: 'NE',
    city: 'Valentine',
    species: ['Whitetail', 'Mule Deer', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Guides hunts through the rugged Sandhills terrain where whitetail and mule deer ranges overlap.',
    phone: '(555) 301-5592',
    email: 'travis@sandhillsguide.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 42,
  },
  {
    id: 202,
    name: 'Kyle Messner',
    businessName: 'Cornhusker Trophy Hunts',
    state: 'Nebraska',
    stateCode: 'NE',
    city: 'Norfolk',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Crossbow'],
    experience: '12+ years',
    description: 'Manages intensively for Boone and Crockett class whitetails on northeast Nebraska river-bottom farms.',
    phone: '(555) 301-6743',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 31,
  },
  {
    id: 203,
    name: 'Jeff Randolph',
    businessName: 'Nebraska Waterfowl & Deer',
    state: 'Nebraska',
    stateCode: 'NE',
    city: 'Kearney',
    species: ['Whitetail', 'Waterfowl', 'Turkey'],
    methods: ['Rifle', 'Shotgun', 'Bow'],
    experience: '18+ years',
    description: 'Offers combination hunts for whitetail and Central Flyway waterfowl along the Platte River migration corridor.',
    phone: '(555) 301-7890',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 55,
  },

  // ============================================================
  // Nevada (NV)
  // ============================================================
  {
    id: 204,
    name: 'Cody Harmon',
    businessName: 'Silver State Outfitters',
    state: 'Nevada',
    stateCode: 'NV',
    city: 'Elko',
    species: ['Mule Deer', 'Elk', 'Antelope'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '22+ years',
    description: 'Hunts the Ruby Mountains and surrounding high desert for trophy mule deer and elk on exclusive private ranches.',
    phone: '(555) 302-1001',
    email: 'cody@silverstateoutfitters.com',
    website: 'https://silverstateoutfitters.com',
    priceRange: '$$$$',
    buckStopPartner: true,
    rating: 4.9,
    reviewCount: 87,
  },
  {
    id: 205,
    name: 'Rick Vasquez',
    businessName: 'Basin & Range Hunts',
    state: 'Nevada',
    stateCode: 'NV',
    city: 'Winnemucca',
    species: ['Mule Deer', 'Antelope'],
    methods: ['Rifle', 'Bow'],
    experience: '14+ years',
    description: 'Guides spot-and-stalk hunts across vast basin and range country in northern Nevada.',
    phone: '(555) 302-1122',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 29,
  },
  {
    id: 206,
    name: 'Marcus Dillon',
    businessName: 'High Desert Guide Co.',
    state: 'Nevada',
    stateCode: 'NV',
    city: 'Ely',
    species: ['Elk', 'Mule Deer'],
    methods: ['Rifle', 'Muzzleloader'],
    experience: '10+ years',
    description: 'Specializes in guided elk hunts in remote mountain ranges of eastern Nevada with pack-in camps.',
    phone: '(555) 302-1243',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 22,
  },

  // ============================================================
  // New Hampshire (NH)
  // ============================================================
  {
    id: 207,
    name: 'Brian Leach',
    businessName: 'White Mountain Guide Service',
    state: 'New Hampshire',
    stateCode: 'NH',
    city: 'Conway',
    species: ['Whitetail', 'Bear', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '18+ years',
    description: 'Guides hunts through hardwood ridges and river valleys at the base of the White Mountains.',
    phone: '(555) 303-2010',
    email: 'brian@whitemtnguide.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 38,
  },
  {
    id: 208,
    name: 'Steve Morrill',
    businessName: 'Granite State Outfitters',
    state: 'New Hampshire',
    stateCode: 'NH',
    city: 'Keene',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Shotgun'],
    experience: '12+ years',
    description: 'Focuses on pressured public-land whitetails in the oak and beech forests of southwestern New Hampshire.',
    phone: '(555) 303-2131',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.3,
    reviewCount: 19,
  },
  {
    id: 209,
    name: 'Matt Dubois',
    businessName: 'North Country Hunts',
    state: 'New Hampshire',
    stateCode: 'NH',
    city: 'Lancaster',
    species: ['Whitetail', 'Bear', 'Moose'],
    methods: ['Rifle', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Operates in the remote North Country where moose permits are available and black bear populations are strong.',
    phone: '(555) 303-2252',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 44,
  },

  // ============================================================
  // New Jersey (NJ)
  // ============================================================
  {
    id: 210,
    name: 'Anthony Caruso',
    businessName: 'Garden State Whitetails',
    state: 'New Jersey',
    stateCode: 'NJ',
    city: 'Newton',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Shotgun', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Hunts the farmland and hardwood ridges of Sussex County where trophy whitetails thrive in a high-pressure state.',
    phone: '(555) 304-3010',
    email: 'anthony@gardenstatewhitetails.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 27,
  },
  {
    id: 211,
    name: 'Dave Petroski',
    businessName: 'Pine Barrens Outfitters',
    state: 'New Jersey',
    stateCode: 'NJ',
    city: 'Vineland',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Shotgun'],
    experience: '10+ years',
    description: 'Guides deer and turkey hunts in the vast Pine Barrens region of southern New Jersey.',
    phone: '(555) 304-3131',
    priceRange: '$',
    buckStopPartner: false,
    rating: 4.2,
    reviewCount: 14,
  },

  // ============================================================
  // New Mexico (NM)
  // ============================================================
  {
    id: 212,
    name: 'Luis Montoya',
    businessName: 'High Plains Outfitters',
    state: 'New Mexico',
    stateCode: 'NM',
    city: 'Raton',
    species: ['Elk', 'Mule Deer', 'Antelope'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '25+ years',
    description: 'Runs horseback elk and mule deer hunts across the Sangre de Cristo foothills with private ranch access.',
    phone: '(555) 305-4010',
    email: 'luis@highplainsoutfitters.com',
    website: 'https://highplainsoutfittersnm.com',
    priceRange: '$$$$',
    buckStopPartner: true,
    rating: 4.9,
    reviewCount: 112,
  },
  {
    id: 213,
    name: 'Jake Thornton',
    businessName: 'Gila Wilderness Hunts',
    state: 'New Mexico',
    stateCode: 'NM',
    city: 'Silver City',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '18+ years',
    description: 'Guides backcountry hunts in the Gila Wilderness, one of the most remote and game-rich areas in the Southwest.',
    phone: '(555) 305-4131',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 63,
  },
  {
    id: 214,
    name: 'Carlos Gutierrez',
    businessName: 'Rio Grande Guide Service',
    state: 'New Mexico',
    stateCode: 'NM',
    city: 'Socorro',
    species: ['Mule Deer', 'Antelope', 'Predator'],
    methods: ['Rifle', 'Bow'],
    experience: '12+ years',
    description: 'Specializes in long-range mule deer and antelope hunts on the open plains along the Rio Grande valley.',
    phone: '(555) 305-4252',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.3,
    reviewCount: 25,
  },
  {
    id: 215,
    name: 'Ben Kessler',
    businessName: 'Land of Enchantment Elk',
    state: 'New Mexico',
    stateCode: 'NM',
    city: 'Chama',
    species: ['Elk', 'Mule Deer'],
    methods: ['Rifle', 'Muzzleloader', 'Bow'],
    experience: '20+ years',
    description: 'Operates drop camps and fully guided elk hunts in the high country of the Carson and Santa Fe National Forests.',
    phone: '(555) 305-4373',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 71,
  },

  // ============================================================
  // New York (NY)
  // ============================================================
  {
    id: 216,
    name: 'Mike Salvatore',
    businessName: 'Adirondack Trophy Hunts',
    state: 'New York',
    stateCode: 'NY',
    city: 'Saranac Lake',
    species: ['Whitetail', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '22+ years',
    description: 'Hunts the deep hardwood forests and beaver swamps of the Adirondack Park for mature whitetails and black bears.',
    phone: '(555) 306-5010',
    email: 'mike@adirondacktrophy.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 52,
  },
  {
    id: 217,
    name: 'Tom Bridges',
    businessName: 'Finger Lakes Outfitters',
    state: 'New York',
    stateCode: 'NY',
    city: 'Geneva',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Crossbow', 'Shotgun'],
    experience: '15+ years',
    description: 'Guides hunts on agricultural land between the Finger Lakes where whitetails grow big on rich crop fields.',
    phone: '(555) 306-5131',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 39,
  },
  {
    id: 218,
    name: 'Jim Kowalski',
    businessName: 'Western NY Whitetails',
    state: 'New York',
    stateCode: 'NY',
    city: 'Batavia',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Crossbow'],
    experience: '10+ years',
    description: 'Manages a network of private farms in Genesee County known for consistently producing 140-class bucks.',
    phone: '(555) 306-5252',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 28,
  },
  {
    id: 219,
    name: 'Paul Hennessy',
    businessName: 'Catskill Mountain Hunts',
    state: 'New York',
    stateCode: 'NY',
    city: 'Margaretville',
    species: ['Whitetail', 'Bear', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Shotgun'],
    experience: '17+ years',
    description: 'Offers guided hunts in the steep terrain of the Catskill Mountains with a focus on wilderness-style experiences.',
    phone: '(555) 306-5373',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.3,
    reviewCount: 21,
  },

  // ============================================================
  // North Carolina (NC)
  // ============================================================
  {
    id: 220,
    name: 'Chad Richardson',
    businessName: 'Piedmont Trophy Outfitters',
    state: 'North Carolina',
    stateCode: 'NC',
    city: 'Salisbury',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Hunts the rolling Piedmont hills and agricultural fields where big-bodied whitetails feed on soybeans and corn.',
    phone: '(555) 307-6010',
    email: 'chad@piedmonttrophy.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 58,
  },
  {
    id: 221,
    name: 'Bobby Tate',
    businessName: 'Smoky Mountain Bear Hunts',
    state: 'North Carolina',
    stateCode: 'NC',
    city: 'Waynesville',
    species: ['Bear', 'Whitetail', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '25+ years',
    description: 'Specializes in black bear hunts with hounds in the rugged mountains of western North Carolina.',
    phone: '(555) 307-6131',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 76,
  },
  {
    id: 222,
    name: 'Derek Wallace',
    businessName: 'Coastal Plain Guide Service',
    state: 'North Carolina',
    stateCode: 'NC',
    city: 'Kinston',
    species: ['Whitetail', 'Turkey', 'Waterfowl'],
    methods: ['Rifle', 'Shotgun', 'Bow'],
    experience: '14+ years',
    description: 'Guides hunts in the swamps and bottomlands of eastern North Carolina where deer densities are among the highest in the state.',
    phone: '(555) 307-6252',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 33,
  },
  {
    id: 223,
    name: 'Shane Locklear',
    businessName: 'Tar Heel Outfitters',
    state: 'North Carolina',
    stateCode: 'NC',
    city: 'Lumberton',
    species: ['Whitetail', 'Turkey', 'Bear'],
    methods: ['Bow', 'Rifle', 'Crossbow'],
    experience: '16+ years',
    description: 'Offers guided hunts on private timber company land in the Sandhills region with comfortable lodge accommodations.',
    phone: '(555) 307-6373',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 41,
  },

  // ============================================================
  // North Dakota (ND)
  // ============================================================
  {
    id: 224,
    name: 'Jesse Strand',
    businessName: 'Prairie Edge Outfitters',
    state: 'North Dakota',
    stateCode: 'ND',
    city: 'Bismarck',
    species: ['Whitetail', 'Mule Deer'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '18+ years',
    description: 'Hunts the Missouri River breaks where whitetails and mule deer share habitat in rugged badlands terrain.',
    phone: '(555) 308-7010',
    email: 'jesse@prairieedge.com',
    website: 'https://prairieedgeoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 64,
  },
  {
    id: 225,
    name: 'Ryan Knutson',
    businessName: 'Badlands Whitetail Co.',
    state: 'North Dakota',
    stateCode: 'ND',
    city: 'Dickinson',
    species: ['Whitetail', 'Mule Deer', 'Antelope'],
    methods: ['Rifle', 'Bow'],
    experience: '12+ years',
    description: 'Guides trophy whitetail and mule deer hunts in the scenic western North Dakota badlands.',
    phone: '(555) 308-7131',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 37,
  },
  {
    id: 226,
    name: 'Adam Thorson',
    businessName: 'Dakota Prairie Hunts',
    state: 'North Dakota',
    stateCode: 'ND',
    city: 'Jamestown',
    species: ['Whitetail', 'Waterfowl'],
    methods: ['Rifle', 'Shotgun', 'Bow'],
    experience: '15+ years',
    description: 'Offers combination whitetail and waterfowl hunts on the fertile prairies of central North Dakota.',
    phone: '(555) 308-7252',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 45,
  },

  // ============================================================
  // Ohio (OH)
  // ============================================================
  {
    id: 227,
    name: 'Greg Dennison',
    businessName: 'Buckeye Whitetail Outfitters',
    state: 'Ohio',
    stateCode: 'OH',
    city: 'Coshocton',
    species: ['Whitetail'],
    methods: ['Bow', 'Crossbow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Runs a premiere whitetail operation in east-central Ohio, consistently producing Pope and Young caliber bucks.',
    phone: '(555) 309-8010',
    email: 'greg@buckeyewhitetail.com',
    website: 'https://buckeyewhitetailoutfitters.com',
    priceRange: '$$$$',
    buckStopPartner: true,
    rating: 4.9,
    reviewCount: 134,
  },
  {
    id: 228,
    name: 'Tony Vitale',
    businessName: 'Ohio River Valley Hunts',
    state: 'Ohio',
    stateCode: 'OH',
    city: 'Marietta',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Crossbow', 'Shotgun'],
    experience: '15+ years',
    description: 'Guides hunts along the Ohio River bluffs where oak-hickory ridges hold heavy-racked whitetails.',
    phone: '(555) 309-8131',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 57,
  },
  {
    id: 229,
    name: 'Mark Lautenschleger',
    businessName: 'Heartland Bow Hunts',
    state: 'Ohio',
    stateCode: 'OH',
    city: 'Mount Vernon',
    species: ['Whitetail'],
    methods: ['Bow', 'Crossbow'],
    experience: '18+ years',
    description: 'Archery-only outfitter managing small, low-pressure farms in Knox County for quality bow-hunting experiences.',
    phone: '(555) 309-8252',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 48,
  },
  {
    id: 230,
    name: 'Chris Dillon',
    businessName: 'Southeast Ohio Outfitters',
    state: 'Ohio',
    stateCode: 'OH',
    city: 'McConnelsville',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader', 'Shotgun'],
    experience: '12+ years',
    description: 'Hunts the steep hollows and ridges of Appalachian Ohio where public land borders managed private ground.',
    phone: '(555) 309-8373',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.3,
    reviewCount: 22,
  },

  // ============================================================
  // Oklahoma (OK)
  // ============================================================
  {
    id: 231,
    name: 'Wade Barnett',
    businessName: 'Cross Timbers Outfitters',
    state: 'Oklahoma',
    stateCode: 'OK',
    city: 'McAlester',
    species: ['Whitetail', 'Turkey', 'Hog'],
    methods: ['Bow', 'Rifle', 'Crossbow'],
    experience: '20+ years',
    description: 'Hunts the Cross Timbers region of southeastern Oklahoma where post oak forests hold big whitetails and abundant hogs.',
    phone: '(555) 310-9010',
    email: 'wade@crosstimbersoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 59,
  },
  {
    id: 232,
    name: 'Dustin Cloud',
    businessName: 'Oklahoma Trophy Whitetails',
    state: 'Oklahoma',
    stateCode: 'OK',
    city: 'Durant',
    species: ['Whitetail', 'Hog'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '14+ years',
    description: 'Manages food plots and trail camera surveys to target mature bucks in the Red River bottom country.',
    phone: '(555) 310-9131',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 32,
  },
  {
    id: 233,
    name: 'Brett Rowland',
    businessName: 'Sooner State Guide Service',
    state: 'Oklahoma',
    stateCode: 'OK',
    city: 'Ponca City',
    species: ['Whitetail', 'Turkey', 'Waterfowl'],
    methods: ['Rifle', 'Shotgun', 'Bow'],
    experience: '16+ years',
    description: 'Offers multi-species hunts across north-central Oklahoma prairies and creek bottoms.',
    phone: '(555) 310-9252',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 40,
  },

  // ============================================================
  // Oregon (OR)
  // ============================================================
  {
    id: 234,
    name: 'Tyler Meeks',
    businessName: 'Cascade Range Outfitters',
    state: 'Oregon',
    stateCode: 'OR',
    city: 'Bend',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '22+ years',
    description: 'Guides backcountry elk hunts in the Cascade Range with horseback access to remote high-country basins.',
    phone: '(555) 311-1010',
    email: 'tyler@cascaderangeoutfitters.com',
    website: 'https://cascaderangeoutfitters.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 91,
  },
  {
    id: 235,
    name: 'Nick Schultz',
    businessName: 'Blue Mountain Guide Co.',
    state: 'Oregon',
    stateCode: 'OR',
    city: 'La Grande',
    species: ['Elk', 'Mule Deer', 'Bear', 'Whitetail'],
    methods: ['Rifle', 'Bow'],
    experience: '18+ years',
    description: 'Hunts the Blue Mountains of northeast Oregon where Roosevelt and Rocky Mountain elk overlap with whitetail range.',
    phone: '(555) 311-1131',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 55,
  },
  {
    id: 236,
    name: 'Darren Isaacs',
    businessName: 'Coast Range Bear Hunts',
    state: 'Oregon',
    stateCode: 'OR',
    city: 'Roseburg',
    species: ['Bear', 'Elk'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'Specializes in spring and fall black bear hunts in the dense timber of the Oregon Coast Range.',
    phone: '(555) 311-1252',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 34,
  },
  {
    id: 237,
    name: 'Patrick Riggs',
    businessName: 'High Desert Hunts Oregon',
    state: 'Oregon',
    stateCode: 'OR',
    city: 'Burns',
    species: ['Mule Deer', 'Antelope'],
    methods: ['Rifle', 'Bow'],
    experience: '12+ years',
    description: 'Guides spot-and-stalk mule deer and antelope hunts on the wide-open sagebrush flats of Harney County.',
    phone: '(555) 311-1373',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 26,
  },

  // ============================================================
  // Pennsylvania (PA)
  // ============================================================
  {
    id: 238,
    name: 'Joe Piekarski',
    businessName: 'Keystone Whitetail Hunts',
    state: 'Pennsylvania',
    stateCode: 'PA',
    city: 'Wellsboro',
    species: ['Whitetail', 'Bear', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '25+ years',
    description: 'Hunts the big woods of Potter and Tioga Counties, legendary territory for Keystone State trophy bucks.',
    phone: '(555) 312-2010',
    email: 'joe@keystonewhitetail.com',
    website: 'https://keystonewhitetailhunts.com',
    priceRange: '$$$',
    buckStopPartner: true,
    rating: 4.8,
    reviewCount: 103,
  },
  {
    id: 239,
    name: 'Rich Sterner',
    businessName: 'PA Mountain Outfitters',
    state: 'Pennsylvania',
    stateCode: 'PA',
    city: 'State College',
    species: ['Whitetail', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '18+ years',
    description: 'Guides hunts in the ridge-and-valley terrain of central Pennsylvania where bear populations have surged.',
    phone: '(555) 312-2131',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 47,
  },
  {
    id: 240,
    name: 'Eric Shultz',
    businessName: 'Allegheny Highlands Guide Service',
    state: 'Pennsylvania',
    stateCode: 'PA',
    city: 'Bradford',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Crossbow'],
    experience: '14+ years',
    description: 'Operates on managed timber leases in the Allegheny National Forest region for a true big-woods hunting experience.',
    phone: '(555) 312-2252',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 31,
  },
  {
    id: 241,
    name: 'Andy Klinefelter',
    businessName: 'Lancaster County Whitetails',
    state: 'Pennsylvania',
    stateCode: 'PA',
    city: 'Lititz',
    species: ['Whitetail'],
    methods: ['Bow', 'Crossbow', 'Muzzleloader'],
    experience: '12+ years',
    description: 'Hunts the fertile farmland of Lancaster County where corn-fed whitetails regularly break the 150-inch mark.',
    phone: '(555) 312-2373',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 42,
  },

  // ============================================================
  // Rhode Island (RI)
  // ============================================================
  {
    id: 242,
    name: 'Scott Medeiros',
    businessName: 'Ocean State Hunting',
    state: 'Rhode Island',
    stateCode: 'RI',
    city: 'Exeter',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Shotgun', 'Muzzleloader'],
    experience: '15+ years',
    description: 'Guides whitetail and turkey hunts on private land in rural western Rhode Island where deer densities are surprisingly high.',
    phone: '(555) 313-3010',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.3,
    reviewCount: 12,
  },
  {
    id: 243,
    name: 'Kevin Traficante',
    businessName: 'Little Rhody Outfitters',
    state: 'Rhode Island',
    stateCode: 'RI',
    city: 'West Greenwich',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Shotgun'],
    experience: '10+ years',
    description: 'Manages small private parcels for quality deer management in the smallest state, proving big bucks live everywhere.',
    phone: '(555) 313-3131',
    priceRange: '$',
    buckStopPartner: false,
    rating: 4.1,
    reviewCount: 8,
  },

  // ============================================================
  // South Carolina (SC)
  // ============================================================
  {
    id: 244,
    name: 'Hank Simmons',
    businessName: 'Lowcountry Outfitters',
    state: 'South Carolina',
    stateCode: 'SC',
    city: 'Walterboro',
    species: ['Whitetail', 'Turkey', 'Hog'],
    methods: ['Rifle', 'Bow', 'Shotgun'],
    experience: '20+ years',
    description: 'Hunts the ACE Basin and surrounding Lowcountry swamps where deer and hog populations are dense year-round.',
    phone: '(555) 314-4010',
    email: 'hank@lowcountryoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 62,
  },
  {
    id: 245,
    name: 'Travis McMillan',
    businessName: 'Palmetto Guide Service',
    state: 'South Carolina',
    stateCode: 'SC',
    city: 'Florence',
    species: ['Whitetail', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Crossbow'],
    experience: '14+ years',
    description: 'Operates on private Pee Dee region farmland with managed food plots and year-round trail camera surveillance.',
    phone: '(555) 314-4131',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 35,
  },
  {
    id: 246,
    name: 'Clint Hubbard',
    businessName: 'Upstate Trophy Hunts',
    state: 'South Carolina',
    stateCode: 'SC',
    city: 'Pickens',
    species: ['Whitetail', 'Bear', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '16+ years',
    description: 'Guides in the Blue Ridge foothills of upstate South Carolina where mountain whitetails and bears roam.',
    phone: '(555) 314-4252',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 29,
  },

  // ============================================================
  // South Dakota (SD)
  // ============================================================
  {
    id: 247,
    name: 'Brent Paulson',
    businessName: 'Black Hills Outfitters',
    state: 'South Dakota',
    stateCode: 'SD',
    city: 'Rapid City',
    species: ['Whitetail', 'Mule Deer', 'Elk'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '22+ years',
    description: 'Hunts the Black Hills and surrounding prairie breaks for trophy whitetails and mule deer on private ranches.',
    phone: '(555) 315-5010',
    email: 'brent@blackhillsoutfitters.com',
    website: 'https://blackhillsoutfitterssd.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 73,
  },
  {
    id: 248,
    name: 'Cole Jensen',
    businessName: 'Missouri River Hunts',
    state: 'South Dakota',
    stateCode: 'SD',
    city: 'Pierre',
    species: ['Whitetail', 'Mule Deer'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'Guides hunts along the Missouri River breaks where the Great Plains meet timbered creek bottoms.',
    phone: '(555) 315-5131',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 41,
  },
  {
    id: 249,
    name: 'Derek Engel',
    businessName: 'Dakota Grassland Outfitters',
    state: 'South Dakota',
    stateCode: 'SD',
    city: 'Chamberlain',
    species: ['Whitetail', 'Turkey', 'Waterfowl'],
    methods: ['Rifle', 'Shotgun', 'Bow'],
    experience: '18+ years',
    description: 'Offers combination hunts for river-bottom whitetails and prairie waterfowl during the fall migration.',
    phone: '(555) 315-5252',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 50,
  },

  // ============================================================
  // Tennessee (TN)
  // ============================================================
  {
    id: 250,
    name: 'Daryl Compton',
    businessName: 'Tennessee Valley Outfitters',
    state: 'Tennessee',
    stateCode: 'TN',
    city: 'Clarksville',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Hunts the fertile river-bottom farms of the Cumberland River valley for big-framed Tennessee whitetails.',
    phone: '(555) 316-6010',
    email: 'daryl@tennesseevalley.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 67,
  },
  {
    id: 251,
    name: 'Keith Dockery',
    businessName: 'Smoky Mountain Outfitters',
    state: 'Tennessee',
    stateCode: 'TN',
    city: 'Maryville',
    species: ['Bear', 'Whitetail', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '18+ years',
    description: 'Specializes in black bear hunts in the foothills of the Great Smoky Mountains with an 85% success rate.',
    phone: '(555) 316-6131',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 53,
  },
  {
    id: 252,
    name: 'Shane Atkins',
    businessName: 'West Tennessee Whitetails',
    state: 'Tennessee',
    stateCode: 'TN',
    city: 'Jackson',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Crossbow'],
    experience: '14+ years',
    description: 'Operates on private timber and agricultural land in the flatlands of west Tennessee where trophy genetics run deep.',
    phone: '(555) 316-6252',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 36,
  },
  {
    id: 253,
    name: 'Jason Presley',
    businessName: 'Volunteer State Guide Service',
    state: 'Tennessee',
    stateCode: 'TN',
    city: 'Crossville',
    species: ['Whitetail', 'Bear', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Shotgun'],
    experience: '16+ years',
    description: 'Guides hunts on the Cumberland Plateau where mixed hardwood forests support healthy deer, bear, and turkey populations.',
    phone: '(555) 316-6373',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 40,
  },

  // ============================================================
  // Texas (TX) - 5 guides
  // ============================================================
  {
    id: 254,
    name: 'Colton McCready',
    businessName: 'South Texas Trophy Ranch',
    state: 'Texas',
    stateCode: 'TX',
    city: 'Laredo',
    species: ['Whitetail'],
    methods: ['Rifle', 'Bow', 'Crossbow'],
    experience: '25+ years',
    description: 'Runs a premier high-fence trophy whitetail operation in the famous south Texas brush country with all-inclusive packages.',
    phone: '(555) 317-7010',
    email: 'colton@southtexastrophyranch.com',
    website: 'https://southtexastrophyranch.com',
    priceRange: '$$$$',
    buckStopPartner: true,
    rating: 4.9,
    reviewCount: 148,
  },
  {
    id: 255,
    name: 'Trey Sullivan',
    businessName: 'Hill Country Outfitters',
    state: 'Texas',
    stateCode: 'TX',
    city: 'Llano',
    species: ['Whitetail', 'Turkey', 'Hog'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Guides hunts across the Edwards Plateau where limestone hills and live oak groves produce excellent free-range whitetails.',
    phone: '(555) 317-7131',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: 256,
    name: 'Miguel Garza',
    businessName: 'Brush Country Guide Service',
    state: 'Texas',
    stateCode: 'TX',
    city: 'Uvalde',
    species: ['Whitetail', 'Hog', 'Turkey'],
    methods: ['Rifle', 'Bow'],
    experience: '18+ years',
    description: 'Specializes in fair-chase hunts on low-fence ranches in the brush country with year-round hog hunting packages.',
    phone: '(555) 317-7252',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 56,
  },
  {
    id: 257,
    name: 'Cole Henderson',
    businessName: 'West Texas Mule Deer Hunts',
    state: 'Texas',
    stateCode: 'TX',
    city: 'Fort Stockton',
    species: ['Mule Deer', 'Hog', 'Predator'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'Hunts the Trans-Pecos region of far west Texas for trophy mule deer on vast desert mountain ranches.',
    phone: '(555) 317-7373',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 43,
  },
  {
    id: 258,
    name: 'Ray Hobbs',
    businessName: 'East Texas Sportsman',
    state: 'Texas',
    stateCode: 'TX',
    city: 'Nacogdoches',
    species: ['Whitetail', 'Hog', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Shotgun', 'Crossbow'],
    experience: '22+ years',
    description: 'Guides hunts in the Piney Woods of east Texas where tall timber and creek bottoms hold big whitetails and plentiful hogs.',
    phone: '(555) 317-7494',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 61,
  },

  // ============================================================
  // Utah (UT)
  // ============================================================
  {
    id: 259,
    name: 'Tanner Olsen',
    businessName: 'Wasatch Outfitters',
    state: 'Utah',
    stateCode: 'UT',
    city: 'Heber City',
    species: ['Elk', 'Mule Deer'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Guides elk and mule deer hunts in the Wasatch Mountains with access to limited-entry units known for trophy bulls.',
    phone: '(555) 318-8010',
    email: 'tanner@wasatchoutfitters.com',
    website: 'https://wasatchoutfitters.com',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 95,
  },
  {
    id: 260,
    name: 'Jason Syme',
    businessName: 'Book Cliffs Guide Service',
    state: 'Utah',
    stateCode: 'UT',
    city: 'Vernal',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '16+ years',
    description: 'Hunts the rugged Book Cliffs and Uinta Basin for trophy elk on some of Utah\'s most coveted limited-entry permits.',
    phone: '(555) 318-8131',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 58,
  },
  {
    id: 261,
    name: 'Brett Stanger',
    businessName: 'Southern Utah Hunts',
    state: 'Utah',
    stateCode: 'UT',
    city: 'Cedar City',
    species: ['Mule Deer', 'Elk', 'Antelope'],
    methods: ['Rifle', 'Muzzleloader', 'Bow'],
    experience: '14+ years',
    description: 'Specializes in Paunsaugunt and Zion unit mule deer hunts in the red rock country of southern Utah.',
    phone: '(555) 318-8252',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 44,
  },
  {
    id: 262,
    name: 'Cory Westwood',
    businessName: 'Beehive State Outfitters',
    state: 'Utah',
    stateCode: 'UT',
    city: 'Richfield',
    species: ['Elk', 'Mule Deer'],
    methods: ['Rifle', 'Bow'],
    experience: '12+ years',
    description: 'Guides hunts in the Fishlake and Monroe Mountain units where high-altitude aspen forests hold impressive bull elk.',
    phone: '(555) 318-8373',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 30,
  },

  // ============================================================
  // Vermont (VT)
  // ============================================================
  {
    id: 263,
    name: 'Nate Ferris',
    businessName: 'Green Mountain Guide Service',
    state: 'Vermont',
    stateCode: 'VT',
    city: 'Rutland',
    species: ['Whitetail', 'Bear', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '18+ years',
    description: 'Guides hunts through the Green Mountain National Forest where mixed hardwoods support healthy deer and bear populations.',
    phone: '(555) 319-9010',
    email: 'nate@greenmtnguide.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 33,
  },
  {
    id: 264,
    name: 'Will Provost',
    businessName: 'Northeast Kingdom Hunts',
    state: 'Vermont',
    stateCode: 'VT',
    city: 'St. Johnsbury',
    species: ['Whitetail', 'Bear', 'Moose'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'Operates in Vermont\'s remote Northeast Kingdom where big woods bucks and occasional moose permits make for unforgettable hunts.',
    phone: '(555) 319-9131',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 24,
  },
  {
    id: 265,
    name: 'Luke Charlebois',
    businessName: 'Champlain Valley Outfitters',
    state: 'Vermont',
    stateCode: 'VT',
    city: 'Middlebury',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Shotgun'],
    experience: '12+ years',
    description: 'Hunts the agricultural Champlain Valley where open fields and hedgerows produce some of Vermont\'s biggest bucks.',
    phone: '(555) 319-9252',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.3,
    reviewCount: 18,
  },

  // ============================================================
  // Virginia (VA)
  // ============================================================
  {
    id: 266,
    name: 'Nathan Mays',
    businessName: 'Shenandoah Valley Outfitters',
    state: 'Virginia',
    stateCode: 'VA',
    city: 'Staunton',
    species: ['Whitetail', 'Bear', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '22+ years',
    description: 'Hunts the ridges and valleys of the Shenandoah where agricultural bottoms border national forest land.',
    phone: '(555) 320-1010',
    email: 'nathan@shenandoahvalleyoutfitters.com',
    website: 'https://shenandoahvalleyoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: true,
    rating: 4.8,
    reviewCount: 88,
  },
  {
    id: 267,
    name: 'Alan Pratt',
    businessName: 'Blue Ridge Hunts',
    state: 'Virginia',
    stateCode: 'VA',
    city: 'Bedford',
    species: ['Whitetail', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '16+ years',
    description: 'Guides in the Blue Ridge Mountains with a focus on mature mountain whitetails and fall bear hunts.',
    phone: '(555) 320-1131',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 45,
  },
  {
    id: 268,
    name: 'Chris Stiltner',
    businessName: 'Southwest Virginia Guide Co.',
    state: 'Virginia',
    stateCode: 'VA',
    city: 'Abingdon',
    species: ['Whitetail', 'Turkey', 'Bear'],
    methods: ['Rifle', 'Bow', 'Shotgun'],
    experience: '18+ years',
    description: 'Operates in the Appalachian highlands of far southwest Virginia where long seasons and liberal bag limits provide excellent opportunities.',
    phone: '(555) 320-1252',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 51,
  },
  {
    id: 269,
    name: 'Robert Lyle',
    businessName: 'Tidewater Whitetails',
    state: 'Virginia',
    stateCode: 'VA',
    city: 'Williamsburg',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Crossbow', 'Muzzleloader'],
    experience: '14+ years',
    description: 'Hunts the Tidewater region\'s swamp edges and agricultural fields where mild winters grow heavy-antlered bucks.',
    phone: '(555) 320-1373',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 37,
  },

  // ============================================================
  // Washington (WA)
  // ============================================================
  {
    id: 270,
    name: 'Jason Culp',
    businessName: 'Olympic Peninsula Outfitters',
    state: 'Washington',
    stateCode: 'WA',
    city: 'Sequim',
    species: ['Elk', 'Bear', 'Whitetail'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Guides Roosevelt elk and black bear hunts in the temperate rainforests and alpine meadows of the Olympic Peninsula.',
    phone: '(555) 321-2010',
    email: 'jason@olympicoutfitters.com',
    website: 'https://olympicpeninsulaoutfitters.com',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 72,
  },
  {
    id: 271,
    name: 'Matt Vanderpool',
    businessName: 'Eastern Washington Guide Service',
    state: 'Washington',
    stateCode: 'WA',
    city: 'Ellensburg',
    species: ['Elk', 'Mule Deer', 'Whitetail'],
    methods: ['Rifle', 'Bow'],
    experience: '16+ years',
    description: 'Hunts the shrub-steppe and timbered canyons of eastern Washington where Rocky Mountain elk and mule deer thrive.',
    phone: '(555) 321-2131',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 44,
  },
  {
    id: 272,
    name: 'Kevin Moberg',
    businessName: 'Cascade Foothills Hunts',
    state: 'Washington',
    stateCode: 'WA',
    city: 'Wenatchee',
    species: ['Mule Deer', 'Elk', 'Bear'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '18+ years',
    description: 'Specializes in backcountry mule deer and elk hunts in the eastern Cascade foothills with pack-in spike camps.',
    phone: '(555) 321-2252',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 52,
  },
  {
    id: 273,
    name: 'Dale Erikson',
    businessName: 'Palouse Country Outfitters',
    state: 'Washington',
    stateCode: 'WA',
    city: 'Pullman',
    species: ['Whitetail', 'Turkey', 'Bear'],
    methods: ['Rifle', 'Bow', 'Shotgun'],
    experience: '14+ years',
    description: 'Guides whitetail and turkey hunts in the rolling wheat fields and timbered creek draws of the Palouse region.',
    phone: '(555) 321-2373',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 31,
  },

  // ============================================================
  // West Virginia (WV)
  // ============================================================
  {
    id: 274,
    name: 'Earl Bragg',
    businessName: 'Mountain State Outfitters',
    state: 'West Virginia',
    stateCode: 'WV',
    city: 'Elkins',
    species: ['Whitetail', 'Bear', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '25+ years',
    description: 'Hunts the rugged Allegheny highlands where steep hollows and remote ridges shelter mature bucks and a booming bear population.',
    phone: '(555) 322-3010',
    email: 'earl@mountainstateoutfitters.com',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 65,
  },
  {
    id: 275,
    name: 'Cody Harper',
    businessName: 'New River Gorge Hunts',
    state: 'West Virginia',
    stateCode: 'WV',
    city: 'Fayetteville',
    species: ['Whitetail', 'Bear'],
    methods: ['Rifle', 'Bow', 'Crossbow'],
    experience: '15+ years',
    description: 'Guides hunts along the New River Gorge where hardwood ridges and laurel thickets hold heavy-bodied Appalachian whitetails.',
    phone: '(555) 322-3131',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 38,
  },
  {
    id: 276,
    name: 'Tim Cutlip',
    businessName: 'Potomac Highlands Guide Service',
    state: 'West Virginia',
    stateCode: 'WV',
    city: 'Moorefield',
    species: ['Whitetail', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Shotgun', 'Muzzleloader'],
    experience: '18+ years',
    description: 'Operates on private farms in the South Branch Potomac Valley where fertile agricultural ground grows impressive whitetails.',
    phone: '(555) 322-3252',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 29,
  },

  // ============================================================
  // Wisconsin (WI) - 5 guides
  // ============================================================
  {
    id: 277,
    name: 'Mike Shaughnessy',
    businessName: 'Wisconsin Trophy Whitetails',
    state: 'Wisconsin',
    stateCode: 'WI',
    city: 'Buffalo County',
    species: ['Whitetail'],
    methods: ['Bow', 'Rifle', 'Crossbow', 'Muzzleloader'],
    experience: '25+ years',
    description: 'Operates in legendary Buffalo County, consistently one of the top counties in the nation for Boone and Crockett whitetails.',
    phone: '(555) 323-4010',
    email: 'mike@witrophywhitetails.com',
    website: 'https://wisconsintrophywhitetails.com',
    priceRange: '$$$$',
    buckStopPartner: true,
    rating: 4.9,
    reviewCount: 142,
  },
  {
    id: 278,
    name: 'Pete Warzynski',
    businessName: 'Northwoods Bear & Deer',
    state: 'Wisconsin',
    stateCode: 'WI',
    city: 'Rhinelander',
    species: ['Bear', 'Whitetail'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Guides bear hunts over bait in the northwoods and November whitetail hunts in the big timber of Oneida County.',
    phone: '(555) 323-4131',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.7,
    reviewCount: 78,
  },
  {
    id: 279,
    name: 'Aaron Breunig',
    businessName: 'Driftless Region Outfitters',
    state: 'Wisconsin',
    stateCode: 'WI',
    city: 'Viroqua',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Crossbow'],
    experience: '18+ years',
    description: 'Hunts the steep coulees and ridge-top food plots of the Driftless Area where giant whitetails are the norm.',
    phone: '(555) 323-4252',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 86,
  },
  {
    id: 280,
    name: 'Dan Kumm',
    businessName: 'Central Wisconsin Hunts',
    state: 'Wisconsin',
    stateCode: 'WI',
    city: 'Wausau',
    species: ['Whitetail', 'Bear', 'Turkey'],
    methods: ['Rifle', 'Bow', 'Shotgun'],
    experience: '15+ years',
    description: 'Offers guided whitetail, bear, and turkey hunts on managed private land in Marathon County.',
    phone: '(555) 323-4373',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 47,
  },
  {
    id: 281,
    name: 'Scott Erickson',
    businessName: 'Badger State Outfitters',
    state: 'Wisconsin',
    stateCode: 'WI',
    city: 'Prairie du Chien',
    species: ['Whitetail', 'Turkey'],
    methods: ['Bow', 'Rifle', 'Muzzleloader'],
    experience: '12+ years',
    description: 'Guides hunts on the Mississippi River bluffs and bottomlands of Crawford County, a perennial trophy hotspot.',
    phone: '(555) 323-4494',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.6,
    reviewCount: 53,
  },

  // ============================================================
  // Wyoming (WY)
  // ============================================================
  {
    id: 282,
    name: 'Clay Buchanan',
    businessName: 'Wind River Outfitters',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Dubois',
    species: ['Elk', 'Mule Deer', 'Antelope', 'Moose'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '30+ years',
    description: 'Runs wilderness horseback hunts in the Wind River Range and Absaroka Mountains for trophy elk and mule deer.',
    phone: '(555) 324-5010',
    email: 'clay@windriveroutfitters.com',
    website: 'https://windriveroutfitters.com',
    priceRange: '$$$$',
    buckStopPartner: true,
    rating: 5.0,
    reviewCount: 126,
  },
  {
    id: 283,
    name: 'Garrett Shaw',
    businessName: 'Bighorn Basin Hunts',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Cody',
    species: ['Elk', 'Mule Deer', 'Bear'],
    methods: ['Rifle', 'Bow'],
    experience: '22+ years',
    description: 'Guides hunts on the eastern slope of the Absarokas near Yellowstone where bull elk congregate during the rut.',
    phone: '(555) 324-5131',
    priceRange: '$$$',
    buckStopPartner: false,
    rating: 4.8,
    reviewCount: 94,
  },
  {
    id: 284,
    name: 'Travis Pfister',
    businessName: 'Thunder Basin Outfitters',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Gillette',
    species: ['Antelope', 'Mule Deer', 'Whitetail'],
    methods: ['Rifle', 'Bow'],
    experience: '15+ years',
    description: 'Specializes in antelope and mule deer hunts on the vast grasslands and sagebrush prairies of the Powder River Basin.',
    phone: '(555) 324-5252',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.5,
    reviewCount: 48,
  },
  {
    id: 285,
    name: 'Wyatt Jensen',
    businessName: 'Snake River Outfitters',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Jackson',
    species: ['Elk', 'Mule Deer', 'Moose'],
    methods: ['Rifle', 'Bow', 'Muzzleloader'],
    experience: '20+ years',
    description: 'Operates in the Bridger-Teton National Forest with access to premier wilderness areas near Grand Teton National Park.',
    phone: '(555) 324-5373',
    priceRange: '$$$$',
    buckStopPartner: false,
    rating: 4.9,
    reviewCount: 109,
  },
  {
    id: 286,
    name: 'Luke Heward',
    businessName: 'Red Desert Guide Co.',
    state: 'Wyoming',
    stateCode: 'WY',
    city: 'Rock Springs',
    species: ['Antelope', 'Mule Deer', 'Elk'],
    methods: ['Rifle', 'Bow'],
    experience: '12+ years',
    description: 'Guides hunts in the Red Desert and Wyoming Range where wide-open country holds strong antelope and mule deer herds.',
    phone: '(555) 324-5494',
    priceRange: '$$',
    buckStopPartner: false,
    rating: 4.4,
    reviewCount: 35,
  },
];
