// Buck Stop Lure Company - Southeast State Hunting Guide Data
// States: VA, WV, NC, SC, GA, FL, AL, MS

import type { StateHuntingGuide } from './state-hunting-guide';

export const southeastStates: StateHuntingGuide[] = [
  {
    stateCode: 'VA',
    stateName: 'Virginia',
    region: 'Southeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Ruffed Grouse', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
      { name: 'Bobcat', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Oct 5 - Nov 15 & Dec 1 - Jan 4' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 16 - Nov 30 (rifle)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Nov 2 - Nov 15 (early) & Dec 7 - Jan 4 (late)' },
    ],
    licenseInfo: {
      residentBase: '$23',
      nonResidentBase: '$110',
      deerTagResident: 'Included',
      deerTagNonResident: 'Included',
      youthPrograms: 'Junior license ages 12-15; apprentice license',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Earn-a-Buck in some counties',
      bagLimit: '3 antlered per season; varies by county for antlerless',
      blazeOrange: 'Required during firearm season (blaze orange or pink)',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed on private and public land',
      crossbowDuringArchery: true,
    },
    agencyName: 'Virginia Dept. of Wildlife Resources',
    agencyUrl: 'https://dwr.virginia.gov',
  },
  {
    stateCode: 'WV',
    stateName: 'West Virginia',
    region: 'Southeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Ruffed Grouse', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 28 - Dec 31' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 25 - Dec 8 (buck) & Dec 9 - Dec 31 (antlerless)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Dec 16 - Dec 31' },
    ],
    licenseInfo: {
      residentBase: '$19',
      nonResidentBase: '$119',
      deerTagResident: 'Included',
      deerTagNonResident: 'Included',
      youthPrograms: 'Class Y license for under 18; youth hunting days',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'None statewide',
      bagLimit: '3 per season (1 buck, 2 antlerless typical)',
      blazeOrange: 'Required during gun season (400 sq in)',
      baiting: 'Permitted in some counties',
      sundayHunting: 'Prohibited on public land',
      crossbowDuringArchery: true,
    },
    agencyName: 'West Virginia DNR',
    agencyUrl: 'https://wvdnr.gov',
  },
  {
    stateCode: 'NC',
    stateName: 'North Carolina',
    region: 'Southeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Feral Hog', category: 'other' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 14 - Oct 25' },
      { type: 'firearm', species: 'Deer', dateRange: 'Oct 12 - Jan 1 (varies by zone)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Oct 5 - Oct 11 & Jan 2 - Jan 11' },
    ],
    licenseInfo: {
      residentBase: '$25',
      nonResidentBase: '$100',
      deerTagResident: 'Included',
      deerTagNonResident: 'Included',
      youthPrograms: 'Free for under 16; youth deer hunting days',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: '2 points on one side or 10-inch spread',
      bagLimit: '6 deer per season (2 antlered in most counties)',
      blazeOrange: 'Required during gun season',
      baiting: 'Prohibited on public lands',
      sundayHunting: 'Allowed on private land (firearms and archery)',
      crossbowDuringArchery: true,
    },
    agencyName: 'North Carolina Wildlife Resources Commission',
    agencyUrl: 'https://www.ncwildlife.org',
  },
  {
    stateCode: 'SC',
    stateName: 'South Carolina',
    region: 'Southeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Feral Hog', category: 'other' },
      { name: 'Coyote', category: 'predator' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Aug 15 - Jan 1 (varies by Game Zone)' },
      { type: 'firearm', species: 'Deer', dateRange: 'Oct 11 - Jan 1 (varies by Game Zone)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Oct 1 - Oct 10' },
    ],
    licenseInfo: {
      residentBase: '$12',
      nonResidentBase: '$125',
      deerTagResident: '$5 per tag',
      deerTagNonResident: '$5 per tag',
      youthPrograms: 'Free for under 16; youth deer hunts on WMAs',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'None statewide (4-point rule in some Game Zones)',
      bagLimit: 'No limit on antlerless on private land in most zones; 5 total in some zones',
      blazeOrange: 'Not required (strongly recommended)',
      baiting: 'Allowed on private land',
      sundayHunting: 'Allowed on private land',
      crossbowDuringArchery: true,
    },
    agencyName: 'South Carolina Dept. of Natural Resources',
    agencyUrl: 'https://www.dnr.sc.gov',
  },
  {
    stateCode: 'GA',
    stateName: 'Georgia',
    region: 'Southeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Feral Hog', category: 'other' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 13 - Oct 10' },
      { type: 'firearm', species: 'Deer', dateRange: 'Oct 18 - Jan 11 (varies by zone)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Oct 11 - Oct 17 (primitive weapons)' },
    ],
    licenseInfo: {
      residentBase: '$15',
      nonResidentBase: '$100',
      deerTagResident: 'Included',
      deerTagNonResident: 'Included',
      youthPrograms: 'Free for under 16; youth season weekends',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: '4 points on one side on most WMAs',
      bagLimit: '10 antlered per season; 10 antlerless per season',
      blazeOrange: 'Required during gun seasons (500 sq in above waist)',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Georgia DNR Wildlife Resources Division',
    agencyUrl: 'https://georgiawildlife.com',
  },
  {
    stateCode: 'FL',
    stateName: 'Florida',
    region: 'Southeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Feral Hog', category: 'other' },
      { name: 'Alligator', category: 'other' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Jul - Feb (varies by zone; typically Oct - Nov)' },
      { type: 'firearm', species: 'Deer', dateRange: 'Sep - Feb (varies widely by zone)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Nov - Dec (varies by zone)' },
    ],
    licenseInfo: {
      residentBase: '$17',
      nonResidentBase: '$151.50',
      deerTagResident: '$5 permit',
      deerTagNonResident: '$5 permit',
      youthPrograms: 'Free for under 16; youth hunts on WMAs',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: '1 antler with at least 5 inches above hairline in Zones C & D',
      bagLimit: '2 antlered per season; antlerless varies by zone',
      blazeOrange: 'Required on WMAs during general gun season (500 sq in)',
      baiting: 'Prohibited on WMAs; allowed on private land',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Florida Fish & Wildlife Conservation Commission',
    agencyUrl: 'https://myfwc.com',
  },
  {
    stateCode: 'AL',
    stateName: 'Alabama',
    region: 'Southeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Feral Hog', category: 'other' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Oct 15 - Feb 10' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 18 - Feb 10' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Nov 13 - Nov 17' },
    ],
    licenseInfo: {
      residentBase: '$24.65',
      nonResidentBase: '$315',
      deerTagResident: 'Included',
      deerTagNonResident: 'Included',
      youthPrograms: 'Free for under 16; youth deer season weekend',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: '3 bucks per season; 1 must have 4+ points on one side in some counties',
      bagLimit: '3 antlered per season; 1 antlerless per day',
      blazeOrange: 'Required during gun season (144 sq in above waist or hat)',
      baiting: 'Allowed with bait privilege license ($15 resident / $51 non-resident)',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Alabama DCNR Wildlife & Freshwater Fisheries',
    agencyUrl: 'https://www.outdooralabama.com',
  },
  {
    stateCode: 'MS',
    stateName: 'Mississippi',
    region: 'Southeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Feral Hog', category: 'other' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 14 - Nov 22 & Dec 1 - Jan 31' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 23 - Dec 1 & Dec 16 - Jan 31 (varies by zone)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Nov 30 - Dec 15' },
    ],
    licenseInfo: {
      residentBase: '$15',
      nonResidentBase: '$300',
      deerTagResident: 'Included',
      deerTagNonResident: 'Included',
      youthPrograms: 'Free for under 16; youth deer season weekend',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Antler regulations apply: bucks must have hardened antlers',
      bagLimit: '3 antlered per season; 5 antlerless per season',
      blazeOrange: 'Required during gun season (500 sq in above waist)',
      baiting: 'Allowed',
      sundayHunting: 'Allowed on private land',
      crossbowDuringArchery: true,
    },
    agencyName: 'Mississippi Dept. of Wildlife, Fisheries & Parks',
    agencyUrl: 'https://www.mdwfp.com',
  },
];
