// Buck Stop Lure Company - Pacific West State Hunting Guide Data
// States: WA, OR, CA, AK, HI

import type { StateHuntingGuide } from './state-hunting-guide';

export const pacificStates: StateHuntingGuide[] = [
  {
    stateCode: 'WA',
    stateName: 'Washington',
    region: 'Pacific West',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Blacktail Deer', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Mountain Goat', category: 'big-game' },
      { name: 'Moose', category: 'big-game' },
      { name: 'Mountain Lion', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Grouse', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 1 - Sep 30 (early); varies by GMU' },
      { type: 'firearm', species: 'Deer', dateRange: 'Oct 11 - Nov (modern firearm; varies by GMU)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Nov - Dec (late season; varies by GMU)' },
      { type: 'general', species: 'Elk', dateRange: 'Sep - Nov (archery, modern, muzzleloader by GMU)' },
    ],
    licenseInfo: {
      residentBase: '$45.50 big game package',
      nonResidentBase: '$453 big game package',
      deerTagResident: 'Included in package',
      deerTagNonResident: 'Included in package',
      youthPrograms: 'Youth (under 16) reduced fees; mentored youth hunts',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Varies by GMU; 3-point minimum in some units',
      bagLimit: '1 deer per tag (general + special permits)',
      blazeOrange: 'Not required (recommended during modern firearm)',
      baiting: 'Banned statewide (effective 2025 for deer, elk, moose)',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: false,
    },
    agencyName: 'Washington Dept. of Fish & Wildlife',
    agencyUrl: 'https://wdfw.wa.gov',
  },
  {
    stateCode: 'OR',
    stateName: 'Oregon',
    region: 'Pacific West',
    species: [
      { name: 'Blacktail Deer', category: 'big-game' },
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Antelope', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Mountain Lion', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Grouse', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Aug 30 - Sep 28 (general archery)' },
      { type: 'firearm', species: 'Deer', dateRange: 'Oct 4 - Nov 7 (general rifle; varies by unit)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Nov (limited; controlled-hunt only)' },
    ],
    licenseInfo: {
      residentBase: '$33.50 sportsman package',
      nonResidentBase: '$166.50 hunting license',
      deerTagResident: '$29.50 general deer tag',
      deerTagNonResident: '$358.50 general deer tag',
      youthPrograms: 'Youth license (12-17) at reduced rates; mentored youth hunts',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Varies by unit; forked-horn or better in some areas',
      bagLimit: '1 deer per tag',
      blazeOrange: 'Not required (recommended)',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: false,
    },
    agencyName: 'Oregon Dept. of Fish & Wildlife',
    agencyUrl: 'https://www.dfw.state.or.us',
  },
  {
    stateCode: 'CA',
    stateName: 'California',
    region: 'Pacific West',
    species: [
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Blacktail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Wild Pig', category: 'big-game' },
      { name: 'Elk (Tule/Roosevelt)', category: 'big-game' },
      { name: 'Antelope', category: 'big-game' },
      { name: 'Bighorn Sheep', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Jul - Sep (A-zone archery; varies by zone)' },
      { type: 'firearm', species: 'Deer', dateRange: 'Sep - Nov (general rifle; varies by zone)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Oct - Nov (varies by zone)' },
      { type: 'general', species: 'Wild Pig', dateRange: 'Year-round' },
    ],
    licenseInfo: {
      residentBase: '$55.24',
      nonResidentBase: '$192.71',
      deerTagResident: '$34.41 deer tag (zone-specific)',
      deerTagNonResident: '$293.83 deer tag',
      youthPrograms: 'Junior license for under 16; free apprentice hunts',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Forked-horn or better for bucks (antlered deer)',
      bagLimit: '1 buck per tag; up to 2 tags max per year',
      blazeOrange: 'Not required',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: false,
    },
    agencyName: 'California Dept. of Fish & Wildlife',
    agencyUrl: 'https://wildlife.ca.gov',
  },
  {
    stateCode: 'AK',
    stateName: 'Alaska',
    region: 'Pacific West',
    species: [
      { name: 'Sitka Blacktail Deer', category: 'big-game' },
      { name: 'Moose', category: 'big-game' },
      { name: 'Caribou', category: 'big-game' },
      { name: 'Elk (Afognak Island)', category: 'big-game' },
      { name: 'Brown/Grizzly Bear', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Dall Sheep', category: 'big-game' },
      { name: 'Mountain Goat', category: 'big-game' },
      { name: 'Muskox', category: 'big-game' },
      { name: 'Bison', category: 'big-game' },
      { name: 'Ptarmigan', category: 'upland' },
      { name: 'Grouse', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Snowshoe Hare', category: 'small-game' },
    ],
    seasons: [
      { type: 'general', species: 'Deer (Sitka Blacktail)', dateRange: 'Aug 1 - Dec 31 (varies by GMU)' },
      { type: 'general', species: 'Moose', dateRange: 'Aug - Sep (varies by GMU)' },
      { type: 'general', species: 'Caribou', dateRange: 'Aug - Mar (varies by herd/GMU)' },
      { type: 'general', species: 'Brown Bear', dateRange: 'Sep - May (varies; draw + registration)' },
      { type: 'general', species: 'Dall Sheep', dateRange: 'Aug 10 - Sep 20 (varies by GMU)' },
    ],
    licenseInfo: {
      residentBase: '$45',
      nonResidentBase: '$160',
      deerTagResident: '$25 deer harvest ticket',
      deerTagNonResident: '$300 deer/small game tag',
      youthPrograms: 'No license required under 16; mentored hunts available',
      hunterEdRequired: false,
    },
    regulations: {
      antlerRestrictions: 'Varies by GMU and species',
      bagLimit: '2-5 deer per year (varies by GMU); 1 moose typical',
      blazeOrange: 'Not required',
      baiting: 'Prohibited for big game',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Alaska Dept. of Fish & Game',
    agencyUrl: 'https://www.adfg.alaska.gov',
  },
  {
    stateCode: 'HI',
    stateName: 'Hawaii',
    region: 'Pacific West',
    species: [
      { name: 'Axis Deer', category: 'big-game' },
      { name: 'Feral Pig', category: 'big-game' },
      { name: 'Mouflon Sheep', category: 'big-game' },
      { name: 'Feral Goat', category: 'big-game' },
      { name: 'Blacktail Deer (Lanai)', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Francolin', category: 'upland' },
      { name: 'Ring-necked Pheasant', category: 'upland' },
      { name: 'Chukar', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer/Pig', dateRange: 'Feb - Mar (varies by island and unit)' },
      { type: 'firearm', species: 'Deer/Pig', dateRange: 'Mar - Jun (varies by island and unit)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Mar (varies by island)' },
    ],
    licenseInfo: {
      residentBase: '$20',
      nonResidentBase: '$105',
      deerTagResident: 'Included with license for most hunts',
      deerTagNonResident: 'Included with license for most hunts',
      youthPrograms: 'Youth license available; limited access hunts',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'None for axis deer; varies by species',
      bagLimit: 'Varies by island, unit, and species',
      blazeOrange: 'Required during firearm seasons on public hunting areas',
      baiting: 'Prohibited on public hunting areas',
      sundayHunting: 'Allowed (seasons run specific dates)',
      crossbowDuringArchery: true,
    },
    agencyName: 'Hawaii DLNR Division of Forestry & Wildlife',
    agencyUrl: 'https://dlnr.hawaii.gov/dofaw',
  },
];
