// Buck Stop Lure Company - Northeast State Hunting Guide Data
// States: ME, NH, VT, MA, CT, RI, NY, NJ, PA, DE, MD

import type { StateHuntingGuide } from './state-hunting-guide';

export const northeastStates: StateHuntingGuide[] = [
  {
    stateCode: 'ME',
    stateName: 'Maine',
    region: 'Northeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Moose', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Ruffed Grouse', category: 'upland' },
      { name: 'Woodcock', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Snowshoe Hare', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Oct 1 - Dec 12' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 4 - Nov 30' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Dec 2 - Dec 14' },
      { type: 'general', species: 'Moose', dateRange: 'Sep - Oct (by permit lottery)' },
      { type: 'general', species: 'Bear', dateRange: 'Aug 26 - Nov 25' },
      { type: 'general', species: 'Turkey (Spring)', dateRange: 'May (by zone)' },
    ],
    licenseInfo: {
      residentBase: '$26',
      nonResidentBase: '$115',
      deerTagResident: 'Included with license',
      deerTagNonResident: 'Included with license',
      youthPrograms: 'Youth license (10-15) at reduced cost; youth deer day',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Antler point restrictions in some WMDs',
      bagLimit: '1 antlered deer; additional antlerless permits by zone',
      blazeOrange: 'Required during firearm season (1 article of blaze orange)',
      baiting: 'Prohibited for deer',
      sundayHunting: 'Prohibited statewide',
      crossbowDuringArchery: false,
    },
    agencyName: 'Maine Dept. of Inland Fisheries & Wildlife',
    agencyUrl: 'https://www.maine.gov/ifw',
  },
  {
    stateCode: 'NH',
    stateName: 'New Hampshire',
    region: 'Northeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Moose', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Ruffed Grouse', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Snowshoe Hare', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 15 - Dec 15' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 13 - Dec 8' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Oct 26 - Nov 5' },
      { type: 'general', species: 'Bear', dateRange: 'Sep 1 - Nov (varies)' },
      { type: 'general', species: 'Moose', dateRange: 'Oct (lottery only)' },
    ],
    licenseInfo: {
      residentBase: '$15',
      nonResidentBase: '$113',
      deerTagResident: 'Included with license',
      deerTagNonResident: 'Included with license',
      youthPrograms: 'Youth license ages 12-15; mentored hunts for younger',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'One antlered deer per season',
      bagLimit: '1 antlered deer plus bonus antlerless permits',
      blazeOrange: 'Required during firearm season (blaze orange or pink)',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: false,
    },
    agencyName: 'New Hampshire Fish & Game',
    agencyUrl: 'https://www.wildlife.nh.gov',
  },
  {
    stateCode: 'VT',
    stateName: 'Vermont',
    region: 'Northeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Moose', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Ruffed Grouse', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Snowshoe Hare', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Oct 1 - Dec 15' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 16 - Dec 1' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Dec 5 - Dec 15' },
      { type: 'general', species: 'Bear', dateRange: 'Sep 1 - Nov (varies)' },
      { type: 'general', species: 'Turkey (Spring)', dateRange: 'May 1 - May 31' },
    ],
    licenseInfo: {
      residentBase: '$28',
      nonResidentBase: '$102',
      deerTagResident: 'Included',
      deerTagNonResident: 'Included',
      youthPrograms: 'Youth weekend deer hunt; apprentice license',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Bucks must have 1 antler with 2+ points',
      bagLimit: '1 buck plus antlerless by permit',
      blazeOrange: 'Required during rifle season',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed on private land with landowner permission',
      crossbowDuringArchery: false,
    },
    agencyName: 'Vermont Fish & Wildlife',
    agencyUrl: 'https://vtfishandwildlife.com',
  },
  {
    stateCode: 'MA',
    stateName: 'Massachusetts',
    region: 'Northeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Oct 21 - Nov 25' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 27 - Dec 14 (shotgun)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Dec 16 - Dec 31' },
    ],
    licenseInfo: {
      residentBase: '$27.50',
      nonResidentBase: '$65.50',
      deerTagResident: 'Included',
      deerTagNonResident: 'Included',
      youthPrograms: 'Free for under 15 with adult mentor; youth deer hunt day',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'None statewide',
      bagLimit: '2 deer total across all seasons',
      blazeOrange: 'Required during shotgun season (500 sq in)',
      baiting: 'Prohibited',
      sundayHunting: 'Prohibited -- one of two states with full Sunday ban',
      crossbowDuringArchery: false,
    },
    agencyName: 'Massachusetts Division of Fisheries & Wildlife',
    agencyUrl: 'https://www.mass.gov/orgs/division-of-fisheries-and-wildlife',
  },
  {
    stateCode: 'CT',
    stateName: 'Connecticut',
    region: 'Northeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 15 - Dec 31' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 20 - Dec 10 (shotgun)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Dec 11 - Dec 31' },
    ],
    licenseInfo: {
      residentBase: '$19',
      nonResidentBase: '$91',
      deerTagResident: 'Included',
      deerTagNonResident: 'Included',
      youthPrograms: 'Junior hunting license ages 12-15',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'None statewide',
      bagLimit: '2 deer per season with bonus tags available',
      blazeOrange: 'Required during firearm season (400 sq in above waist)',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed on private land; prohibited on state land',
      crossbowDuringArchery: true,
    },
    agencyName: 'Connecticut DEEP Wildlife Division',
    agencyUrl: 'https://portal.ct.gov/deep/wildlife',
  },
  {
    stateCode: 'RI',
    stateName: 'Rhode Island',
    region: 'Northeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 15 - Jan 31' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 9 - Jan 31 (shotgun)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Nov 9 - Jan 31' },
    ],
    licenseInfo: {
      residentBase: '$18',
      nonResidentBase: '$40',
      deerTagResident: 'Included',
      deerTagNonResident: 'Included',
      youthPrograms: 'Free license for under 15',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'None',
      bagLimit: '2 deer per season',
      blazeOrange: 'Recommended but not required',
      baiting: 'Prohibited on public land',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Rhode Island DEM Division of Fish & Wildlife',
    agencyUrl: 'https://dem.ri.gov/fish-and-wildlife',
  },
  {
    stateCode: 'NY',
    stateName: 'New York',
    region: 'Northeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Ruffed Grouse', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Oct 1 - Nov 17 & Dec 14 - Jan 1' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 18 - Dec 10 (varies by zone)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Oct 14 - Oct 22 & Dec 11 - Dec 17' },
      { type: 'general', species: 'Bear', dateRange: 'Sep - Dec (varies by zone)' },
    ],
    licenseInfo: {
      residentBase: '$22',
      nonResidentBase: '$100',
      deerTagResident: 'Included',
      deerTagNonResident: 'Included',
      youthPrograms: 'Junior license (12-15) $5; youth big game hunt',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Vary by WMU -- earn-a-buck in some units',
      bagLimit: '1 antlered + antlerless permits by WMU',
      blazeOrange: 'Required during gun season',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'New York DEC',
    agencyUrl: 'https://www.dec.ny.gov',
  },
  {
    stateCode: 'NJ',
    stateName: 'New Jersey',
    region: 'Northeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 14 - Oct 25 & Nov 11 - Jan 31' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 4 - Dec 9 (varies by zone)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Dec 11 - Dec 23' },
    ],
    licenseInfo: {
      residentBase: '$27.50',
      nonResidentBase: '$135.50',
      deerTagResident: '$28 (permit)',
      deerTagNonResident: '$65 (permit)',
      youthPrograms: 'Youth license for 10-15; special youth hunt days',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Earn-a-buck in some zones',
      bagLimit: 'Varies by zone -- up to 6+ antlerless in some zones',
      blazeOrange: 'Required during firearm season',
      baiting: 'Prohibited',
      sundayHunting: 'Bow hunting allowed on Sundays on WMAs and private land',
      crossbowDuringArchery: true,
    },
    agencyName: 'New Jersey Division of Fish & Wildlife',
    agencyUrl: 'https://www.nj.gov/dep/fgw',
  },
  {
    stateCode: 'PA',
    stateName: 'Pennsylvania',
    region: 'Northeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Ruffed Grouse', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Oct 5 - Nov 16 & Dec 26 - Jan 25' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 30 - Dec 14' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Dec 26 - Jan 17 (flintlock)' },
    ],
    licenseInfo: {
      residentBase: '$20.97',
      nonResidentBase: '$101.97',
      deerTagResident: 'Included',
      deerTagNonResident: 'Included',
      youthPrograms: 'Junior license 50% off; mentored youth permits ages 7+',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: '3 points on one side in most WMUs',
      bagLimit: '1 antlered + antlerless permits by WMU',
      blazeOrange: 'Required during firearm season (250 sq in)',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed on private and select public land (expanded 2025)',
      crossbowDuringArchery: true,
    },
    agencyName: 'Pennsylvania Game Commission',
    agencyUrl: 'https://www.pgc.pa.gov',
  },
  {
    stateCode: 'DE',
    stateName: 'Delaware',
    region: 'Northeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 1 - Jan 31' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 15 - Jan 31 (shotgun)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Oct 14 - Oct 22' },
    ],
    licenseInfo: {
      residentBase: '$12.50',
      nonResidentBase: '$80',
      deerTagResident: 'Included',
      deerTagNonResident: 'Included',
      youthPrograms: 'Free for under 16',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'None statewide',
      bagLimit: '2 antlered per season; liberal antlerless',
      blazeOrange: 'Required during firearm season',
      baiting: 'Allowed on private land',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Delaware Division of Fish & Wildlife',
    agencyUrl: 'https://dnrec.delaware.gov/fish-wildlife',
  },
  {
    stateCode: 'MD',
    stateName: 'Maryland',
    region: 'Northeast',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Sika Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 8 - Oct 25 & Dec 16 - Jan 31' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 25 - Dec 8 (rifle); Oct 26 - Nov 24 (early)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Oct 19 - Oct 25' },
    ],
    licenseInfo: {
      residentBase: '$24.50',
      nonResidentBase: '$130',
      deerTagResident: '$5 stamp',
      deerTagNonResident: '$5 stamp',
      youthPrograms: 'Junior license for 10-15; youth hunting days',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: '3 points on one side minimum; 1 exemption per year',
      bagLimit: '2 antlered per season; antlerless varies by county',
      blazeOrange: 'Required during firearm season',
      baiting: 'Prohibited in some counties (CWD response)',
      sundayHunting: 'Allowed on private land; limited on public land',
      crossbowDuringArchery: true,
    },
    agencyName: 'Maryland DNR',
    agencyUrl: 'https://dnr.maryland.gov/wildlife',
  },
];
