// Buck Stop Lure Company - Mountain West State Hunting Guide Data
// States: MT, WY, CO, ID, NV, UT, NM, AZ

import type { StateHuntingGuide } from './state-hunting-guide';

export const westernStates: StateHuntingGuide[] = [
  {
    stateCode: 'MT',
    stateName: 'Montana',
    region: 'Mountain West',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Antelope', category: 'big-game' },
      { name: 'Moose', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Mountain Lion', category: 'big-game' },
      { name: 'Mountain Goat', category: 'big-game' },
      { name: 'Bighorn Sheep', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Grouse', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer/Elk', dateRange: 'Sep 6 - Oct 19' },
      { type: 'firearm', species: 'Deer/Elk', dateRange: 'Oct 25 - Nov 30 (general)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Dec (by district)' },
      { type: 'general', species: 'Antelope', dateRange: 'Oct 4 - Nov 9' },
    ],
    licenseInfo: {
      residentBase: '$20 (conservation + $10 base)',
      nonResidentBase: '$50 base + combination license $1,079',
      deerTagResident: 'Included in combination ($29 deer tag)',
      deerTagNonResident: '$365 (part of combination or B-license)',
      youthPrograms: 'Discounted youth licenses; mentored youth hunts',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Brow-tine bull regulation for elk in some districts',
      bagLimit: '1 deer per general tag; B-licenses for additional',
      blazeOrange: 'Not required (strongly recommended during rifle season)',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: false,
    },
    agencyName: 'Montana Fish, Wildlife & Parks',
    agencyUrl: 'https://fwp.mt.gov',
  },
  {
    stateCode: 'WY',
    stateName: 'Wyoming',
    region: 'Mountain West',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Antelope', category: 'big-game' },
      { name: 'Moose', category: 'big-game' },
      { name: 'Bighorn Sheep', category: 'big-game' },
      { name: 'Mountain Goat', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Mountain Lion', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Grouse', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer/Elk', dateRange: 'Sep 1 - Sep 30' },
      { type: 'firearm', species: 'Deer', dateRange: 'Oct 1 - Nov 30 (varies by area)' },
      { type: 'firearm', species: 'Elk', dateRange: 'Oct 1 - Nov 30 (varies by area)' },
      { type: 'general', species: 'Antelope', dateRange: 'Sep - Oct (by area)' },
    ],
    licenseInfo: {
      residentBase: '$30 conservation stamp',
      nonResidentBase: '$37 conservation stamp',
      deerTagResident: '$47 deer license',
      deerTagNonResident: '$392 full-price deer license (draw system)',
      youthPrograms: 'Youth prices reduced; preference point system',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Varies by hunt area',
      bagLimit: '1 per license type',
      blazeOrange: 'Not required (recommended)',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: false,
    },
    agencyName: 'Wyoming Game & Fish Department',
    agencyUrl: 'https://wgfd.wyo.gov',
  },
  {
    stateCode: 'CO',
    stateName: 'Colorado',
    region: 'Mountain West',
    species: [
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Antelope', category: 'big-game' },
      { name: 'Moose', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Mountain Lion', category: 'big-game' },
      { name: 'Bighorn Sheep', category: 'big-game' },
      { name: 'Mountain Goat', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Grouse', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer/Elk', dateRange: 'Aug 30 - Sep 28 (archery only)' },
      { type: 'firearm', species: 'Deer', dateRange: 'Oct 12 - Nov 10 (combined rifle; varies by GMU)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Sep 13 - Sep 21' },
      { type: 'general', species: 'Elk', dateRange: 'Oct - Nov (multiple rifle seasons by GMU)' },
    ],
    licenseInfo: {
      residentBase: '$35.17 qualification',
      nonResidentBase: '$98.63 qualification',
      deerTagResident: '$51 deer license',
      deerTagNonResident: '$414 deer license (draw or OTC)',
      youthPrograms: 'Youth licenses reduced; mentored youth program; preference points',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Varies by GMU; some units bucks only, some antler-point restrictions',
      bagLimit: '1 per species per license',
      blazeOrange: 'Not required (recommended)',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: false,
    },
    agencyName: 'Colorado Parks & Wildlife',
    agencyUrl: 'https://cpw.state.co.us',
  },
  {
    stateCode: 'ID',
    stateName: 'Idaho',
    region: 'Mountain West',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Antelope', category: 'big-game' },
      { name: 'Moose', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Mountain Lion', category: 'big-game' },
      { name: 'Mountain Goat', category: 'big-game' },
      { name: 'Bighorn Sheep', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Grouse', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer/Elk', dateRange: 'Aug 30 - Sep 30 (general archery)' },
      { type: 'firearm', species: 'Deer', dateRange: 'Oct 10 - Nov 18 (general; varies by zone)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Dec (varies by zone)' },
      { type: 'general', species: 'Elk', dateRange: 'Oct - Nov (general + controlled hunts)' },
    ],
    licenseInfo: {
      residentBase: '$15.75',
      nonResidentBase: '$154.75',
      deerTagResident: '$23.25 deer tag',
      deerTagNonResident: '$416.25 deer tag',
      youthPrograms: 'Youth pricing under 18; mentored hunting program',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Varies by unit; some units have 3-point minimum for whitetail',
      bagLimit: '1 deer per tag; can purchase general + controlled hunt tags',
      blazeOrange: 'Not required (recommended)',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: false,
    },
    agencyName: 'Idaho Fish & Game',
    agencyUrl: 'https://idfg.idaho.gov',
  },
  {
    stateCode: 'NV',
    stateName: 'Nevada',
    region: 'Mountain West',
    species: [
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Antelope', category: 'big-game' },
      { name: 'Bighorn Sheep', category: 'big-game' },
      { name: 'Mountain Goat', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Mountain Lion', category: 'big-game' },
      { name: 'Chukar', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Aug - Sep (by unit; draw only)' },
      { type: 'firearm', species: 'Deer', dateRange: 'Oct - Nov (by unit; draw only)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Sep - Oct (by unit; draw only)' },
    ],
    licenseInfo: {
      residentBase: '$33',
      nonResidentBase: '$142',
      deerTagResident: '$30 application + $120 tag (if drawn)',
      deerTagNonResident: '$30 application + $240 tag (if drawn)',
      youthPrograms: 'Youth pricing under 18; bonus/preference point system',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Varies by unit',
      bagLimit: '1 per tag (draw only for all big game)',
      blazeOrange: 'Not required',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: false,
    },
    agencyName: 'Nevada Dept. of Wildlife',
    agencyUrl: 'https://www.ndow.org',
  },
  {
    stateCode: 'UT',
    stateName: 'Utah',
    region: 'Mountain West',
    species: [
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Antelope', category: 'big-game' },
      { name: 'Moose', category: 'big-game' },
      { name: 'Bighorn Sheep', category: 'big-game' },
      { name: 'Mountain Goat', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Mountain Lion', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Chukar', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Grouse', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Aug 16 - Sep 12 (general archery)' },
      { type: 'firearm', species: 'Deer', dateRange: 'Oct 19 - Oct 27 (general any weapon)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Sep 24 - Oct 6' },
      { type: 'general', species: 'Elk', dateRange: 'Sep - Oct (varies by unit; draw + general)' },
    ],
    licenseInfo: {
      residentBase: '$34 combination',
      nonResidentBase: '$65 combination',
      deerTagResident: '$50 general or $35 limited-entry application',
      deerTagNonResident: '$298 general or draw-only for premium units',
      youthPrograms: 'Reduced youth pricing; dedicated hunter program; preference points',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Bucks only on general units; antler restrictions on LE units',
      bagLimit: '1 per permit',
      blazeOrange: 'Not required (recommended)',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: false,
    },
    agencyName: 'Utah Division of Wildlife Resources',
    agencyUrl: 'https://wildlife.utah.gov',
  },
  {
    stateCode: 'NM',
    stateName: 'New Mexico',
    region: 'Mountain West',
    species: [
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Whitetail Deer (Coues)', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Antelope', category: 'big-game' },
      { name: 'Bighorn Sheep', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Mountain Lion', category: 'big-game' },
      { name: 'Javelina', category: 'big-game' },
      { name: 'Quail', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 1 - Sep 24 (varies by GMU)' },
      { type: 'firearm', species: 'Deer', dateRange: 'Oct - Nov (draw only; varies by GMU)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Oct (draw by GMU)' },
      { type: 'general', species: 'Elk', dateRange: 'Sep - Jan (archery, muzzleloader, rifle by period)' },
    ],
    licenseInfo: {
      residentBase: '$25 game-hunting license (fee increase effective April 2026)',
      nonResidentBase: '$90 game-hunting license',
      deerTagResident: '$42 deer tag',
      deerTagNonResident: '$310 deer tag',
      youthPrograms: 'Youth pricing for under 18; mentored youth hunts',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Varies by GMU; antler-point restrictions in some units',
      bagLimit: '1 per species per license',
      blazeOrange: 'Required during rifle seasons (fluorescent orange, 244 sq in)',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: false,
    },
    agencyName: 'New Mexico Dept. of Game & Fish',
    agencyUrl: 'https://www.wildlife.state.nm.us',
  },
  {
    stateCode: 'AZ',
    stateName: 'Arizona',
    region: 'Mountain West',
    species: [
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Coues Whitetail Deer', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Antelope', category: 'big-game' },
      { name: 'Bighorn Sheep', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Mountain Lion', category: 'big-game' },
      { name: 'Javelina', category: 'big-game' },
      { name: 'Bison', category: 'big-game' },
      { name: 'Quail (Gambels, Scaled, Mearns)', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Aug - Jan (by unit; draw only)' },
      { type: 'firearm', species: 'Deer', dateRange: 'Oct - Dec (by unit; draw only)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Included in general hunt dates' },
      { type: 'general', species: 'Elk', dateRange: 'Sep - Dec (draw only)' },
      { type: 'general', species: 'Javelina', dateRange: 'Jan - Feb (draw)' },
    ],
    licenseInfo: {
      residentBase: '$37 combination',
      nonResidentBase: '$160 combination',
      deerTagResident: '$13 application + $54 tag (if drawn)',
      deerTagNonResident: '$13 application + $225 tag (if drawn)',
      youthPrograms: 'Youth combination $5; bonus points carry over',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Varies by unit and species',
      bagLimit: '1 per tag (all big game draw-only)',
      blazeOrange: 'Not required',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: false,
    },
    agencyName: 'Arizona Game & Fish Department',
    agencyUrl: 'https://www.azgfd.com',
  },
];
