// Buck Stop Lure Company - Midwest State Hunting Guide Data
// States: OH, MI, IN, IL, WI, MN, IA, MO

import type { StateHuntingGuide } from './state-hunting-guide';

export const midwestStates: StateHuntingGuide[] = [
  {
    stateCode: 'OH',
    stateName: 'Ohio',
    region: 'Midwest',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Ruffed Grouse', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 28 - Feb 2' },
      { type: 'firearm', species: 'Deer', dateRange: 'Dec 2 - Dec 8 & Dec 21 - Dec 22 (gun)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Jan 4 - Jan 7' },
    ],
    licenseInfo: {
      residentBase: '$19',
      nonResidentBase: '$125',
      deerTagResident: '$24 deer permit',
      deerTagNonResident: '$40 deer permit',
      youthPrograms: 'Youth license free under 18; youth gun weekend',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Antler point restrictions in most counties',
      bagLimit: '1 antlered + up to 6 antlerless with permits (varies by county)',
      blazeOrange: 'Required during gun season',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Ohio DNR Division of Wildlife',
    agencyUrl: 'https://ohiodnr.gov/wildlife',
  },
  {
    stateCode: 'MI',
    stateName: 'Michigan',
    region: 'Midwest',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Ruffed Grouse', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Woodcock', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Oct 1 - Nov 14 & Dec 1 - Jan 1' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 15 - Nov 30' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Dec 6 - Dec 21 (Zone 1 & 2)' },
      { type: 'general', species: 'Elk', dateRange: 'Sep - Dec (lottery only; ~200 tags)' },
      { type: 'general', species: 'Bear', dateRange: 'Sep - Oct (by permit)' },
    ],
    licenseInfo: {
      residentBase: '$11',
      nonResidentBase: '$151',
      deerTagResident: '$20 deer license',
      deerTagNonResident: '$190 deer license',
      youthPrograms: 'Mentored youth hunting; youth hunt weekends; junior license',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'APR in select DMUs; generally 3 pts on one side or 4+ combined',
      bagLimit: '2 deer total (1 antlered + 1 antlerless in most DMUs)',
      blazeOrange: 'Required during firearm season (50% of outer clothing)',
      baiting: 'Banned statewide due to CWD/bovine TB',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Michigan DNR',
    agencyUrl: 'https://www.michigan.gov/dnr',
  },
  {
    stateCode: 'IN',
    stateName: 'Indiana',
    region: 'Midwest',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Oct 1 - Jan 5' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 15 - Nov 30' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Dec 6 - Dec 21' },
    ],
    licenseInfo: {
      residentBase: '$17',
      nonResidentBase: '$80',
      deerTagResident: '$24 deer bundle',
      deerTagNonResident: '$150 deer bundle',
      youthPrograms: 'Youth license $7; special youth deer season weekend',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'None statewide (one buck rule)',
      bagLimit: '1 antlered deer per year; bonus antlerless tags available',
      blazeOrange: 'Required during firearm season',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Indiana DNR Fish & Wildlife',
    agencyUrl: 'https://www.in.gov/dnr/fish-and-wildlife',
  },
  {
    stateCode: 'IL',
    stateName: 'Illinois',
    region: 'Midwest',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Oct 1 - Jan 18 (with breaks)' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 21 - Nov 23 & Dec 4 - Dec 7 (shotgun/straight-wall)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Dec 8 - Dec 21' },
    ],
    licenseInfo: {
      residentBase: '$12',
      nonResidentBase: '$57',
      deerTagResident: '$25.50 deer permit',
      deerTagNonResident: '$300 deer permit',
      youthPrograms: 'Youth license free; special youth deer weekends',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'None statewide',
      bagLimit: '1 antlered per season unless bonus tags available; 2 total',
      blazeOrange: 'Required during firearm season (blaze orange or pink)',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Illinois DNR',
    agencyUrl: 'https://www2.illinois.gov/dnr',
  },
  {
    stateCode: 'WI',
    stateName: 'Wisconsin',
    region: 'Midwest',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Ruffed Grouse', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 14 - Jan 5 (crossbow same)' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 22 - Nov 30 (9-day gun)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Dec 1 - Dec 10' },
      { type: 'general', species: 'Bear', dateRange: 'Sep (by permit/preference)' },
    ],
    licenseInfo: {
      residentBase: '$20',
      nonResidentBase: '$160',
      deerTagResident: '$24 gun tag or $24 bow tag',
      deerTagNonResident: '$160 gun tag',
      youthPrograms: 'Free for under 12 with mentor; youth deer hunt weekend',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Earn-a-Buck in select counties; no statewide APR',
      bagLimit: '1 antlered per tag; bonus antlerless tags in many units',
      blazeOrange: 'Required during gun season (blaze orange or pink, 50% outer)',
      baiting: 'Prohibited statewide (CWD response)',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Wisconsin DNR',
    agencyUrl: 'https://dnr.wisconsin.gov',
  },
  {
    stateCode: 'MN',
    stateName: 'Minnesota',
    region: 'Midwest',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Moose', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Ruffed Grouse', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 14 - Dec 31' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 8 - Nov 23 (varies by zone/series)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Nov 29 - Dec 14' },
      { type: 'general', species: 'Bear', dateRange: 'Sep (by lottery)' },
    ],
    licenseInfo: {
      residentBase: '$26',
      nonResidentBase: '$155',
      deerTagResident: 'Included with deer license ($34 total)',
      deerTagNonResident: '$175 total deer license',
      youthPrograms: 'Youth license $5.50; firearms safety age 12+; youth deer hunt',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Voluntary only; no mandatory APR',
      bagLimit: '1 antlered + lottery antlerless permits',
      blazeOrange: 'Required during firearm season (blaze orange or pink)',
      baiting: 'Prohibited statewide',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Minnesota DNR',
    agencyUrl: 'https://www.dnr.state.mn.us',
  },
  {
    stateCode: 'IA',
    stateName: 'Iowa',
    region: 'Midwest',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Oct 1 - Dec 5 & Dec 22 - Jan 10' },
      { type: 'firearm', species: 'Deer', dateRange: 'Dec 7 - Dec 11 (first shotgun) & Dec 14 - Dec 22 (second)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Oct 13 - Oct 23 (early) & Jan 11 - Jan 19 (late)' },
    ],
    licenseInfo: {
      residentBase: '$19',
      nonResidentBase: '$121',
      deerTagResident: '$30 any-sex tag',
      deerTagNonResident: '$511 any-sex tag (non-resident)',
      youthPrograms: 'Youth license free; special youth deer season; mentored youth',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'None statewide; one buck limit enforces quality',
      bagLimit: '1 antlered per season; additional antlerless tags available',
      blazeOrange: 'Required during shotgun and muzzleloader seasons',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Iowa DNR',
    agencyUrl: 'https://www.iowadnr.gov',
  },
  {
    stateCode: 'MO',
    stateName: 'Missouri',
    region: 'Midwest',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 15 - Nov 14 & Nov 26 - Jan 15' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 15 - Nov 25 (November portion)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Dec (alternative methods)' },
    ],
    licenseInfo: {
      residentBase: '$19',
      nonResidentBase: '$205',
      deerTagResident: '$11 deer permit',
      deerTagNonResident: '$275 non-resident deer permit',
      youthPrograms: 'Free for under 16; youth deer season 2 weekends',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Antler point restrictions in select counties (being revised)',
      bagLimit: '2 antlered per season; antlerless permits vary by county',
      blazeOrange: 'Required during firearms deer season',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Missouri Dept. of Conservation',
    agencyUrl: 'https://mdc.mo.gov',
  },
];
