// Buck Stop Lure Company - Plains & South State Hunting Guide Data
// States: KS, NE, SD, ND, OK, TX, LA, AR, TN, KY

import type { StateHuntingGuide } from './state-hunting-guide';

export const plainsStates: StateHuntingGuide[] = [
  {
    stateCode: 'KS',
    stateName: 'Kansas',
    region: 'Plains',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Antelope', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 15 - Dec 31' },
      { type: 'firearm', species: 'Deer', dateRange: 'Dec 3 - Dec 14 (rifle); Nov 26 - Dec 7 (pre-rut firearm in some units)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Sep 15 - Sep 28' },
    ],
    licenseInfo: {
      residentBase: '$27.50',
      nonResidentBase: '$97.50',
      deerTagResident: '$42.50',
      deerTagNonResident: '$442.50',
      youthPrograms: 'Youth/mentor license; special youth seasons',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'None statewide',
      bagLimit: '1 antlered per permit type (can purchase archery + firearm)',
      blazeOrange: 'Required during firearm season',
      baiting: 'Allowed on private land; prohibited on public land',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Kansas Dept. of Wildlife & Parks',
    agencyUrl: 'https://ksoutdoors.gov',
  },
  {
    stateCode: 'NE',
    stateName: 'Nebraska',
    region: 'Plains',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Antelope', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Grouse', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 1 - Dec 31' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 16 - Nov 24 (rifle)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Dec 1 - Dec 31' },
    ],
    licenseInfo: {
      residentBase: '$31',
      nonResidentBase: '$129',
      deerTagResident: '$31 deer permit',
      deerTagNonResident: '$236 deer permit',
      youthPrograms: 'Youth permits at reduced cost; special youth seasons',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'None statewide',
      bagLimit: '2 deer per year (varies by permit type and unit)',
      blazeOrange: 'Required during firearm season (400 sq in on head and back)',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Nebraska Game & Parks Commission',
    agencyUrl: 'https://outdoornebraska.gov',
  },
  {
    stateCode: 'SD',
    stateName: 'South Dakota',
    region: 'Plains',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Antelope', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Mountain Lion', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Grouse', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 1 - Jan 1' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 1 - Jan 1 (West River); varies East River (lottery)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Dec 1 - Jan 1' },
    ],
    licenseInfo: {
      residentBase: '$28',
      nonResidentBase: '$125',
      deerTagResident: '$40 West River / $44 East River',
      deerTagNonResident: '$286 West River / $286 East River (lottery)',
      youthPrograms: 'Youth licenses at reduced cost; youth-only deer season',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'None statewide',
      bagLimit: '1 per tag; can apply for multiple tags in different units',
      blazeOrange: 'Required during firearm season',
      baiting: 'Prohibited',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'South Dakota Game, Fish & Parks',
    agencyUrl: 'https://gfp.sd.gov',
  },
  {
    stateCode: 'ND',
    stateName: 'North Dakota',
    region: 'Plains',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Antelope', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Moose', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Grouse', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Aug 30 - Jan 5' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 8 - Nov 24 (gun; lottery)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Nov 29 - Dec 15' },
    ],
    licenseInfo: {
      residentBase: '$20',
      nonResidentBase: '$110',
      deerTagResident: '$30 gun tag (lottery)',
      deerTagNonResident: '$250 gun tag (limited non-resident allocation)',
      youthPrograms: 'Youth deer license; hunting mentorship program',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'None statewide',
      bagLimit: '1 per license type; limited doe tags by unit',
      blazeOrange: 'Required during gun season (400 sq in)',
      baiting: 'Allowed on private land; prohibited on public land',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: false,
    },
    agencyName: 'North Dakota Game & Fish Department',
    agencyUrl: 'https://gf.nd.gov',
  },
  {
    stateCode: 'OK',
    stateName: 'Oklahoma',
    region: 'Plains',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Feral Hog', category: 'other' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Oct 1 - Jan 15' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 23 - Dec 8 (gun)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Oct 26 - Nov 3' },
    ],
    licenseInfo: {
      residentBase: '$25',
      nonResidentBase: '$226',
      deerTagResident: '$25 deer tag',
      deerTagNonResident: '$276 deer tag',
      youthPrograms: 'Youth license free for under 18; youth deer weekend',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'None statewide; 1 antlered per gun season',
      bagLimit: '2 antlered + 4 antlerless per season across all methods',
      blazeOrange: 'Required during muzzleloader and gun season (400 sq in outer)',
      baiting: 'Allowed on private land; prohibited on public land',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Oklahoma Dept. of Wildlife Conservation',
    agencyUrl: 'https://www.wildlifedepartment.com',
  },
  {
    stateCode: 'TX',
    stateName: 'Texas',
    region: 'South',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Mule Deer', category: 'big-game' },
      { name: 'Javelina', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Pheasant', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Feral Hog', category: 'other' },
      { name: 'Exotic Species (Axis, Nilgai, etc.)', category: 'other' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 27 - Oct 31' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 1 - Jan 5 (North); Nov 1 - Jan 19 (South)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Jan 6 - Jan 19 (North)' },
      { type: 'general', species: 'Feral Hog', dateRange: 'Year-round on private land; no bag limit' },
    ],
    licenseInfo: {
      residentBase: '$25',
      nonResidentBase: '$315',
      deerTagResident: 'Included with license (tags on license)',
      deerTagNonResident: 'Included (5 deer tags on license)',
      youthPrograms: 'Youth license $7; special youth-only deer weekends',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Vary by county; some require 13-inch inside spread',
      bagLimit: '5 deer per license (no more than 3 bucks statewide; 2 in most counties)',
      blazeOrange: 'Not required (recommended)',
      baiting: 'Allowed on private land; regulated on some public land',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Texas Parks & Wildlife Dept.',
    agencyUrl: 'https://tpwd.texas.gov',
  },
  {
    stateCode: 'LA',
    stateName: 'Louisiana',
    region: 'South',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Feral Hog', category: 'other' },
      { name: 'Alligator', category: 'other' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 20 - Feb 15 (varies by Deer Area)' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 8 - Feb 15 (varies by Deer Area)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Oct 18 - Oct 24 & Nov 1 - Nov 7 (varies by area)' },
    ],
    licenseInfo: {
      residentBase: '$15',
      nonResidentBase: '$150',
      deerTagResident: '$12.50 deer tag',
      deerTagNonResident: '$150 deer tag',
      youthPrograms: 'Free for under 16; youth deer hunting weekend',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Varies by Deer Area; 3 inside points on one side in some areas',
      bagLimit: '6 per season (3 antlered; area limits may be lower)',
      blazeOrange: 'Required during gun season (400 sq in)',
      baiting: 'Allowed on private land',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Louisiana Dept. of Wildlife & Fisheries',
    agencyUrl: 'https://www.wlf.louisiana.gov',
  },
  {
    stateCode: 'AR',
    stateName: 'Arkansas',
    region: 'South',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Feral Hog', category: 'other' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 28 - Feb 28' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 9 - Dec 1 (modern gun)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Oct 19 - Oct 27' },
    ],
    licenseInfo: {
      residentBase: '$10.50',
      nonResidentBase: '$300',
      deerTagResident: '$10.50 deer tag',
      deerTagNonResident: '$175 all-game license',
      youthPrograms: 'Free for under 16; youth deer hunt weekends',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: '3-point minimum on one side in most zones',
      bagLimit: '6 per season (varies by zone)',
      blazeOrange: 'Required during gun season (solid blaze orange or safety green, 400 sq in)',
      baiting: 'Allowed on private land; prohibited on WMAs',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Arkansas Game & Fish Commission',
    agencyUrl: 'https://www.agfc.com',
  },
  {
    stateCode: 'TN',
    stateName: 'Tennessee',
    region: 'South',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Ruffed Grouse', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Feral Hog', category: 'other' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 27 - Oct 31 & Nov 1 - Jan 5 (continues into gun)' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 22 - Jan 5 (gun)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Nov 1 - Nov 14' },
    ],
    licenseInfo: {
      residentBase: '$34',
      nonResidentBase: '$166',
      deerTagResident: 'Included with license',
      deerTagNonResident: 'Included with license',
      youthPrograms: 'Youth license free; young sportsman license ages 13-15',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: '3 antlered per year; 1 must be 4+ pts on one side in some units',
      bagLimit: '3 antlered + bonus does (unit-specific antlerless limits)',
      blazeOrange: 'Required during gun season (500 sq in, head and body)',
      baiting: 'Allowed on private land with bait privilege license (effective 2026)',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Tennessee Wildlife Resources Agency',
    agencyUrl: 'https://www.tn.gov/twra',
  },
  {
    stateCode: 'KY',
    stateName: 'Kentucky',
    region: 'South',
    species: [
      { name: 'Whitetail Deer', category: 'big-game' },
      { name: 'Black Bear', category: 'big-game' },
      { name: 'Elk', category: 'big-game' },
      { name: 'Wild Turkey', category: 'upland' },
      { name: 'Dove', category: 'upland' },
      { name: 'Quail', category: 'upland' },
      { name: 'Ruffed Grouse', category: 'upland' },
      { name: 'Waterfowl', category: 'waterfowl' },
      { name: 'Cottontail Rabbit', category: 'small-game' },
      { name: 'Coyote', category: 'predator' },
    ],
    seasons: [
      { type: 'archery', species: 'Deer', dateRange: 'Sep 7 - Jan 20' },
      { type: 'crossbow', species: 'Deer', dateRange: 'Sep 21 - Jan 20' },
      { type: 'firearm', species: 'Deer', dateRange: 'Nov 9 - Nov 24 (modern gun)' },
      { type: 'muzzleloader', species: 'Deer', dateRange: 'Oct 19 - Oct 20 & Dec 14 - Dec 22' },
      { type: 'general', species: 'Elk', dateRange: 'Sep - Dec (lottery only; limited areas)' },
    ],
    licenseInfo: {
      residentBase: '$27',
      nonResidentBase: '$195',
      deerTagResident: 'Included with license',
      deerTagNonResident: 'Included with license',
      youthPrograms: 'Youth license free for under 16; youth deer weekend',
      hunterEdRequired: true,
    },
    regulations: {
      antlerRestrictions: 'Statewide 4-point rule in some zones; Zone 1 bucks must have 4+ pts on one side',
      bagLimit: '4 deer per season (1 antlered in most zones)',
      blazeOrange: 'Required during gun and muzzleloader season (hunter orange outer, head and body)',
      baiting: 'Allowed on private land; prohibited on WMAs',
      sundayHunting: 'Allowed',
      crossbowDuringArchery: true,
    },
    agencyName: 'Kentucky Dept. of Fish & Wildlife Resources',
    agencyUrl: 'https://fw.ky.gov',
  },
];
