// Buck Stop Lure Company - 2026 Whitetail Rut Calendar Data
// State-by-state rut timing predictions based on 70+ years of field data

export interface StateRutData {
  stateCode: string;
  stateName: string;
  region: 'Northeast' | 'Southeast' | 'Midwest' | 'Plains' | 'Mountain West' | 'Pacific West' | 'South';
  peakRutStart: string;
  peakRutEnd: string;
  preRutStart: string;
  seekingPhase: string;
  chasingPhase: string;
  breedingPhase: string;
  postRut: string;
  secondRut: string;
  notes: string;
  scentRecommendation: string;
  huntableSpecies: string[];
  seasons: {
    archery: string;
    firearm: string;
    muzzleloader: string;
  };
  keyRegulations: string[];
  agencyName: string;
  agencyUrl: string;
}

export type RutRegion = StateRutData['region'];

export const rutRegions: RutRegion[] = [
  'Northeast',
  'Southeast',
  'Midwest',
  'Plains',
  'Mountain West',
  'Pacific West',
  'South',
];

/**
 * Returns color for a state based on peak rut timing.
 * Uses 7 distinct colors for better visual differentiation on the map.
 */
export function getRutTimingColor(peakRutStart: string): string {
  const month = peakRutStart.split(' ')[0];
  const day = parseInt(peakRutStart.split(' ')[1], 10);

  if (month === 'October') return '#228B22';           // forest green (very distinct)
  if (month === 'November' && day <= 5) return '#6DB33F';   // lime green
  if (month === 'November' && day <= 10) return '#F0C820';  // bright yellow
  if (month === 'November' && day <= 15) return '#E88C20';  // bright orange
  if (month === 'November' && day <= 20) return '#D05020';  // red-orange
  if (month === 'November') return '#A02010';               // crimson
  if (month === 'December') return '#701818';               // dark red
  return '#401010';                                         // very dark red (Jan+)
}

export function getRutTimingLabel(peakRutStart: string): string {
  const month = peakRutStart.split(' ')[0];
  const day = parseInt(peakRutStart.split(' ')[1], 10);

  if (month === 'October') return 'Early (October)';
  if (month === 'November' && day <= 7) return 'Early Nov (1-7)';
  if (month === 'November' && day <= 15) return 'Mid Nov (8-15)';
  if (month === 'November') return 'Late Nov (16-30)';
  if (month === 'December') return 'December';
  return 'Late (January+)';
}

export const stateRutData: StateRutData[] = [
  // ── Northeast ──────────────────────────────────────────────
  {
    stateCode: 'ME',
    stateName: 'Maine',
    region: 'Northeast',
    peakRutStart: 'November 5',
    peakRutEnd: 'November 18',
    preRutStart: 'October 10',
    seekingPhase: 'October 20 - November 5',
    chasingPhase: 'November 5 - November 12',
    breedingPhase: 'November 8 - November 22',
    postRut: 'November 22 - December 10',
    secondRut: 'December 10 - December 22',
    notes: 'Northern Maine sees slightly earlier rut activity. Big woods bucks are on their feet earlier in the day during cold snaps. The second rut can produce mature bucks that were unsuccessful during the primary rut.',
    scentRecommendation: '200 PROOF Ultimate Doe-In-Heat during peak. Use MATE-TRIKS on scrape lines during seeking phase.',
    huntableSpecies: ['Whitetail', 'Bear', 'Moose', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Oct 1 - Dec 12',
      firearm: 'Nov 4 - Nov 30',
      muzzleloader: 'Dec 2 - Dec 14',
    },
    keyRegulations: ['Blaze orange required during firearm season', 'Sunday hunting prohibited', 'Antler point restrictions in some WMDs'],
    agencyName: 'Maine Dept. of Inland Fisheries & Wildlife',
    agencyUrl: 'https://www.maine.gov/ifw',
  },
  {
    stateCode: 'NH',
    stateName: 'New Hampshire',
    region: 'Northeast',
    peakRutStart: 'November 6',
    peakRutEnd: 'November 19',
    preRutStart: 'October 12',
    seekingPhase: 'October 22 - November 6',
    chasingPhase: 'November 6 - November 14',
    breedingPhase: 'November 10 - November 22',
    postRut: 'November 22 - December 12',
    secondRut: 'December 10 - December 24',
    notes: 'White Mountain region bucks rut slightly earlier than southern counties. Cold fronts in early November trigger intense chasing activity. Stand hunting near doe bedding areas is most effective.',
    scentRecommendation: 'MATE-TRIKS Doe-In-Heat on scrapes and trails. Switch to 200 PROOF during chasing phase for maximum pull.',
    huntableSpecies: ['Whitetail', 'Bear', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 15 - Dec 15',
      firearm: 'Nov 13 - Dec 8',
      muzzleloader: 'Oct 26 - Nov 5',
    },
    keyRegulations: ['Blaze orange or pink required during firearm season', 'Baiting prohibited', 'One antlered deer per season'],
    agencyName: 'New Hampshire Fish & Game',
    agencyUrl: 'https://www.wildlife.nh.gov',
  },
  {
    stateCode: 'VT',
    stateName: 'Vermont',
    region: 'Northeast',
    peakRutStart: 'November 5',
    peakRutEnd: 'November 18',
    preRutStart: 'October 10',
    seekingPhase: 'October 20 - November 5',
    chasingPhase: 'November 5 - November 13',
    breedingPhase: 'November 8 - November 22',
    postRut: 'November 22 - December 10',
    secondRut: 'December 8 - December 22',
    notes: 'Green Mountain bucks are highly active during the first two weeks of November. The rifle season typically aligns perfectly with peak breeding. Agricultural field edges produce consistent rut activity.',
    scentRecommendation: '200 PROOF Ultimate Doe-In-Heat paired with RUCK\'N BUCK on mock scrapes. GLAND-U-LURE on licking branches.',
    huntableSpecies: ['Whitetail', 'Bear', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Oct 1 - Dec 15',
      firearm: 'Nov 16 - Dec 1',
      muzzleloader: 'Dec 5 - Dec 15',
    },
    keyRegulations: ['Blaze orange required during rifle season', 'Antler point restrictions: bucks must have 1 antler with 2+ points', 'Sunday hunting prohibited on private land without permission'],
    agencyName: 'Vermont Fish & Wildlife',
    agencyUrl: 'https://vtfishandwildlife.com',
  },
  {
    stateCode: 'MA',
    stateName: 'Massachusetts',
    region: 'Northeast',
    peakRutStart: 'November 8',
    peakRutEnd: 'November 22',
    preRutStart: 'October 15',
    seekingPhase: 'October 25 - November 8',
    chasingPhase: 'November 8 - November 16',
    breedingPhase: 'November 12 - November 25',
    postRut: 'November 25 - December 15',
    secondRut: 'December 12 - December 26',
    notes: 'Suburban deer populations can produce exceptional bucks. The rut peaks slightly later than northern New England. Archery hunters have a significant advantage during the seeking phase.',
    scentRecommendation: 'MATE-TRIKS Original during seeking. 200 PROOF during chasing and breeding for maximum buck attraction.',
    huntableSpecies: ['Whitetail', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Oct 21 - Nov 25',
      firearm: 'Nov 27 - Dec 14',
      muzzleloader: 'Dec 16 - Dec 31',
    },
    keyRegulations: ['Blaze orange required during shotgun season', 'No rifles for deer in most zones', 'Sunday hunting allowed on private land only'],
    agencyName: 'Massachusetts Division of Fisheries & Wildlife',
    agencyUrl: 'https://www.mass.gov/orgs/division-of-fisheries-and-wildlife',
  },
  {
    stateCode: 'CT',
    stateName: 'Connecticut',
    region: 'Northeast',
    peakRutStart: 'November 8',
    peakRutEnd: 'November 22',
    preRutStart: 'October 15',
    seekingPhase: 'October 25 - November 8',
    chasingPhase: 'November 8 - November 17',
    breedingPhase: 'November 12 - November 25',
    postRut: 'November 25 - December 15',
    secondRut: 'December 12 - December 28',
    notes: 'High deer density in northwestern hills produces excellent rut action. Suburban bucks can be patterned along travel corridors between fragmented woodlots. Focus on pinch points and funnels.',
    scentRecommendation: 'MATE-TRIKS SPRAY for quick field application. 200 PROOF on scent wicks in travel corridors.',
    huntableSpecies: ['Whitetail', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 15 - Dec 31',
      firearm: 'Nov 20 - Dec 10',
      muzzleloader: 'Dec 11 - Dec 31',
    },
    keyRegulations: ['Blaze orange required during firearm season', 'No Sunday hunting on state land', 'Shotgun or muzzleloader only -- no rifles for deer'],
    agencyName: 'Connecticut DEEP Wildlife Division',
    agencyUrl: 'https://portal.ct.gov/deep/wildlife',
  },
  {
    stateCode: 'RI',
    stateName: 'Rhode Island',
    region: 'Northeast',
    peakRutStart: 'November 9',
    peakRutEnd: 'November 22',
    preRutStart: 'October 16',
    seekingPhase: 'October 26 - November 9',
    chasingPhase: 'November 9 - November 18',
    breedingPhase: 'November 13 - November 25',
    postRut: 'November 25 - December 15',
    secondRut: 'December 14 - December 28',
    notes: 'Small state with excellent deer management. Limited public land makes private access key. Bucks move consistently through narrow travel corridors between woodlots.',
    scentRecommendation: 'MATE-TRIKS Original on drag rags between stand sites. 200 PROOF during peak breeding.',
    huntableSpecies: ['Whitetail', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 15 - Jan 31',
      firearm: 'Nov 9 - Jan 31 (shotgun)',
      muzzleloader: 'Nov 9 - Jan 31',
    },
    keyRegulations: ['Blaze orange recommended but not required', 'Shotgun or muzzleloader only -- no rifles', 'Sunday hunting allowed'],
    agencyName: 'Rhode Island DEM Division of Fish & Wildlife',
    agencyUrl: 'https://dem.ri.gov/fish-and-wildlife',
  },
  {
    stateCode: 'NY',
    stateName: 'New York',
    region: 'Northeast',
    peakRutStart: 'November 5',
    peakRutEnd: 'November 20',
    preRutStart: 'October 10',
    seekingPhase: 'October 22 - November 5',
    chasingPhase: 'November 5 - November 14',
    breedingPhase: 'November 8 - November 24',
    postRut: 'November 24 - December 12',
    secondRut: 'December 10 - December 24',
    notes: 'Adirondack bucks rut earlier than Long Island or Catskill deer. Southern tier counties see peak activity around November 10-15. Big woods hunting requires patience and all-day sits during peak.',
    scentRecommendation: 'RUCK\'N BUCK for mock scrapes in early pre-rut. 200 PROOF Ultimate Doe-In-Heat from November 5 through peak.',
    huntableSpecies: ['Whitetail', 'Bear', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Oct 1 - Nov 17 & Dec 14 - Jan 1',
      firearm: 'Nov 18 - Dec 10 (Northern), Nov 18 - Dec 10 (Southern)',
      muzzleloader: 'Oct 14 - Oct 22 & Dec 11 - Dec 17',
    },
    keyRegulations: ['Blaze orange required during gun season', 'Earn-a-Buck in some WMUs', 'Antler restrictions vary by WMU'],
    agencyName: 'New York DEC',
    agencyUrl: 'https://www.dec.ny.gov',
  },
  {
    stateCode: 'NJ',
    stateName: 'New Jersey',
    region: 'Northeast',
    peakRutStart: 'November 8',
    peakRutEnd: 'November 22',
    preRutStart: 'October 15',
    seekingPhase: 'October 25 - November 8',
    chasingPhase: 'November 8 - November 16',
    breedingPhase: 'November 12 - November 25',
    postRut: 'November 25 - December 15',
    secondRut: 'December 12 - December 26',
    notes: 'North Jersey produces larger-racked bucks with earlier rut timing than southern pinelands. Agricultural areas in western NJ see intense rut activity along field edges and hedgerows.',
    scentRecommendation: 'Guide Grade Doe-In-Heat for trophy-class bucks. GLAND-U-LURE on licking branches and rub lines.',
    huntableSpecies: ['Whitetail', 'Bear', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 14 - Oct 25 & Nov 11 - Jan 31',
      firearm: 'Nov 4 - Dec 9 (shotgun/rifle varies by zone)',
      muzzleloader: 'Dec 11 - Dec 23',
    },
    keyRegulations: ['Blaze orange required during firearm season', 'Shotgun only in southern zones', 'Earn-a-Buck in some zones'],
    agencyName: 'New Jersey Division of Fish & Wildlife',
    agencyUrl: 'https://www.nj.gov/dep/fgw',
  },
  {
    stateCode: 'PA',
    stateName: 'Pennsylvania',
    region: 'Northeast',
    peakRutStart: 'November 8',
    peakRutEnd: 'November 20',
    preRutStart: 'October 12',
    seekingPhase: 'October 24 - November 8',
    chasingPhase: 'November 8 - November 15',
    breedingPhase: 'November 10 - November 24',
    postRut: 'November 24 - December 12',
    secondRut: 'December 10 - December 24',
    notes: 'Archery season overlaps perfectly with the rut. Northern tier counties peak slightly earlier. State forests in the central mountains hold excellent rut corridors. First two weeks of November are prime.',
    scentRecommendation: 'MATE-TRIKS PRO-SIZE for extended archery sits. 200 PROOF during November 8-20 peak window.',
    huntableSpecies: ['Whitetail', 'Bear', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Oct 5 - Nov 16 & Dec 26 - Jan 25',
      firearm: 'Nov 30 - Dec 14',
      muzzleloader: 'Dec 26 - Jan 17 (flintlock)',
    },
    keyRegulations: ['Blaze orange 250 sq in required during rifle season', 'Antler point restrictions: 3 pts on one side in most WMUs', 'Sunday hunting allowed on private and select public land'],
    agencyName: 'Pennsylvania Game Commission',
    agencyUrl: 'https://www.pgc.pa.gov',
  },
  {
    stateCode: 'DE',
    stateName: 'Delaware',
    region: 'Northeast',
    peakRutStart: 'November 10',
    peakRutEnd: 'November 24',
    preRutStart: 'October 18',
    seekingPhase: 'October 28 - November 10',
    chasingPhase: 'November 10 - November 18',
    breedingPhase: 'November 14 - November 26',
    postRut: 'November 26 - December 15',
    secondRut: 'December 14 - December 28',
    notes: 'Small but productive deer state. Agricultural landscape creates natural funnels. Sussex County in the south tends to see slightly later rut activity than New Castle County.',
    scentRecommendation: 'MATE-TRIKS SPRAY along field edges. 200 PROOF on scrape lines during chasing phase.',
    huntableSpecies: ['Whitetail', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 1 - Jan 31',
      firearm: 'Nov 15 - Jan 31 (shotgun)',
      muzzleloader: 'Oct 14 - Oct 22',
    },
    keyRegulations: ['Blaze orange required during firearm season', 'Shotgun only -- no rifles', 'Sunday hunting allowed'],
    agencyName: 'Delaware Division of Fish & Wildlife',
    agencyUrl: 'https://dnrec.delaware.gov/fish-wildlife',
  },
  {
    stateCode: 'MD',
    stateName: 'Maryland',
    region: 'Northeast',
    peakRutStart: 'November 10',
    peakRutEnd: 'November 24',
    preRutStart: 'October 16',
    seekingPhase: 'October 28 - November 10',
    chasingPhase: 'November 10 - November 18',
    breedingPhase: 'November 14 - November 26',
    postRut: 'November 26 - December 15',
    secondRut: 'December 14 - December 28',
    notes: 'Western Maryland mountains see earlier rut than Eastern Shore. Exceptional genetics in agricultural counties produce trophy bucks. Focus on oak flats and transition zones between ag fields and timber.',
    scentRecommendation: 'Guide Grade Doe-In-Heat for trophy potential areas. RUCK\'N BUCK on mock scrapes starting late October.',
    huntableSpecies: ['Whitetail', 'Bear', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 8 - Oct 25 & Dec 16 - Jan 31',
      firearm: 'Nov 25 - Dec 8 (rifle), Oct 26 - Nov 24 (early firearms)',
      muzzleloader: 'Oct 19 - Oct 25',
    },
    keyRegulations: ['Blaze orange required during firearm season', 'Sunday hunting allowed on private land only', 'Antler restrictions vary by region'],
    agencyName: 'Maryland DNR',
    agencyUrl: 'https://dnr.maryland.gov/wildlife',
  },

  // ── Southeast ──────────────────────────────────────────────
  {
    stateCode: 'VA',
    stateName: 'Virginia',
    region: 'Southeast',
    peakRutStart: 'November 12',
    peakRutEnd: 'November 26',
    preRutStart: 'October 20',
    seekingPhase: 'November 1 - November 12',
    chasingPhase: 'November 12 - November 20',
    breedingPhase: 'November 15 - November 28',
    postRut: 'November 28 - December 15',
    secondRut: 'December 15 - January 5',
    notes: 'Mountain counties in the west rut earlier than coastal plain. Blue Ridge corridor produces excellent rut action. Shenandoah Valley sees intense chasing along agricultural corridors.',
    scentRecommendation: 'MATE-TRIKS Doe-In-Heat for pre-rut scouting. 200 PROOF during peak chasing in mid-November.',
    huntableSpecies: ['Whitetail', 'Bear', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Oct 5 - Nov 15 & Dec 1 - Jan 4',
      firearm: 'Nov 16 - Nov 30 (rifle)',
      muzzleloader: 'Nov 2 - Nov 15 (early), Dec 7 - Jan 4 (late)',
    },
    keyRegulations: ['Blaze orange required during firearm season', 'Earn-a-Buck in some counties', 'Sunday hunting allowed'],
    agencyName: 'Virginia Dept. of Wildlife Resources',
    agencyUrl: 'https://dwr.virginia.gov',
  },
  {
    stateCode: 'WV',
    stateName: 'West Virginia',
    region: 'Southeast',
    peakRutStart: 'November 10',
    peakRutEnd: 'November 24',
    preRutStart: 'October 15',
    seekingPhase: 'October 28 - November 10',
    chasingPhase: 'November 10 - November 18',
    breedingPhase: 'November 14 - November 26',
    postRut: 'November 26 - December 15',
    secondRut: 'December 12 - December 28',
    notes: 'Mountain state with excellent rut hunting. Ridgetop saddles and benches are prime rut stands. Eastern panhandle sees slightly earlier peak than southern counties. Cold fronts push daytime movement.',
    scentRecommendation: '200 PROOF on ridgeline scrapes. GLAND-U-LURE along rub lines and bench trails. RUCK\'N BUCK on saddle mock scrapes.',
    huntableSpecies: ['Whitetail', 'Bear', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 28 - Dec 31',
      firearm: 'Nov 25 - Dec 8 (buck), Dec 9 - Dec 31 (antlerless)',
      muzzleloader: 'Dec 16 - Dec 31',
    },
    keyRegulations: ['Blaze orange required during gun season (400 sq in)', 'Baiting permitted in some counties', 'Sunday hunting prohibited on public land'],
    agencyName: 'West Virginia DNR',
    agencyUrl: 'https://wvdnr.gov',
  },
  {
    stateCode: 'NC',
    stateName: 'North Carolina',
    region: 'Southeast',
    peakRutStart: 'November 15',
    peakRutEnd: 'November 30',
    preRutStart: 'October 25',
    seekingPhase: 'November 5 - November 15',
    chasingPhase: 'November 15 - November 24',
    breedingPhase: 'November 18 - December 5',
    postRut: 'December 5 - December 25',
    secondRut: 'January 5 - January 20',
    notes: 'Mountain region in the west peaks 1-2 weeks earlier than piedmont or coastal plain. Coastal counties may not see peak breeding until December. Wide variation across the state makes regional knowledge essential.',
    scentRecommendation: 'MATE-TRIKS Original during early seeking. 200 PROOF for mountain hunts in mid-November. Guide Grade for coastal late rut.',
    huntableSpecies: ['Whitetail', 'Bear', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 14 - Oct 25',
      firearm: 'Oct 12 - Jan 1 (varies by zone)',
      muzzleloader: 'Oct 5 - Oct 11 & Jan 2 - Jan 11',
    },
    keyRegulations: ['Blaze orange required during gun season', 'Antler restrictions: 2 pts on one side or 10-in spread', 'Sunday hunting allowed on private land'],
    agencyName: 'North Carolina Wildlife Resources Commission',
    agencyUrl: 'https://www.ncwildlife.org',
  },
  {
    stateCode: 'SC',
    stateName: 'South Carolina',
    region: 'Southeast',
    peakRutStart: 'November 20',
    peakRutEnd: 'December 10',
    preRutStart: 'November 1',
    seekingPhase: 'November 10 - November 20',
    chasingPhase: 'November 20 - December 1',
    breedingPhase: 'November 25 - December 12',
    postRut: 'December 12 - January 5',
    secondRut: 'January 10 - January 28',
    notes: 'Upstate ruts earliest in October-November. Midlands peak in November. Coastal plain and ACE Basin see late December through January breeding. State has one of the widest rut windows in the country.',
    scentRecommendation: 'MATE-TRIKS SPRAY for run-and-gun coastal hunts. 200 PROOF for piedmont sits during peak.',
    huntableSpecies: ['Whitetail', 'Hog', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 15 - Oct 11 & Oct 12 - Jan 1 (varies by zone)',
      firearm: 'Oct 12 - Jan 1 (varies by zone)',
      muzzleloader: 'Oct 1 - Oct 11',
    },
    keyRegulations: ['Blaze orange required on WMA lands during gun season', 'No antler restrictions statewide', 'Baiting allowed on private land'],
    agencyName: 'South Carolina DNR',
    agencyUrl: 'https://www.dnr.sc.gov',
  },
  {
    stateCode: 'GA',
    stateName: 'Georgia',
    region: 'Southeast',
    peakRutStart: 'November 20',
    peakRutEnd: 'December 10',
    preRutStart: 'November 1',
    seekingPhase: 'November 10 - November 20',
    chasingPhase: 'November 20 - December 2',
    breedingPhase: 'November 25 - December 15',
    postRut: 'December 15 - January 5',
    secondRut: 'January 10 - January 25',
    notes: 'North Georgia mountains peak in late October to mid-November. Piedmont peaks in November. Coastal plain sees December through January activity. Pine plantations create excellent travel corridors.',
    scentRecommendation: '200 PROOF for mountain hunts. MATE-TRIKS Doe-In-Heat for piedmont. Guide Grade Doe-In-Heat for coastal trophy bucks.',
    huntableSpecies: ['Whitetail', 'Hog', 'Bear', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 14 - Jan 12',
      firearm: 'Oct 19 - Jan 12 (varies by zone)',
      muzzleloader: 'Oct 12 - Oct 18',
    },
    keyRegulations: ['Blaze orange required during gun season on WMAs', 'Antler restrictions: 4 pts on one side or 15-in spread in some zones', 'Baiting allowed on private land'],
    agencyName: 'Georgia DNR Wildlife Resources Division',
    agencyUrl: 'https://georgiawildlife.com',
  },
  {
    stateCode: 'FL',
    stateName: 'Florida',
    region: 'Southeast',
    peakRutStart: 'December 1',
    peakRutEnd: 'January 15',
    preRutStart: 'November 10',
    seekingPhase: 'November 20 - December 1',
    chasingPhase: 'December 1 - December 15',
    breedingPhase: 'December 10 - January 15',
    postRut: 'January 15 - February 10',
    secondRut: 'February 10 - February 28',
    notes: 'Panhandle ruts earliest (November). North-central zones peak December-January. South Florida subspecies (Key deer) have different timing. Osceola and Seminole types breed later than northern herds.',
    scentRecommendation: 'MATE-TRIKS Original for long-season use. 200 PROOF during December-January peak breeding windows.',
    huntableSpecies: ['Whitetail', 'Hog', 'Turkey', 'Alligator', 'Small Game'],
    seasons: {
      archery: 'Sep 14 - Oct 25 & Jan 20 - Feb 2',
      firearm: 'Nov 2 - Jan 19 (zone-dependent)',
      muzzleloader: 'Nov 30 - Dec 8 (zone-dependent)',
    },
    keyRegulations: ['Blaze orange required during gun season on WMAs', 'Antler restrictions: at least one antler 5 in or more', 'Baiting prohibited on WMAs'],
    agencyName: 'Florida Fish & Wildlife Conservation Commission',
    agencyUrl: 'https://myfwc.com',
  },
  {
    stateCode: 'AL',
    stateName: 'Alabama',
    region: 'Southeast',
    peakRutStart: 'January 10',
    peakRutEnd: 'February 5',
    preRutStart: 'December 10',
    seekingPhase: 'December 25 - January 10',
    chasingPhase: 'January 10 - January 22',
    breedingPhase: 'January 15 - February 8',
    postRut: 'February 8 - March 1',
    secondRut: 'N/A',
    notes: 'Northern counties rut as early as late December. Black Belt region is prime January-February. Southern Alabama sees the latest rut activity. Long hunting season gives multiple opportunities.',
    scentRecommendation: '200 PROOF Ultimate Doe-In-Heat during January peak. RUCK\'N BUCK on mock scrapes starting mid-December.',
    huntableSpecies: ['Whitetail', 'Hog', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Oct 15 - Feb 10',
      firearm: 'Nov 23 - Feb 10 (varies by zone)',
      muzzleloader: 'Nov 11 - Nov 22',
    },
    keyRegulations: ['Blaze orange required during gun season', 'Antler restrictions: 3 pts on one side in some zones', 'Baiting allowed on private land'],
    agencyName: 'Alabama Dept. of Conservation & Natural Resources',
    agencyUrl: 'https://www.outdooralabama.com',
  },
  {
    stateCode: 'MS',
    stateName: 'Mississippi',
    region: 'Southeast',
    peakRutStart: 'December 20',
    peakRutEnd: 'January 20',
    preRutStart: 'November 25',
    seekingPhase: 'December 10 - December 20',
    chasingPhase: 'December 20 - January 5',
    breedingPhase: 'December 25 - January 20',
    postRut: 'January 20 - February 10',
    secondRut: 'February 10 - February 25',
    notes: 'Delta region peaks in December. Hill country and pine belt see later rut. Mississippi has produced world-class bucks. Food plots near hardwood bottoms are prime rut stand locations.',
    scentRecommendation: 'MATE-TRIKS PRO-SIZE for extended Delta sits. 200 PROOF during the late December to January peak window.',
    huntableSpecies: ['Whitetail', 'Hog', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Oct 1 - Nov 22 & Dec 2 - Jan 31',
      firearm: 'Nov 23 - Dec 1 & Dec 26 - Jan 20',
      muzzleloader: 'Dec 2 - Dec 15',
    },
    keyRegulations: ['Blaze orange 500 sq in required during gun season', 'Antler restrictions: 13-in inside spread or 4 pts on one side', 'CWD testing required in select zones'],
    agencyName: 'Mississippi Dept. of Wildlife, Fisheries & Parks',
    agencyUrl: 'https://www.mdwfp.com',
  },

  // ── Midwest ──────────────────────────────────────────────
  {
    stateCode: 'OH',
    stateName: 'Ohio',
    region: 'Midwest',
    peakRutStart: 'November 8',
    peakRutEnd: 'November 22',
    preRutStart: 'October 12',
    seekingPhase: 'October 25 - November 8',
    chasingPhase: 'November 8 - November 16',
    breedingPhase: 'November 12 - November 25',
    postRut: 'November 25 - December 12',
    secondRut: 'December 10 - December 24',
    notes: 'Consistently one of the top trophy-producing states. Eastern agricultural counties are legendary for big bucks. Cold fronts in early November trigger explosive rut activity. All-day sits are a must.',
    scentRecommendation: 'Guide Grade Doe-In-Heat for trophy-class hunts. RUCK\'N BUCK on field-edge mock scrapes starting late October.',
    huntableSpecies: ['Whitetail', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 28 - Feb 2',
      firearm: 'Dec 2 - Dec 8 & Dec 21 - Dec 22 (gun)',
      muzzleloader: 'Jan 4 - Jan 7',
    },
    keyRegulations: ['Blaze orange required during gun season', 'Antler point restrictions in most counties', 'Straight-wall cartridge rifles allowed in shotgun season'],
    agencyName: 'Ohio DNR Division of Wildlife',
    agencyUrl: 'https://ohiodnr.gov/wildlife',
  },
  {
    stateCode: 'MI',
    stateName: 'Michigan',
    region: 'Midwest',
    peakRutStart: 'November 5',
    peakRutEnd: 'November 20',
    preRutStart: 'October 10',
    seekingPhase: 'October 20 - November 5',
    chasingPhase: 'November 5 - November 14',
    breedingPhase: 'November 8 - November 24',
    postRut: 'November 24 - December 12',
    secondRut: 'December 10 - December 24',
    notes: 'UP bucks peak slightly earlier than Lower Peninsula. November 5-15 is the magic window for firearm season. Agricultural southern Michigan produces the biggest bucks. Swamp edges are key travel routes.',
    scentRecommendation: '200 PROOF Ultimate Doe-In-Heat is a Michigan staple. MATE-TRIKS on boot pads for scent trails. GLAND-U-LURE on rubs.',
    huntableSpecies: ['Whitetail', 'Bear', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Oct 1 - Nov 14 & Dec 1 - Jan 1',
      firearm: 'Nov 15 - Nov 30',
      muzzleloader: 'Dec 1 - Dec 15 (Zone 1) / Dec 6 - Jan 1 (Zone 3)',
    },
    keyRegulations: ['Blaze orange required during firearm season', 'Antler point restrictions in some zones', 'Baiting banned in Lower Peninsula'],
    agencyName: 'Michigan DNR',
    agencyUrl: 'https://www.michigan.gov/dnr',
  },
  {
    stateCode: 'IN',
    stateName: 'Indiana',
    region: 'Midwest',
    peakRutStart: 'November 10',
    peakRutEnd: 'November 22',
    preRutStart: 'October 15',
    seekingPhase: 'October 28 - November 10',
    chasingPhase: 'November 10 - November 17',
    breedingPhase: 'November 13 - November 25',
    postRut: 'November 25 - December 12',
    secondRut: 'December 12 - December 26',
    notes: 'South-central Indiana hill country is prime rut territory. River bottom corridors funnel bucks during chasing. Agricultural landscape creates predictable travel patterns between bedding and feeding.',
    scentRecommendation: '200 PROOF during peak. MATE-TRIKS on scrapes and drag rags. RUCK\'N BUCK for pre-rut mock scrape lines.',
    huntableSpecies: ['Whitetail', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Oct 1 - Jan 5',
      firearm: 'Nov 16 - Dec 1',
      muzzleloader: 'Dec 7 - Dec 22',
    },
    keyRegulations: ['Blaze orange required during firearms season', 'One antlered deer per year', 'Rifles prohibited -- shotgun, handgun, or muzzleloader only'],
    agencyName: 'Indiana DNR Division of Fish & Wildlife',
    agencyUrl: 'https://www.in.gov/dnr/fish-and-wildlife',
  },
  {
    stateCode: 'IL',
    stateName: 'Illinois',
    region: 'Midwest',
    peakRutStart: 'November 8',
    peakRutEnd: 'November 22',
    preRutStart: 'October 12',
    seekingPhase: 'October 25 - November 8',
    chasingPhase: 'November 8 - November 16',
    breedingPhase: 'November 12 - November 25',
    postRut: 'November 25 - December 12',
    secondRut: 'December 10 - December 24',
    notes: 'Pike County and surrounding area is world-renowned for trophy whitetails. River bluffs and agricultural bottomlands create perfect rut funnels. November 7-15 is the single best week to be in a stand.',
    scentRecommendation: 'Guide Grade Doe-In-Heat for trophy hunts. 200 PROOF on drag rags through pinch points and saddles.',
    huntableSpecies: ['Whitetail', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Oct 1 - Jan 19',
      firearm: 'Nov 22 - Nov 24 & Dec 5 - Dec 8 (shotgun/rifle)',
      muzzleloader: 'Dec 13 - Dec 15',
    },
    keyRegulations: ['Blaze orange or blaze pink required during firearm season', 'Shotgun only in most counties -- rifles in select southern counties', 'One antlered deer per season unless bonus tags available'],
    agencyName: 'Illinois DNR',
    agencyUrl: 'https://www2.illinois.gov/dnr',
  },
  {
    stateCode: 'WI',
    stateName: 'Wisconsin',
    region: 'Midwest',
    peakRutStart: 'November 5',
    peakRutEnd: 'November 18',
    preRutStart: 'October 10',
    seekingPhase: 'October 22 - November 5',
    chasingPhase: 'November 5 - November 13',
    breedingPhase: 'November 8 - November 22',
    postRut: 'November 22 - December 10',
    secondRut: 'December 8 - December 22',
    notes: 'Buffalo County is legendary for monster bucks. Northern forest bucks rut slightly earlier. Gun season opener typically falls during peak breeding. Funnel hunting between bedding areas is most productive.',
    scentRecommendation: '200 PROOF Ultimate Doe-In-Heat is the go-to. RUCK\'N BUCK on mock scrapes near bedding funnels. GLAND-U-LURE all pre-rut.',
    huntableSpecies: ['Whitetail', 'Bear', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 14 - Jan 5',
      firearm: 'Nov 22 - Nov 30 (gun)',
      muzzleloader: 'Nov 30 - Dec 10',
    },
    keyRegulations: ['Blaze orange or pink required during gun season', 'CWD testing zones -- mandatory sampling in some areas', 'Earn-a-Buck in select counties'],
    agencyName: 'Wisconsin DNR',
    agencyUrl: 'https://dnr.wisconsin.gov',
  },
  {
    stateCode: 'MN',
    stateName: 'Minnesota',
    region: 'Midwest',
    peakRutStart: 'November 5',
    peakRutEnd: 'November 18',
    preRutStart: 'October 8',
    seekingPhase: 'October 20 - November 5',
    chasingPhase: 'November 5 - November 13',
    breedingPhase: 'November 8 - November 22',
    postRut: 'November 22 - December 10',
    secondRut: 'December 8 - December 22',
    notes: 'Southeast bluff country produces the largest bucks. Big woods in the north require different tactics -- focus on doe groups. Transition zone between agricultural and forest is most productive for rut hunters.',
    scentRecommendation: 'MATE-TRIKS Original for big woods. 200 PROOF in agricultural southeast. RUCK\'N BUCK on bluff country scrapes.',
    huntableSpecies: ['Whitetail', 'Bear', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 14 - Dec 31',
      firearm: 'Nov 9 - Nov 17 (A season) & Nov 22 - Dec 8 (B season)',
      muzzleloader: 'Nov 30 - Dec 15',
    },
    keyRegulations: ['Blaze orange required during firearm season', 'Antler point restrictions in some areas', 'CWD management zones with mandatory testing'],
    agencyName: 'Minnesota DNR',
    agencyUrl: 'https://www.dnr.state.mn.us',
  },
  {
    stateCode: 'IA',
    stateName: 'Iowa',
    region: 'Midwest',
    peakRutStart: 'November 8',
    peakRutEnd: 'November 20',
    preRutStart: 'October 12',
    seekingPhase: 'October 25 - November 8',
    chasingPhase: 'November 8 - November 15',
    breedingPhase: 'November 10 - November 24',
    postRut: 'November 24 - December 12',
    secondRut: 'December 10 - December 24',
    notes: 'Consistently the number one trophy whitetail state. One-tag system produces mature bucks. River bottom timber along the Mississippi and Missouri rivers creates world-class rut hunting. November 5-15 is prime.',
    scentRecommendation: 'Guide Grade Doe-In-Heat -- this is where you bring your best. 200 PROOF on scent wicks in river funnels.',
    huntableSpecies: ['Whitetail', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Oct 1 - Dec 6 & Dec 23 - Jan 10',
      firearm: 'Dec 7 - Dec 11 & Dec 14 - Dec 22 (shotgun/rifle)',
      muzzleloader: 'Oct 14 - Oct 25 (early) / Jan 11 - Jan 19 (late)',
    },
    keyRegulations: ['"One Buck Rule" -- one antlered deer per year', 'Blaze orange required during gun season', 'Straight-wall cartridge rifles now allowed in shotgun season'],
    agencyName: 'Iowa DNR',
    agencyUrl: 'https://www.iowadnr.gov',
  },
  {
    stateCode: 'MO',
    stateName: 'Missouri',
    region: 'Midwest',
    peakRutStart: 'November 10',
    peakRutEnd: 'November 22',
    preRutStart: 'October 15',
    seekingPhase: 'October 28 - November 10',
    chasingPhase: 'November 10 - November 18',
    breedingPhase: 'November 14 - November 26',
    postRut: 'November 26 - December 15',
    secondRut: 'December 12 - December 26',
    notes: 'Northern Missouri river breaks produce trophy bucks. Ozark region has lower density but quality deer. Mark Twain National Forest offers excellent public land rut hunting. Creek bottoms are natural funnels.',
    scentRecommendation: '200 PROOF for creek-bottom funnel hunting. MATE-TRIKS PRO-SIZE for all-day Ozark sits. GLAND-U-LURE on field-edge rubs.',
    huntableSpecies: ['Whitetail', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 15 - Nov 15 & Nov 27 - Jan 15',
      firearm: 'Nov 16 - Nov 26 (rifle)',
      muzzleloader: 'Dec 14 - Dec 24',
    },
    keyRegulations: ['Blaze orange 400 sq in required during firearm season', 'Antler point restrictions in some counties', 'Telecheck system mandatory for harvest reporting'],
    agencyName: 'Missouri Dept. of Conservation',
    agencyUrl: 'https://mdc.mo.gov',
  },

  // ── Plains ──────────────────────────────────────────────
  {
    stateCode: 'KS',
    stateName: 'Kansas',
    region: 'Plains',
    peakRutStart: 'November 10',
    peakRutEnd: 'November 22',
    preRutStart: 'October 18',
    seekingPhase: 'October 30 - November 10',
    chasingPhase: 'November 10 - November 18',
    breedingPhase: 'November 14 - November 26',
    postRut: 'November 26 - December 15',
    secondRut: 'December 14 - December 28',
    notes: 'Eastern Kansas river corridors produce Boone & Crockett class bucks annually. Western Kansas CRP fields hold sleeper bucks. Cottonwood river bottoms and agricultural field corners are the best rut stands.',
    scentRecommendation: 'Guide Grade Doe-In-Heat for once-in-a-lifetime hunts. RUCK\'N BUCK on river-bottom mock scrapes.',
    huntableSpecies: ['Whitetail', 'Mule Deer', 'Turkey', 'Antelope', 'Small Game'],
    seasons: {
      archery: 'Sep 15 - Dec 31',
      firearm: 'Dec 3 - Dec 14 (rifle)',
      muzzleloader: 'Sep 15 - Sep 28',
    },
    keyRegulations: ['Blaze orange required during firearm season', 'One antlered deer per permit', 'Nonresident tags limited and draw-only'],
    agencyName: 'Kansas Dept. of Wildlife & Parks',
    agencyUrl: 'https://ksoutdoors.com',
  },
  {
    stateCode: 'NE',
    stateName: 'Nebraska',
    region: 'Plains',
    peakRutStart: 'November 10',
    peakRutEnd: 'November 24',
    preRutStart: 'October 15',
    seekingPhase: 'October 28 - November 10',
    chasingPhase: 'November 10 - November 18',
    breedingPhase: 'November 14 - November 26',
    postRut: 'November 26 - December 15',
    secondRut: 'December 14 - December 28',
    notes: 'Platte River corridor is the trophy belt. Sandhills produce unique hunting opportunities. Eastern Nebraska agricultural areas rival Iowa and Kansas for buck quality. River timber is king during the rut.',
    scentRecommendation: '200 PROOF in river-bottom timber. MATE-TRIKS SPRAY for Sandhills spot-and-stalk. GLAND-U-LURE on CRP field scrapes.',
    huntableSpecies: ['Whitetail', 'Mule Deer', 'Turkey', 'Antelope', 'Small Game'],
    seasons: {
      archery: 'Sep 15 - Jan 15',
      firearm: 'Nov 9 - Nov 17 (rifle)',
      muzzleloader: 'Dec 1 - Dec 31',
    },
    keyRegulations: ['Blaze orange 400 sq in required during firearm season', 'Antler point restrictions in some units', 'CWD management zones in select areas'],
    agencyName: 'Nebraska Game & Parks Commission',
    agencyUrl: 'https://outdoornebraska.gov',
  },
  {
    stateCode: 'SD',
    stateName: 'South Dakota',
    region: 'Plains',
    peakRutStart: 'November 8',
    peakRutEnd: 'November 22',
    preRutStart: 'October 12',
    seekingPhase: 'October 25 - November 8',
    chasingPhase: 'November 8 - November 16',
    breedingPhase: 'November 12 - November 24',
    postRut: 'November 24 - December 12',
    secondRut: 'December 10 - December 24',
    notes: 'Missouri River breaks offer world-class whitetail hunting. Black Hills have unique terrain for rut funnels. Eastern corn belt produces massive bucks. Wind can shut down daytime movement -- hunt lee sides.',
    scentRecommendation: '200 PROOF Ultimate Doe-In-Heat on river break scrapes. RUCK\'N BUCK for pre-rut mock scrape campaigns.',
    huntableSpecies: ['Whitetail', 'Mule Deer', 'Antelope', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 28 - Jan 1',
      firearm: 'Nov 16 - Dec 1 (East River) / Nov 9 - Dec 15 (West River)',
      muzzleloader: 'Dec 1 - Dec 31 (East River)',
    },
    keyRegulations: ['Blaze orange required during rifle season', 'One buck tag per season', 'Nonresident licenses allocated by lottery'],
    agencyName: 'South Dakota Game, Fish & Parks',
    agencyUrl: 'https://gfp.sd.gov',
  },
  {
    stateCode: 'ND',
    stateName: 'North Dakota',
    region: 'Plains',
    peakRutStart: 'November 5',
    peakRutEnd: 'November 18',
    preRutStart: 'October 10',
    seekingPhase: 'October 22 - November 5',
    chasingPhase: 'November 5 - November 13',
    breedingPhase: 'November 8 - November 22',
    postRut: 'November 22 - December 10',
    secondRut: 'December 8 - December 22',
    notes: 'River bottoms along the Missouri hold the best bucks. Cold fronts arrive early and trigger intense rut. Limited tree cover means bucks use river timber heavily. Short but intense rut window.',
    scentRecommendation: 'MATE-TRIKS PRO-SIZE for brutal cold sits. 200 PROOF during the short but explosive peak window.',
    huntableSpecies: ['Whitetail', 'Mule Deer', 'Antelope', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Aug 30 - Jan 5',
      firearm: 'Nov 8 - Nov 24',
      muzzleloader: 'Dec 6 - Dec 22',
    },
    keyRegulations: ['Blaze orange 400 sq in required during firearm season', 'One antlered whitetail per season', 'Nonresident licenses available by lottery only'],
    agencyName: 'North Dakota Game & Fish',
    agencyUrl: 'https://gf.nd.gov',
  },
  {
    stateCode: 'OK',
    stateName: 'Oklahoma',
    region: 'Plains',
    peakRutStart: 'November 15',
    peakRutEnd: 'November 30',
    preRutStart: 'October 25',
    seekingPhase: 'November 5 - November 15',
    chasingPhase: 'November 15 - November 24',
    breedingPhase: 'November 18 - December 5',
    postRut: 'December 5 - December 25',
    secondRut: 'December 25 - January 10',
    notes: 'Cross Timbers and Ouachita regions produce big bucks. Eastern Oklahoma hardwoods see earlier rut than western plains. Red River corridor holds exceptional genetics. Rut peaks later than northern Plains states.',
    scentRecommendation: 'MATE-TRIKS Doe-In-Heat during seeking phase. 200 PROOF for November 15-30 peak window. GLAND-U-LURE on hardwood rubs.',
    huntableSpecies: ['Whitetail', 'Turkey', 'Hog', 'Small Game'],
    seasons: {
      archery: 'Oct 1 - Jan 15',
      firearm: 'Nov 22 - Dec 7 (rifle) & Dec 14 - Dec 25 (holiday antlerless)',
      muzzleloader: 'Oct 26 - Nov 3',
    },
    keyRegulations: ['Blaze orange required during gun season', 'Antler restrictions: 3 pts on one side in some zones', 'CWD surveillance zones in southeastern counties'],
    agencyName: 'Oklahoma Dept. of Wildlife Conservation',
    agencyUrl: 'https://www.wildlifedepartment.com',
  },

  // ── South (TX, LA, AR, TN, KY) ──────────────────────────
  {
    stateCode: 'TX',
    stateName: 'Texas',
    region: 'South',
    peakRutStart: 'December 15',
    peakRutEnd: 'January 15',
    preRutStart: 'November 15',
    seekingPhase: 'December 1 - December 15',
    chasingPhase: 'December 15 - December 28',
    breedingPhase: 'December 20 - January 15',
    postRut: 'January 15 - February 5',
    secondRut: 'February 5 - February 20',
    notes: 'South Texas brush country peaks December-January. Hill Country peaks November-December. North Texas and panhandle rut earlier, closer to November. State has the most whitetails of any state. Regional timing varies dramatically.',
    scentRecommendation: '200 PROOF for South Texas peak. MATE-TRIKS for Hill Country November rut. Guide Grade for managed ranches.',
    huntableSpecies: ['Whitetail', 'Mule Deer', 'Hog', 'Turkey', 'Javelina', 'Quail'],
    seasons: {
      archery: 'Oct 1 - Nov 1',
      firearm: 'Nov 2 - Jan 19 (general)',
      muzzleloader: 'Jan 20 - Feb 2',
    },
    keyRegulations: ['No blaze orange requirement', 'Very liberal bag limits -- varies by county', 'Antler restrictions in select counties (13-in inside spread)'],
    agencyName: 'Texas Parks & Wildlife Dept.',
    agencyUrl: 'https://tpwd.texas.gov',
  },
  {
    stateCode: 'LA',
    stateName: 'Louisiana',
    region: 'South',
    peakRutStart: 'December 20',
    peakRutEnd: 'January 20',
    preRutStart: 'November 25',
    seekingPhase: 'December 10 - December 20',
    chasingPhase: 'December 20 - January 5',
    breedingPhase: 'December 25 - January 20',
    postRut: 'January 20 - February 10',
    secondRut: 'February 10 - February 28',
    notes: 'Northern Louisiana hills rut earlier than coastal marshes. Atchafalaya Basin bucks are massive but hard to access. Agricultural areas in the northeast produce consistently big bucks. Long season offers flexibility.',
    scentRecommendation: 'MATE-TRIKS PRO-SIZE for long southern sits. 200 PROOF during December-January peak. GLAND-U-LURE for pre-rut scouting.',
    huntableSpecies: ['Whitetail', 'Hog', 'Turkey', 'Alligator', 'Small Game'],
    seasons: {
      archery: 'Oct 1 - Jan 31',
      firearm: 'Nov 9 - Dec 6 (modern firearms, varies by area)',
      muzzleloader: 'Nov 2 - Nov 8 & Dec 14 - Dec 22',
    },
    keyRegulations: ['Blaze orange 400 sq in required during gun season', 'Antler restrictions: 4 pts on one side or 13-in spread in some areas', 'Baiting allowed on private land'],
    agencyName: 'Louisiana Dept. of Wildlife & Fisheries',
    agencyUrl: 'https://www.wlf.louisiana.gov',
  },
  {
    stateCode: 'AR',
    stateName: 'Arkansas',
    region: 'South',
    peakRutStart: 'November 15',
    peakRutEnd: 'December 1',
    preRutStart: 'October 25',
    seekingPhase: 'November 5 - November 15',
    chasingPhase: 'November 15 - November 24',
    breedingPhase: 'November 18 - December 5',
    postRut: 'December 5 - December 25',
    secondRut: 'December 28 - January 12',
    notes: 'Ozark region peaks in mid-November. Delta and coastal plain see later activity into December. White River bottoms produce legendary bucks. National forest land offers excellent public access for rut hunts.',
    scentRecommendation: '200 PROOF for Ozark November rut. MATE-TRIKS for Delta hunts. RUCK\'N BUCK on bottom-land scrapes.',
    huntableSpecies: ['Whitetail', 'Bear', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 28 - Feb 28',
      firearm: 'Nov 9 - Dec 8 (modern gun)',
      muzzleloader: 'Oct 19 - Oct 27 & Dec 14 - Dec 22',
    },
    keyRegulations: ['Blaze orange 400 sq in required during gun season', 'Antler restrictions: 3 pts on one side in some zones', 'CWD management area restrictions in northwest counties'],
    agencyName: 'Arkansas Game & Fish Commission',
    agencyUrl: 'https://www.agfc.com',
  },
  {
    stateCode: 'TN',
    stateName: 'Tennessee',
    region: 'South',
    peakRutStart: 'November 12',
    peakRutEnd: 'November 26',
    preRutStart: 'October 20',
    seekingPhase: 'November 2 - November 12',
    chasingPhase: 'November 12 - November 20',
    breedingPhase: 'November 15 - November 28',
    postRut: 'November 28 - December 18',
    secondRut: 'December 18 - January 5',
    notes: 'Middle Tennessee is the trophy zone. Cumberland Plateau funnels create excellent rut stands. West Tennessee agricultural areas rival Midwest for buck quality. East Tennessee mountains peak slightly earlier.',
    scentRecommendation: '200 PROOF for Cumberland Plateau. Guide Grade for West Tennessee trophy hunts. MATE-TRIKS for mountain archery.',
    huntableSpecies: ['Whitetail', 'Bear', 'Turkey', 'Hog', 'Small Game'],
    seasons: {
      archery: 'Sep 28 - Jan 10',
      firearm: 'Nov 23 - Jan 5 (gun)',
      muzzleloader: 'Nov 9 - Nov 22',
    },
    keyRegulations: ['Blaze orange required during gun season', 'Antler restrictions: 3 pts on one side in Unit CWD', 'CWD testing mandatory in select counties'],
    agencyName: 'Tennessee Wildlife Resources Agency',
    agencyUrl: 'https://www.tn.gov/twra',
  },
  {
    stateCode: 'KY',
    stateName: 'Kentucky',
    region: 'South',
    peakRutStart: 'November 10',
    peakRutEnd: 'November 24',
    preRutStart: 'October 15',
    seekingPhase: 'October 28 - November 10',
    chasingPhase: 'November 10 - November 18',
    breedingPhase: 'November 14 - November 26',
    postRut: 'November 26 - December 15',
    secondRut: 'December 14 - December 28',
    notes: 'Western Kentucky is a trophy factory. Land Between the Lakes sees intense rut funneling. Eastern Kentucky mountains hold big bucks in remote hollows. River bottom corridors are prime rut ambush points.',
    scentRecommendation: 'Guide Grade Doe-In-Heat for western KY trophy hunts. 200 PROOF on river-bottom funnels. RUCK\'N BUCK pre-rut.',
    huntableSpecies: ['Whitetail', 'Bear', 'Turkey', 'Small Game'],
    seasons: {
      archery: 'Sep 7 - Jan 20',
      firearm: 'Nov 9 - Nov 24 (modern gun)',
      muzzleloader: 'Oct 19 - Oct 27 & Dec 14 - Dec 22',
    },
    keyRegulations: ['Blaze orange required during gun and muzzleloader seasons', 'One antlered deer per year', 'Telecheck mandatory within 24 hours of harvest'],
    agencyName: 'Kentucky Dept. of Fish & Wildlife Resources',
    agencyUrl: 'https://fw.ky.gov',
  },

  // ── Mountain West ──────────────────────────────────────────
  {
    stateCode: 'MT',
    stateName: 'Montana',
    region: 'Mountain West',
    peakRutStart: 'November 10',
    peakRutEnd: 'November 25',
    preRutStart: 'October 15',
    seekingPhase: 'October 28 - November 10',
    chasingPhase: 'November 10 - November 18',
    breedingPhase: 'November 14 - November 28',
    postRut: 'November 28 - December 15',
    secondRut: 'December 15 - December 30',
    notes: 'Eastern Montana river breaks hold the best whitetail populations. Milk River and Missouri breaks are legendary. Western Montana valleys have whitetails in riparian corridors. Extreme cold can compress the rut window.',
    scentRecommendation: '200 PROOF for river-break hunting. MATE-TRIKS PRO-SIZE for extended cold-weather sits in the breaks.',
    huntableSpecies: ['Whitetail', 'Mule Deer', 'Elk', 'Antelope', 'Bear', 'Mountain Lion'],
    seasons: {
      archery: 'Sep 7 - Oct 18',
      firearm: 'Oct 26 - Dec 1 (general)',
      muzzleloader: 'Dec 7 - Dec 15',
    },
    keyRegulations: ['Blaze orange 400 sq in required during rifle season', 'CWD testing mandatory in some districts', 'One antlered whitetail per general license'],
    agencyName: 'Montana Fish, Wildlife & Parks',
    agencyUrl: 'https://fwp.mt.gov',
  },
  {
    stateCode: 'WY',
    stateName: 'Wyoming',
    region: 'Mountain West',
    peakRutStart: 'November 12',
    peakRutEnd: 'November 25',
    preRutStart: 'October 18',
    seekingPhase: 'November 1 - November 12',
    chasingPhase: 'November 12 - November 20',
    breedingPhase: 'November 15 - November 28',
    postRut: 'November 28 - December 15',
    secondRut: 'December 15 - January 2',
    notes: 'Northeast Wyoming Black Hills and river corridors hold whitetails. Limited whitetail habitat concentrates deer along waterways. Cottonwood bottoms along the Powder and Bighorn rivers are prime spots.',
    scentRecommendation: 'MATE-TRIKS Doe-In-Heat on river-bottom scrapes. 200 PROOF during mid-November peak breeding.',
    huntableSpecies: ['Whitetail', 'Mule Deer', 'Elk', 'Antelope', 'Bear', 'Mountain Lion'],
    seasons: {
      archery: 'Sep 1 - Sep 30',
      firearm: 'Oct 1 - Nov 30 (varies by area)',
      muzzleloader: 'Dec 1 - Dec 31',
    },
    keyRegulations: ['Blaze orange or pink required during firearm season', 'Draw-only for most big game species', 'CWD surveillance in select hunt areas'],
    agencyName: 'Wyoming Game & Fish',
    agencyUrl: 'https://wgfd.wyo.gov',
  },
  {
    stateCode: 'CO',
    stateName: 'Colorado',
    region: 'Mountain West',
    peakRutStart: 'November 12',
    peakRutEnd: 'November 26',
    preRutStart: 'October 18',
    seekingPhase: 'November 1 - November 12',
    chasingPhase: 'November 12 - November 20',
    breedingPhase: 'November 16 - November 28',
    postRut: 'November 28 - December 18',
    secondRut: 'December 18 - January 5',
    notes: 'Eastern plains whitetails along the South Platte and Arkansas rivers. Front Range foothills hold suburban populations. Limited whitetail range but excellent quality. Agricultural river corridors are the ticket.',
    scentRecommendation: '200 PROOF on South Platte river-bottom scrapes. MATE-TRIKS SPRAY for quick application on cold hunts.',
    huntableSpecies: ['Mule Deer', 'Elk', 'Antelope', 'Bear', 'Mountain Lion', 'Whitetail'],
    seasons: {
      archery: 'Sep 2 - Sep 30',
      firearm: 'Oct 12 - Nov 3 (varies by unit)',
      muzzleloader: 'Sep 14 - Sep 22',
    },
    keyRegulations: ['Blaze orange 500 sq in required during rifle season', 'Draw-only for most rifle units', 'CWD management zones in northeast counties'],
    agencyName: 'Colorado Parks & Wildlife',
    agencyUrl: 'https://cpw.state.co.us',
  },
  {
    stateCode: 'ID',
    stateName: 'Idaho',
    region: 'Mountain West',
    peakRutStart: 'November 15',
    peakRutEnd: 'November 28',
    preRutStart: 'October 20',
    seekingPhase: 'November 2 - November 15',
    chasingPhase: 'November 15 - November 22',
    breedingPhase: 'November 18 - December 2',
    postRut: 'December 2 - December 20',
    secondRut: 'December 20 - January 5',
    notes: 'Northern Idaho panhandle has the strongest whitetail population. Clearwater and Coeur d\'Alene river systems hold good numbers. Agricultural valleys in the Palouse see consistent rut activity.',
    scentRecommendation: 'MATE-TRIKS Original for northern Idaho. 200 PROOF during November 15-28 peak window.',
    huntableSpecies: ['Whitetail', 'Mule Deer', 'Elk', 'Bear', 'Mountain Lion'],
    seasons: {
      archery: 'Aug 30 - Sep 30',
      firearm: 'Oct 10 - Nov 20 (varies by unit)',
      muzzleloader: 'Dec 1 - Dec 15',
    },
    keyRegulations: ['Blaze orange 36 sq in on head recommended during firearm season', 'Tags are unit-specific -- check regulations', 'Wolf hunting allowed with valid tag'],
    agencyName: 'Idaho Fish & Game',
    agencyUrl: 'https://idfg.idaho.gov',
  },
  {
    stateCode: 'NV',
    stateName: 'Nevada',
    region: 'Mountain West',
    peakRutStart: 'November 18',
    peakRutEnd: 'December 2',
    preRutStart: 'October 25',
    seekingPhase: 'November 5 - November 18',
    chasingPhase: 'November 18 - November 26',
    breedingPhase: 'November 22 - December 5',
    postRut: 'December 5 - December 25',
    secondRut: 'N/A',
    notes: 'Very limited whitetail habitat. Small populations along the Humboldt River and eastern Nevada mountain ranges. Mule deer are the primary species. Whitetail opportunities exist but require specific unit knowledge.',
    scentRecommendation: 'MATE-TRIKS Doe-In-Heat for the limited whitetail opportunities. Cover scents essential in open terrain.',
    huntableSpecies: ['Mule Deer', 'Elk', 'Antelope', 'Bear', 'Mountain Lion'],
    seasons: {
      archery: 'Aug 10 - Sep 1 (varies by unit)',
      firearm: 'Oct 10 - Nov 5 (varies by unit)',
      muzzleloader: 'Sep 15 - Oct 5 (varies by unit)',
    },
    keyRegulations: ['Blaze orange required during firearm season', 'Draw-only for most big game', 'Very limited whitetail opportunities'],
    agencyName: 'Nevada Dept. of Wildlife',
    agencyUrl: 'https://www.ndow.org',
  },
  {
    stateCode: 'UT',
    stateName: 'Utah',
    region: 'Mountain West',
    peakRutStart: 'November 15',
    peakRutEnd: 'November 30',
    preRutStart: 'October 22',
    seekingPhase: 'November 5 - November 15',
    chasingPhase: 'November 15 - November 24',
    breedingPhase: 'November 18 - December 2',
    postRut: 'December 2 - December 20',
    secondRut: 'N/A',
    notes: 'Limited whitetail populations primarily in the northeast. Mule deer are the dominant species. Where whitetails exist, they follow similar rut timing to surrounding mountain states.',
    scentRecommendation: 'MATE-TRIKS for limited whitetail encounters. Focus mule deer hunting with appropriate tactics.',
    huntableSpecies: ['Mule Deer', 'Elk', 'Antelope', 'Bear', 'Mountain Lion'],
    seasons: {
      archery: 'Aug 17 - Sep 13',
      firearm: 'Oct 19 - Nov 3 (general)',
      muzzleloader: 'Sep 25 - Oct 8',
    },
    keyRegulations: ['Blaze orange 400 sq in required during any firearm hunt', 'Draw-only for most hunts', 'CWD sampling required in some units'],
    agencyName: 'Utah Division of Wildlife Resources',
    agencyUrl: 'https://wildlife.utah.gov',
  },
  {
    stateCode: 'NM',
    stateName: 'New Mexico',
    region: 'Mountain West',
    peakRutStart: 'November 20',
    peakRutEnd: 'December 5',
    preRutStart: 'October 28',
    seekingPhase: 'November 10 - November 20',
    chasingPhase: 'November 20 - November 30',
    breedingPhase: 'November 25 - December 8',
    postRut: 'December 8 - December 28',
    secondRut: 'N/A',
    notes: 'Northeastern New Mexico along the Canadian River holds Coues whitetails. Pecos River corridor has huntable populations. Agricultural areas near Clovis and Portales see rut activity similar to West Texas.',
    scentRecommendation: '200 PROOF for river-corridor hunts. MATE-TRIKS SPRAY for spot-and-stalk situations in open country.',
    huntableSpecies: ['Mule Deer', 'Elk', 'Antelope', 'Bear', 'Oryx', 'Mountain Lion'],
    seasons: {
      archery: 'Sep 1 - Sep 24 (varies by unit)',
      firearm: 'Oct 19 - Nov 10 (varies by unit)',
      muzzleloader: 'Oct 5 - Oct 18',
    },
    keyRegulations: ['Blaze orange required during rifle season', 'Draw-only for deer and elk', 'Oryx hunting on White Sands available by lottery'],
    agencyName: 'New Mexico Dept. of Game & Fish',
    agencyUrl: 'https://www.wildlife.state.nm.us',
  },
  {
    stateCode: 'AZ',
    stateName: 'Arizona',
    region: 'Mountain West',
    peakRutStart: 'December 1',
    peakRutEnd: 'January 10',
    preRutStart: 'November 10',
    seekingPhase: 'November 20 - December 1',
    chasingPhase: 'December 1 - December 15',
    breedingPhase: 'December 10 - January 10',
    postRut: 'January 10 - February 1',
    secondRut: 'N/A',
    notes: 'Coues whitetail is the primary subspecies. Southeast Arizona sky islands are the heartland. Tiny deer but incredible challenge. Glassing and stalking is the primary method. December-January is the window.',
    scentRecommendation: 'MATE-TRIKS Original for Coues deer scrapes. Light application -- these deer have incredible noses in thin desert air.',
    huntableSpecies: ['Coues Whitetail', 'Mule Deer', 'Elk', 'Javelina', 'Bear', 'Mountain Lion'],
    seasons: {
      archery: 'Aug 23 - Sep 12 (varies by unit)',
      firearm: 'Oct 18 - Nov 14 (varies by unit)',
      muzzleloader: 'Dec 13 - Dec 26 (Coues)',
    },
    keyRegulations: ['Blaze orange required during general rifle season', 'Draw-only for all big game', 'Coues whitetail has separate season and unit structure'],
    agencyName: 'Arizona Game & Fish Dept.',
    agencyUrl: 'https://www.azgfd.com',
  },

  // ── Pacific West ──────────────────────────────────────────
  {
    stateCode: 'WA',
    stateName: 'Washington',
    region: 'Pacific West',
    peakRutStart: 'November 15',
    peakRutEnd: 'December 1',
    preRutStart: 'October 22',
    seekingPhase: 'November 3 - November 15',
    chasingPhase: 'November 15 - November 24',
    breedingPhase: 'November 18 - December 5',
    postRut: 'December 5 - December 25',
    secondRut: 'December 28 - January 10',
    notes: 'Eastern Washington has the best whitetail populations. Palouse agricultural region produces good bucks. Western Washington is primarily blacktail deer. Spokane area has strong suburban whitetail herds.',
    scentRecommendation: 'MATE-TRIKS Doe-In-Heat for eastern WA. 200 PROOF during November 15-December 1 peak window.',
    huntableSpecies: ['Whitetail', 'Mule Deer', 'Elk', 'Bear', 'Mountain Lion'],
    seasons: {
      archery: 'Sep 1 - Sep 30',
      firearm: 'Oct 12 - Oct 25 (modern)',
      muzzleloader: 'Nov 23 - Dec 8',
    },
    keyRegulations: ['Blaze orange 400 sq in required during modern firearm season', 'Species-specific tags required', 'CWD testing in some game management units'],
    agencyName: 'Washington Dept. of Fish & Wildlife',
    agencyUrl: 'https://wdfw.wa.gov',
  },
  {
    stateCode: 'OR',
    stateName: 'Oregon',
    region: 'Pacific West',
    peakRutStart: 'November 18',
    peakRutEnd: 'December 5',
    preRutStart: 'October 25',
    seekingPhase: 'November 5 - November 18',
    chasingPhase: 'November 18 - November 28',
    breedingPhase: 'November 22 - December 8',
    postRut: 'December 8 - December 28',
    secondRut: 'January 5 - January 18',
    notes: 'Limited whitetail range in northeast Oregon. Blacktail deer dominate western Oregon. Where whitetails exist, they follow northern rut patterns. Umatilla and Wallowa counties are the best bet.',
    scentRecommendation: 'MATE-TRIKS Original for whitetail areas. Cover scents are essential in Pacific Northwest humidity.',
    huntableSpecies: ['Mule Deer', 'Blacktail', 'Elk', 'Bear', 'Mountain Lion'],
    seasons: {
      archery: 'Aug 24 - Sep 27',
      firearm: 'Oct 5 - Nov 8 (varies by unit)',
      muzzleloader: 'Nov 16 - Nov 22',
    },
    keyRegulations: ['Blaze orange 400 sq in required during rifle season', 'Controlled hunt tags for most units', 'Whitetail limited to northeast Oregon units'],
    agencyName: 'Oregon Dept. of Fish & Wildlife',
    agencyUrl: 'https://www.dfw.state.or.us',
  },
  {
    stateCode: 'CA',
    stateName: 'California',
    region: 'Pacific West',
    peakRutStart: 'November 20',
    peakRutEnd: 'December 10',
    preRutStart: 'October 28',
    seekingPhase: 'November 8 - November 20',
    chasingPhase: 'November 20 - December 1',
    breedingPhase: 'November 25 - December 12',
    postRut: 'December 12 - January 5',
    secondRut: 'N/A',
    notes: 'Very limited whitetail habitat. Columbian whitetails in the north are protected. Blacktail and mule deer are the primary species. Whitetail hunting opportunities are extremely limited within the state.',
    scentRecommendation: 'MATE-TRIKS for any whitetail encounters. Focus primarily on blacktail and mule deer hunting.',
    huntableSpecies: ['Mule Deer', 'Blacktail', 'Bear', 'Wild Pig'],
    seasons: {
      archery: 'Jul 13 - Sep 22 (A zone) / Oct 12 - Nov 3 (B zone)',
      firearm: 'Sep 21 - Nov 3 (varies by zone)',
      muzzleloader: 'Nov 9 - Dec 22 (D zones)',
    },
    keyRegulations: ['Blaze orange not required but recommended', 'Lead ammo banned for all hunting', 'Columbian whitetail is a protected species -- no hunting'],
    agencyName: 'California Dept. of Fish & Wildlife',
    agencyUrl: 'https://wildlife.ca.gov',
  },
  {
    stateCode: 'AK',
    stateName: 'Alaska',
    region: 'Pacific West',
    peakRutStart: 'November 15',
    peakRutEnd: 'December 5',
    preRutStart: 'October 20',
    seekingPhase: 'November 1 - November 15',
    chasingPhase: 'November 15 - November 25',
    breedingPhase: 'November 20 - December 8',
    postRut: 'December 8 - December 28',
    secondRut: 'N/A',
    notes: 'Sitka blacktail deer are the primary deer species. No whitetails in Alaska. Timing listed is for Sitka blacktail rut in Southeast Alaska. Kodiak Island and Prince of Wales Island are top destinations.',
    scentRecommendation: 'MATE-TRIKS can work on Sitka blacktails. Cover scents essential in the temperate rainforest environment.',
    huntableSpecies: ['Sitka Blacktail', 'Moose', 'Caribou', 'Bear', 'Mountain Goat'],
    seasons: {
      archery: 'Aug 1 - Dec 31 (varies by GMU)',
      firearm: 'Aug 1 - Dec 31 (varies by GMU)',
      muzzleloader: 'Aug 1 - Dec 31 (varies by GMU)',
    },
    keyRegulations: ['No blaze orange requirement', 'Bag limits vary widely by game management unit', 'No whitetails present -- Sitka blacktail is primary deer species'],
    agencyName: 'Alaska Dept. of Fish & Game',
    agencyUrl: 'https://www.adfg.alaska.gov',
  },
  {
    stateCode: 'HI',
    stateName: 'Hawaii',
    region: 'Pacific West',
    peakRutStart: 'November 20',
    peakRutEnd: 'December 15',
    preRutStart: 'October 28',
    seekingPhase: 'November 10 - November 20',
    chasingPhase: 'November 20 - December 1',
    breedingPhase: 'November 25 - December 15',
    postRut: 'December 15 - January 10',
    secondRut: 'N/A',
    notes: 'Axis deer on Maui and Molokai breed year-round with peak activity in late fall. No whitetails present. Axis deer and blacktail deer on Lanai offer unique hunting. Different species require different approaches.',
    scentRecommendation: 'Axis deer respond differently to scent. Contact Buck Stop for species-specific recommendations.',
    huntableSpecies: ['Axis Deer', 'Blacktail', 'Mouflon Sheep', 'Wild Pig', 'Wild Goat'],
    seasons: {
      archery: 'Year-round on private land (varies by island)',
      firearm: 'Year-round on private land / Seasonal public hunts by lottery',
      muzzleloader: 'Included in general firearm seasons',
    },
    keyRegulations: ['No blaze orange requirement', 'Public hunting access by lottery permit only', 'Axis deer and wild pig have no bag limits on private land'],
    agencyName: 'Hawaii DLNR Division of Forestry & Wildlife',
    agencyUrl: 'https://dlnr.hawaii.gov/dofaw',
  },
];

export const allStateRutData: StateRutData[] = stateRutData;

/** Get rut data for a specific state */
export function getStateRutData(stateCode: string): StateRutData | undefined {
  return allStateRutData.find((s) => s.stateCode === stateCode);
}

/** Get all states in a region */
export function getStatesByRegion(region: RutRegion): StateRutData[] {
  return allStateRutData.filter((s) => s.region === region);
}
